### ISSUE TITLE
AST replacement of sub-expressions

### ISSUE THREAD

**Issue by theoilie** [cel-expr/cel-go#1000]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [x] The change is large enough it can't be addressed with a simple Pull Request
- [x] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**
I'm wondering about a sort of AST replacement for sub-expressions. If my expression contains a variable which is a placeholder for another expression, then I replace it with the string before compiling. However, the variable in question would've already been compiled previously, so I already have its AST. I'm wondering if it's possible to use this AST instead of having to do manual string replacement.

**Example**
 Let's say expressions `a` and `b` evaluate to doubles:
 ```go
a := "1.0 + 1.0"
aAST := env.Compile(a)
b := "a + 1.0"
bAST := env.Compile(b)
 ```

Now for expression `a + b` could it be possible to use the already-compiled ASTs for `a` and `b`?
```go
env := cel.NewEnv([]cel.EnvOption{cel.Variable("a", cel.DoubleType), cel.Variable("b", cel.DoubleType)})

// We have to actually replace a and b here with their actual string expression (eg, "1.0 + 1.0").
// Otherwise, when we provide values in prg.Eval() below, the values have to be double type, not the string expression
cAST := env.Compile("a + b")
prg := myPrg(cAST)

// Values for a and b in this map have to be already evaluated into double type.
// We can't do "1.0 + 1.0" for "a" or else we're giving a string type for what's supposed to be a double.
// Is it possible to have a type here which is double but can use the already-compiled ASTs for a and b?
prg.Eval(map[string]any{"a": aAST, "b": bAST})
```

**Alternatives considered**
The alternative I'm doing works, but it involves having to re-compile an expression which was already previously compiled. Specifically, the alternative is: before compiling, recursively find all variable names and replace them with their string expressions so that the whole expression string gets compiled without any variables.

**Comment by TristonianJones** [comment]
Hi @theoilie, you may want to look at using the `cel/inclining.go` approach for combining expressions. It should do what you want, at least for generating new ASTs

-Tristan

**Comment by theoilie** [comment]
> Hi @theoilie, you may want to look at using the `cel/inclining.go` approach for combining expressions. It should do what you want, at least for generating new ASTs
> 
> -Tristan

This looks perfect -- thank you very much!
