### ISSUE TITLE
Comparing typed nil value to null returns false

### ISSUE THREAD

**Issue by utahta** [cel-expr/cel-go#1020]
**Describe the bug**
As shown in the reproduce code below, in the expression `val == null`, false is returned if typed nil is assigned to val.
I'm not sure if this behavior is intended or not, but in my opinion it is counterintuitive and confusing.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

Sample expression and input that reproduces the issue:
```cel
val == null
```

Test setup:
```go
envOps := []cel.EnvOption{
    cel.Types(&errdetails.ErrorInfo{}),
    cel.Declarations(decls.NewVar("val", decls.NewObjectType("google.rpc.ErrorInfo"))),
}
env, _ := cel.NewEnv(envOps...)
ast, _ := env.Compile("val == null")
prg, _ := env.Program(ast)

var p *errdetails.ErrorInfo
out, _, _ = prg.Eval(map[string]interface{}{
    "val": p,
})
fmt.Printf("%v\n", out) // output false
```

**Expected behavior**
We expect to get true by comparing a typed nil value to null.

**Additional context**
Thanks for the great OSS. We are using cel-go heavily in [mercari/grpc-federation](https://github.com/mercari/grpc-federation).
In our OSS, we want to call the gRPC method, assign the result to a variable, and compare it to null.

**Comment by TristonianJones** [comment]
Hi @utahta, the equality check in CEL always validates the type and value. Since the types don't agree (type of null is null_type and corresponds to a concrete JSON null), the result will always be false. 

Instead, I would recommend enabling `cel.OptionalTypes()` and publishing the value as optional. This will allow you to check `val.hasValue()` which I think reads more clearly.

**Comment by utahta** [comment]
Thank you for the quick reply!
I changed the code as follows, but the result was the same. (I know this is not what I want to do to begin with since it's checking for a zero value not nil)
Is there any example regarding the point of publishing the value as optional?

```go
envOps := []cel.EnvOption{
	cel.OptionalTypes(),
	cel.Types(&errdetails.ErrorInfo{}),
	cel.Declarations(decls.NewVar("val", decls.NewObjectType("google.rpc.ErrorInfo"))),
}
env, _ := cel.NewEnv(envOps...)
ast, _ := env.Compile("!optional.ofNonZeroValue(val).hasValue()")
prg, _ := env.Program(ast)

var p *errdetails.ErrorInfo
out, _, _ = prg.Eval(map[string]interface{}{
	"val": p,
})
fmt.Printf("%v\n", out)
```

**Comment by TristonianJones** [comment]
@utahta , good question! You'd want to change the declaration of `val`:

```go
envOps := []cel.EnvOption{
	cel.OptionalTypes(),
	cel.Types(&errdetails.ErrorInfo{}),
	cel.Declarations(decls.NewVar("val", cel.OptionalType(cel.ObjectType("google.rpc.ErrorInfo")))),
}
env, _ := cel.NewEnv(envOps...)
ast, _ := env.Compile("!val.hasValue()")
prg, _ := env.Program(ast)

var p *errdetails.ErrorInfo
out, _, _ = prg.Eval(map[string]interface{}{
	"val": types.OptionalNone(),
})
fmt.Printf("%v\n", out)
```

**Comment by utahta** [comment]
Thank you for your example!
I tried the case with types.OptionalNone assigned to val and confirmed that it works as expected.
However, I got `'no such overload: hasValue(google.rpc.ErrorInfo)'` error in the case where I assigned an object to val.
Is there any way to determine if both cases are nil with the same expression?

```go
envOps := []cel.EnvOption{
	cel.OptionalTypes(),
	cel.Types(&errdetails.ErrorInfo{}),
	cel.Declarations(decls.NewVar("val", decls.NewOptionalType(decls.NewObjectType("google.rpc.ErrorInfo")))),
}
env, _ := cel.NewEnv(envOps...)
ast, _ := env.Compile("!val.hasValue()")
prg, _ := env.Program(ast)

var val any
errInfo := &errdetails.ErrorInfo{}
// errInfo := (*errdetails.ErrorInfo)(nil)
if errInfo != nil {
	val = errInfo
} else {
	val = types.OptionalNone
}
out, _, err := prg.Eval(map[string]interface{}{
	"val": val,
})
if err != nil {
    fmt.Printf("%v\n", err) // output: no such overload: hasValue(google.rpc.ErrorInfo)
    return
}
fmt.Printf("%#v\n", out)
```

**Comment by TristonianJones** [comment]
@utahta You're very close, but you need to update the following line:

```go
if errInfo != nil {
	val = types.OptionalOf(errInfo)
} else {
	val = types.OptionalNone
}
```

**Comment by utahta** [comment]
I have confirmed that it works as expected with the following code.
Thank you for your kind instruction!

```go
if errInfo != nil {
	val = types.OptionalOf(env.CELTypeAdapter().NativeToValue(errInfo))
} else {
	val = types.OptionalNone
}
```
