### ISSUE TITLE
Provide a helper to convert go types to ref.Val

### ISSUE THREAD

**Issue by alvaroaleman** [cel-expr/cel-go#1022]
Cel-Go already provides an adapter to use golang types in a cel program in the form of `ext.NativeTypes` which allows to use arbitrary go types in cel program.
What does not seem to be possible is to then use these go types in custom functions, it fails with an `unsupported conversion to ref.Val`.  
From what I can tell, there is no helper to go from golang type to ref.Val, forcing users to implement it themselves.

**Feature request checklist**

- [X] There are no issues that match the desired change
- [ ] The change is large enough it can't be addressed with a simple Pull Request
- [ ] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**
Summary of the proposed change and some details about what problem
it helps solve.

**Example**
Replace this text with an example indicating the desired functionality.

**Alternatives considered**
Briefly list alternative designs, or an example of the functionality to be replaced.

**Comment by TristonianJones** [comment]
@alvaroaleman would you be able to provide a repro case? My expectation is that the native values are converted to `ref.Val` instances so I'm not sure where the issue crops up.

**Comment by alvaroaleman** [comment]
So while writing the repro I learned that this issue only occurs when using `cel.CustomTypeAdapter`, it looks like that overrides rather than extends the available types. We have such an adapter to convert a custom string type to a string.  Below the repro, I've included the the exact same adapter code we actually use for illustration:
```
package main

import (
	"context"
	"fmt"
	"reflect"

	"github.com/google/cel-go/cel"
	"github.com/google/cel-go/common/types"
	celref "github.com/google/cel-go/common/types/ref"
	"github.com/google/cel-go/ext"
)

func main() {
	env, err := cel.NewEnv(
		ext.NativeTypes(reflect.TypeOf(MyType{})),
		cel.CustomTypeAdapter(&celAdapter{}),
		cel.Variable("MyType", cel.ObjectType("main.MyType")),
		cel.Function("CustomMatcher",
			cel.Overload("CustomMatcher", []*cel.Type{cel.ObjectType("main.MyType")}, cel.BoolType,
				cel.UnaryBinding(func(value celref.Val) celref.Val {
					raw, err := value.ConvertToNative(reflect.TypeOf(MyType{}))
					if err != nil {
						return types.NewErr("failed to convert: %v", err)
					}
					myType, ok := raw.(MyType)
					if !ok {
						return types.NewErr("failed to assert, rawType is %T", raw)
					}

					return types.Bool(CustomMatcher(myType))
				}),
			),
		),
	)
	if err != nil {
		panic(err)
	}

	ast, issues := env.Compile(`CustomMatcher(MyType)`)
	if err := issues.Err(); err != nil {
		panic(err)
	}
	program, err := env.Program(ast)
	if err != nil {
		panic(err)
	}
	result, _, err := program.ContextEval(context.Background(), map[string]any{
		"MyType": MyType{},
	})
	if err != nil {
		panic(err)
	}
	fmt.Printf("result: %v\n", result)
}

type MyType struct {
	SomeField string
}

func CustomMatcher(m MyType) bool {
	return m.SomeField == "some value"
}

type celAdapter struct{}

func (a *celAdapter) NativeToValue(value interface{}) celref.Val {
	switch v := value.(type) {
	case CustomStringType:
		return types.DefaultTypeAdapter.NativeToValue(string(v))
	default:
		return types.DefaultTypeAdapter.NativeToValue(v)
	}
}

type CustomStringType string

```

**Comment by TristonianJones** [comment]
I would recommend creating a composed provider or adapter since you'll need to proxy to the native type provider rather than the default type adapter, e.g.

```go
// setup
baseEnv, err := env, err := cel.NewEnv(
    ext.NativeTypes(reflect.TypeOf(MyType{})))
adapter := &celAdapter{Adapter: baseEnv.CELTypeAdapter()}
env, err := baseEnv.Extend(
    cel.CustomTypeAdapter(adapter), ...)
```

```go
// usage
type celAdapter struct{
  types.Adapter
}

func (a *celAdapter) NativeToValue(value interface{}) celref.Val {
	switch v := value.(type) {
	case CustomStringType:
		return types.DefaultTypeAdapter.NativeToValue(string(v))
	default:
		return a.Adapter.NativeToValue(v)
	}
}
```

**Comment by alvaroaleman** [comment]
Thanks for the suggestion, that fixes it! I didn't realize you can get the adapter out. It might be nice to find a way to pass the upstream adapter to the custom adapter to avoid needing the two step process and make this easier to discover
