### ISSUE TITLE
cel.Types and CustomTypeProvider

### ISSUE THREAD

**Issue by eddycharly** [cel-expr/cel-go#1053]
From the comment in `cel.Types` env option:
```
// Note: This option must be specified after the CustomTypeProvider option when used together.
```

But the implementation assumes the provider is a `types.Registry`.
How can this happen **after** the `CustomTypeProvider` option ?

What am i missing here ?

**Comment by TristonianJones** [comment]
The implementation depends on support for registering protobuf types,
but it doesn't strictly require the provider must be `types.Registry`.

If the `CustomTypeProvider` implements the following methods, then
this option will still work:

```go
// customTypeRegistry is an internal-only interface containing the minimum methods
// required to support custom types. It is a subset of methods from ref.TypeRegistry.
type customTypeRegistry interface {
    RegisterDescriptor(protoreflect.FileDescriptor) error
    RegisterType(...ref.Type) error
}
``` 

In terms of order of operations, you'd do the following:

```go
cel.NewEnv(
  cel.CustomTypeProvider(<your-provider-here>),
  cel.Types(<your-types-here>),
)
```

**Comment by eddycharly** [comment]
Thanks but i still don't get why it **must** be specified **after** the CustomTypeProvider.

Is this supposed to be invalid ?

```golang
cel.NewEnv(
  cel.Types(<your-types-here>),
  cel.CustomTypeProvider(<your-provider-here>),
)
```
