### ISSUE TITLE
Using native Go struct for variable declaration

### ISSUE THREAD

**Issue by danlinxie** [cel-expr/cel-go#1065]
Hi folks! I'm new to the library and curious if there's any way to make CEL support a native Go struct in program environment?

Here's my use case in mind:
```go
type UserAgent struct {
	DeviceAppLanguage string
	DeviceOs          string
        // other fields...
}

// evaluate: `UserAgent.DeviceOs == "ios" && UserAgent.DeviceAppLanguage == "en"`
```

From my understand, I'd have to generate protobuf go struct from something like:
```proto
syntax = "proto3";

package main;

option go_package = ".;main";

message UserAgent {
  string DeviceAppLanguage = 1;
  string DeviceOs = 2;
}
```
And apply it to program env:
```go
env, err := cel.NewEnv(
	cel.Types(&UserAgent{}),
	cel.Variable("UserAgent", cel.ObjectType("main.UserAgent")),
)
```

Is this the expected setup for using a strongly typed object with CEL? or there is something simpler (e.g. not involving protobuf)?

**Comment by TristonianJones** [comment]
Hi @danlinxie, 

You may want to consider using `ext/native.go` as a way of enabling the use of Go structs in CEL which is `ext.NativeTypes(&UserAgent{})` where the `UserAgent` refers to your Go struct. 

You may find this test setup useful:

https://github.com/google/cel-go/blob/f8ecaa2a9a5ec4e9585e92794e66bef7cceb41b8/ext/native_test.go#L947-L955

-Tristan

**Comment by danlinxie** [comment]
Thank you @TristonianJones! This is working great:
```go
env, err := cel.NewEnv(
	ext.NativeTypes(reflect.TypeOf(&UserAgent{})),
	cel.Variable("UserAgent", cel.ObjectType("main.UserAgent")),
)
```
