### ISSUE TITLE
How to Override Relational Operators & 'matches' to Support Null on LHS

### ISSUE THREAD

**Issue by amcrn** [cel-expr/cel-go#1066]
I'm trying to override an operator like `>` to allow `null` on the left-hand-side, and if it is `null`, it should just evaluate to `false`.

Example: `x > 3`
If `x` is null it should return `false`.

Context: I'm converting from a different expression language to CEL, and that expression language is "null safe". Meaning it allows operations like the above, and it also allows things like `x.matches('^foo')`, where if `x` is null it simply returns false.

It looks like `cel.OptionalTypes` does not help here, and converting to `x != null && x > 3` is not desirable (some upstream systems need a 1:1 keyword replacement, not an expansion of the statement).

I've tried to write an `Overload`, but I get one of the following with every permutation I've tried:

* `function declaration merge failed: overload signature collision in function`
* `singleton function incompatible with specialized overloads`

Any help would be appreciated! Thanks!

**Comment by TristonianJones** [comment]
The primitive types in CEL are not nullable, so in this sense CEL is "null safe" in that `null` won't under the system if you're using strong types. Dynamic types such as JSON require a concrete `null` which is supported by the protobuf type `google.protobuf.Value`, so dynamic types come with a nullability caveat which is reflected in how missing map keys are treated as errors in CEL. 

There are protobuf wrapper types which are treated like boxed primitives by proto, so you could declare `x` as `google.protobuf.Int64Value` and then `x` will be assignable to `null`; however, if `x == null` you'll have to type or value-guard all expressions that use `x` and it's likely to lead to a broken experience at runtime. I don't recommend using `null` or the wrapper types if you can avoid it.

As for optional types, you'd need to declare `x` as `optional_type(int)` and then supply it to the evaluation as `types.OptionalOf(<int>)` or `types.OptionalNone`. The statement would then read as follows: `x.hasValue() ? x.value() > 3 : false`, or you could use a streaming-style macro: `x.optMap(val, val > 3).orValue(false)`. It may not be as succinct, but it's definitely less error prone and plays well with chaining, e.g. `x.or(y).or(z).orValue(3)`.
