### ISSUE TITLE
Partial evaluation fails for folded expressions

### ISSUE THREAD

**Issue by charithe** [cel-expr/cel-go#1079]
**Describe the bug**

When partially evaluating an expression like `foo.exists(t, t == bar.baz)` where `bar` is declared as an unknown pattern, CEL 0.22.0 fails with `no such attribute(s): bar.baz`. This wasn't the case with previous CEL versions. When digging into this, it turns out that CEL 0.22.0 converts the `exists` expression into a foldable expression. Because the activation passed to the eval method is embedded into the `folder` object, the underlying type of the activation gets lost. This results in the attribute resolution logic failing because the [`toPartialActivation`](https://github.com/google/cel-go/blob/5d18e93d204801cbe02158a0ddb3a3abce29e4ed/interpreter/attribute_patterns.go#L388) function cannot detect partial activations and grab the unknown patterns from them any more.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

Sample expression and input that reproduces the issue:
```cel
foo.exists(t, t == bar.baz)
```

Test setup:
```go
package main

import (
	"log"

	"github.com/google/cel-go/cel"
	"github.com/google/cel-go/checker/decls"
)

func main() {
	env, err := cel.NewEnv(cel.Declarations(
		decls.NewVar("bar", decls.NewMapType(decls.String, decls.Dyn)),
		decls.NewVar("foo", decls.NewMapType(decls.String, decls.Dyn)),
	))
	exitOnErr(err)

	pvars, err := cel.PartialVars(
		map[string]any{
			"foo": map[string]any{"a": "b"},
		},
		cel.AttributePattern("bar").QualString("baz").Wildcard())
	exitOnErr(err)

	ast, iss := env.Compile(`foo.exists(t, t == bar.baz.x)`)
	exitOnErr(iss.Err())

	prg, err := env.Program(ast, cel.EvalOptions(cel.OptTrackState, cel.OptPartialEval))
	exitOnErr(err)

	_, _, err = prg.Eval(pvars)
	exitOnErr(err)
}

func exitOnErr(err error) {
	if err != nil {
		log.Fatalf("Error: %v", err)
	}
}
```

**Expected behavior**
Before CEL 0.22.0, the above program runs successfully. With CEL 0.22.0, it fails with `no such attribute(s): bar`.

**Additional context**

If I patch CEL as follows, the above program works again. However, that patch causes several of the tests to fail and I am not sure why.

```patch
diff --git a/interpreter/interpretable.go b/interpreter/interpretable.go
index ebc432e..64ca714 100644
--- a/interpreter/interpretable.go
+++ b/interpreter/interpretable.go
@@ -1281,14 +1281,14 @@ func (f *folder) foldIterable(iterable traits.Iterable) ref.Val {
 	for it.HasNext() == types.True {
 		f.iterVar1Val = it.Next()
 
-		cond := f.cond.Eval(f)
+		cond := f.cond.Eval(f.Activation)
 		condBool, ok := cond.(types.Bool)
 		if f.interrupted || (!f.exhaustive && ok && condBool != types.True) {
 			return f.evalResult()
 		}
 
 		// Update the accumulation value and check for eval interuption.
-		f.accuVal = f.step.Eval(f)
+		f.accuVal = f.step.Eval(f.Activation)
 		f.initialized = true
 		if f.interruptable && checkInterrupt(f.Activation) {
 			f.interrupted = true
```

**Comment by TristonianJones** [comment]
Thanks @charithe I'll give this a look today / tomorrow. Sorry for the failure, but thank you for the report.
