### ISSUE TITLE
Two variable comprehensions potentially getting lost during pruning

### ISSUE THREAD

**Issue by charithe** [cel-expr/cel-go#1080]
**Describe the bug**

I am not quite sure whether this is a bug or not. I was reading the source to track down a different problem and came across this, which seems odd to me.

https://github.com/google/cel-go/blob/5d18e93d204801cbe02158a0ddb3a3abce29e4ed/interpreter/prune.go#L418-L433

Shouldn't it check `compre.IterVar2` and return a `p.NewComprehensionTwoVar(...)` if it's not empty?

Similarly, shouldn't there be a check for a two variable comprehension in the following bit as well?

https://github.com/google/cel-go/blob/5d18e93d204801cbe02158a0ddb3a3abce29e4ed/interpreter/prune.go#L284-L287

**Comment by TristonianJones** [comment]
Thank you, this is definitely a bug. I'll give it a look next week

**Comment by TristonianJones** [comment]
@charithe I've looked at this more closely and I'm not sure the prune was always correct for comprehensions. I'm concerned enough about it that I've decided to disable pruning within comprehensions unless the comprehension is the single-iteration cel.bind() call. Let me know fi that will cause any issues with your current solution.

**Comment by charithe** [comment]
Thank you! Seems good so far. I'll keep an eye on it.
