### ISSUE TITLE
How to filter values from a map in CEL expression in cel-go?

### ISSUE THREAD

**Issue by hmsayem** [cel-expr/cel-go#1085]
Hello,

I'm using `cel-go` for evaluating Kubernetes object status fields. One of the challenges I've encountered is filtering values from a map within a CEL expression.

For example, I have a Kubernetes object with a `components` field that is a map (i.e., `map[string]interface{}`). Each entry in the map contains a `phase` field, and I need to filter the entries where `phase == 'Succeeded'`.

Here is an example of the object structure:

```go
"status": map[string]interface{}{
	"components": map[string]interface{}{
		"pod-0": map[string]interface{}{
			"driver":    "Restic",
			"duration":  "10.595356615s",
			"integrity": true,
			"path":      "repository/v1/demo-session/dump-pod-0",
			"phase":     "Succeeded",
		},
		"pod-1": map[string]interface{}{
			"driver":    "Restic",
			"duration":  "8.789930136s",
			"integrity": true,
			"path":      "repository/v1/demo-session/dump-pod-1",
			"phase":     "Failed",
		},
	}
}
```

I've attempted to filter these values in a CEL expression like so:

```go
	env, err := cel.NewEnv(
		cel.Declarations(
			decls.NewVar("status", decls.NewMapType(decls.String, decls.Dyn)),
		),
	)
	expr := "status.components.filter(c, c.phase == 'Succeeded')"

	ast, issues := env.Compile(expr)
	if issues != nil && issues.Err() != nil {
		fmt.Println("Failed to compile expression:", issues.Err())
	}
```
However, this results in an error: `Failed to evaluate expression: no such key: phase`. I am wondering if there is an idiomatic way to handle this in `cel-go`. 

Thanks for your help!

**Comment by TristonianJones** [comment]
Hi @hmsayem,

The issue is that `c` is the map key rather than the value. If you'd like to support two-variable comprehensions, we just added support for this and you could approach this by using the `transformMap` macro:

```go
env, err := cel.NewEnv(
	cel.NewVariable("status", cel.MapType(cel.StringType, cel.DynType)),
	ext.TwoVarComprehensions(),
)
// For each component, emit a map of all values in the 'Succeeded' phase
// Output type is map[string]any where the key is the component name, 
// and the value is the component definition
return env.Compile(
    // returns map[string]any{ "pod-0": ... }
    `status.components.transformMap(name, c, c.phase == 'Succeeded', c)`
)
```

Alternatively, you can also use `transformList` if you want to emit a list of the component values and ignore the component key name in the output:

```
// returns value of pod-0
status.components.transformList(name, c, c.phase == 'Succeeded', c)
```

**Comment by hmsayem** [comment]
Hi @TristonianJones  ,  

Thank you for the clarification and the example using `transformMap` and `transformList` macros. I have a follow-up questions:  

Is it okay to always include the `TwoVarComprehensions()` extension even if I don’t necessarily need two-variable comprehensions for every expressions? My goal is to implement a general-purpose k8s. object status checker that should be capable of evaluating a wide variety of expressions. Could enabling `TwoVarComprehensions()` universally have any unintended issues or performance impacts?

Looking forward to your insights!
