### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by kyessenov** [cel-expr/cel-go#138]
Many go projects rely on semver to avoid breaking API changes (e.g by pinning to v0.1.x series, for example).
It would be good to publish a release to make life easier to projects consuming cel-go.

**Comment by TristonianJones** [comment]
Understood. There is an upcoming simplified interface coming soon and my intent is to create the first version tag once it's committed. Would this work for you?

**Comment by kyessenov** [comment]
Yes, there is no urgency. You get to pick the right time to stabilize the public interfaces.

**Comment by TristonianJones** [comment]
CEL Go v0.1.0 is now a thing. :)

**Comment by TristonianJones** [comment]
Temporarily deleted tag, pending pull #167

**Comment by TristonianJones** [comment]
Integrated.
