### ISSUE TITLE
feature: has() with index notation

### ISSUE THREAD

**Issue by kyessenov** [cel-expr/cel-go#139]
It seems that it's not possible to check key presence in a map if the key is not a valid identifier.
For example, headers often use dashes as separators. What would be the syntax for checking if `request.headers` map has a key `x-request-id`? 

The grammar suggests that `request.headers.x-request-id` is not a valid expression. However, `has(request.headers["x-request-id"])` is not parsable, since the inner expression gets translated to an INDEX function call.

**Comment by TristonianJones** [comment]
The `has` macro mostly exists for detecting whether a proto message field is set to a non-default value, but is supposed to work for maps with identifier-like keys as well. A better test for key presence in maps is `"key-name" in map_val`, but there are probably other functions that work better for different usability goals.

Could you give an example of what you'd like to do?

**Comment by kyessenov** [comment]
Thanks. I think that answers my question. I was mostly concerned about index operator producing errors, and the need to guard it with some key presence test. `in` operator seems to fit the need.
