### ISSUE TITLE
Reject dyn inputs to strongly typed functions at check time.

### ISSUE THREAD

**Issue by glerchundi** [cel-expr/cel-go#140]
We're evaluating this for our filter expressions and we found a weird behaviour which I don't know if its related to our environment or the lib itself. The issue comes when using the `in` operator and defining a list with different types. As far as i know, the parsed expression checking enforces this by default, or this is what i understood by reading this paragraph on the langdef spec:

> The type checker also introduces the dyn type, which is the union of all other types. Therefore the type checker could accept a list of heterogeneous values as dyn([1, 3.14, "foo"]), which is tiven the type list(dyn). The standard function dyn has no effect at runtime, but signals to the type checker that its argument should be considered of type dyn, list(dyn), or a dyn-valued map.

Take this as an example:

* Declare Parser
```go
// Parser is our expr parser
type Parser struct {
	env *checker.Env
}

// NewParser instantiates the Parser object
func NewParser(message proto.Message, allowedFields []string) (*Parser, error) {
	// attach protobuf & initialize env
	pkg := proto.MessageName(message)
	typeProvider := types.NewProvider(message)
	exprType := decls.NewObjectType(pkg)

	// create standard env
	env := checker.NewEnv(packages.NewPackage(pkg), typeProvider)
	if err := env.Add(standardDeclarations()...); err != nil {
		return nil, err
	}

	// add types tailored to our specific use-case.
	for _, filterable := range allowedFields {
		fieldType, ok := typeProvider.FindFieldType(exprType, filterable)
		if !ok {
			return nil, fmt.Errorf("expr: couldn't find field %s", filterable)
		}
		err := env.Add(decls.NewIdent(filterable, fieldType.Type, nil))
		if err != nil {
			return nil, err
		}
	}

	return &Parser{env: env}, nil
}

func standardDeclarations() []*exprpb.Decl {
	return []*exprpb.Decl{
		decls.NewFunction(operators.LogicalAnd,
			decls.NewOverload(overloads.LogicalAnd,
				[]*exprpb.Type{decls.Bool, decls.Bool}, decls.Bool)),
		decls.NewFunction(operators.LogicalOr,
			decls.NewOverload(overloads.LogicalOr,
				[]*exprpb.Type{decls.Bool, decls.Bool}, decls.Bool)),
		decls.NewFunction(operators.Equals,
			decls.NewOverload(overloads.Equals,
				[]*exprpb.Type{decls.String, decls.String}, decls.Bool)),
		decls.NewFunction(operators.In,
			decls.NewOverload(overloads.InList,
				[]*exprpb.Type{decls.String, decls.NewListType(decls.String)}, decls.Bool)),
	}
}
```
* Parse filter
```go
// Parse produces a database friendly expr from a cel string expr
func (e *Parser) Parse(filter string) (*Expr, error) {
	if filter == "" {
		return nil, nil
	}
	// parse expr
	src := common.NewTextSource(filter)
	expr, errs := parser.Parse(src)
	if len(errs.GetErrors()) != 0 {
		return nil, errors.New(errs.ToDisplayString())
	}

	// check expr against env
	checkedExpr, errs := checker.Check(expr, src, e.env)
	if len(errs.GetErrors()) != 0 {
		return nil, errors.New(errs.ToDisplayString())
	}

	return &Expr{expr: checkedExpr.Expr}, nil
}
```

I would expect the checker to fail but it returns the checked expression without complaining.

Can anyone point to the right direction if i'm missing something?

Thanks for this great library by the way.

**Comment by glerchundi** [comment]
Ups, i forgot to actually include the data for the example:

`user.proto`:
```
message User {
  string first_name = 1;
}
```

Test code:
```
[...]
	p, err := NewParser((*User)(nil), []string{"first_name"})
	if err != nil {
		t.Fatalf("%v", err)
	}
	e, err := p.Parse(`first_name in [1, 3.14, "foo"]`)
	if err != nil {
		t.Fatalf("%v", err)
	}
[...]
```

In our use case p.Parse should fail due to types-mixing but it doesn't.

**Comment by glerchundi** [comment]
If we mix different types in a list declaration it seems like `cel-go` converts this into a 'generic' `list(dyn)` type which is then assignable to the `ident` (`first_name` of type `string` in this case). So that the example above works although we expect not do to so.

But if we create a homogeneous list declaration which doesn't match to the ident type, it works as expected by failing the type checking. For example: `first_name in [1, 2, 3]`.

Is this an expected behaviour? Is it possible to override this behaviour to fail on the type checking?

Thanks!

**Comment by TristonianJones** [comment]
Excellent question. Thanks for waiting. Many of us were on vacation over the last two weeks. 

In short, `dyn` is obsolete. The checker behavior is correct and the spec needs to be updated. 
At one point in time, list and struct literals were homogeneously typed by default, but the empty literal
representations for each pointed out some issues with this strategy and helped us realize that CEL
is a dynamically typed language, so the list and map literals should be dynamically typed as well.

What you want should be possible via type assertion functions e.g. `first_name in vector([1, 2, 3])`
where `vector` only accepts `list(int)` and returns `list(int)` out. I'm not sure of your exact use case,
but maybe you elaborate further and we can figure out whether this is a general feature.

**Comment by glerchundi** [comment]
> Excellent question. Thanks for waiting. Many of us were on vacation over the last two weeks.

Don't worry at all!

> In short, `dyn` is obsolete. The checker behavior is correct and the spec needs to be updated.

Ack.

> At one point in time, list and struct literals were homogeneously typed by default, but the empty literal
> representations for each pointed out some issues with this strategy and helped us realize that CEL
> is a dynamically typed language, so the list and map literals should be dynamically typed as well.

Understood but perhaps i'm missing something. What's the point of declaring explicitly the nested type of the list that we were going to use then?

```
[...]
decls.NewFunction(operators.In,
    decls.NewOverload(overloads.InList,
        []*exprpb.Type{decls.String, decls.NewListType(decls.String)}, decls.Bool)),
[...]
```

If i were to use the dynamic typing system I would use the `decls.NewTypeParamType("A")` as you were using it [in the standard environment](https://github.com/google/cel-go/blob/b66995e29682fc4373ca46cd1596b1e94a3e3896/checker/standard.go#L30).

> What you want should be possible via type assertion functions e.g. `first_name in vector([1, 2, 3])`
> where `vector` only accepts `list(int)` and returns `list(int)` out. I'm not sure of your exact use case,
> but maybe you elaborate further and we can figure out whether this is a general feature.

So we're trying to use `cel-spec` (and specifically `cel-go` implementation) for our user-facing filter expression the same way [Google proposes in its API guidelines](https://cloud.google.com/apis/design/naming_convention#list_filter_field). Following the example above this would look like this:

```protobuf
service UserService {
    rpc ListUsers(ListUsersRequest) returns ListUsersResponse {};
}

message User {
    string first_name = 1;
    string last_name = 2;
}

message ListUsersRequest {
    string filter = 1;
}

message ListUsersResponse {
    repeated User users = 1;
    string next_page_token = 2;
}
```

Currently, with your `cel-go` implementation, we were able to successfully achieve lots of filters like these which is absolutely fantastic with 'minimal' effort from our side:

```
first_name == 'A'
last_name == 'A'
first_name == 'A' && last_name == 'B'
first_name == 'A' || last_name == 'B'
first_name == 'A' && last_name == 'B' || last_name == 'C'
first_name == 'A' && (last_name == 'B' || last_name == 'C')
first_name == 'A' || (last_name == 'B' || last_name == 'C')
first_name.startsWith('A')
first_name.endsWith('A')
first_name.contains('A')
first_name in ['A']
```

As you can imagine, we want to create the 'best' (as possible) user-experience for the developer which in this concrete case means that we don't want to force putting things that means nothing to them but is useful for our type-checking system (like it would be the `vector` thing). 

Another reason why we have chosen this library is because in our API side vision we elucidate that it would be useful for our policy system, à la [OPA](https://www.openpolicyagent.org/) or [Google IAM conditions](https://cloud.google.com/iam/docs/conditions-overview).

My question then is, is this something that you'll consider adding to the `cel-go` something that prevents this dynamic type inference and strictly type checks the nested type? Ruled by a configuration parameter for example.

Thanks for your time!

**Comment by TristonianJones** [comment]
Fascinating use case. Thanks for sharing. I have a few more bits of information you may find useful with respect to list filters, but I'll save it for the end.

I just now realized that you aren't using the standard environment. My apologies, I misread the code in the first pass. Indeed, the custom `in` overload should do as you expect since it should be equivalent to the `vector` example I gave. From my initial debug pass, I can see why the code is allowing the check to pass and need to dig a bit further before I'll be able to come up with a solution.

I'm familiar with list filters and there are some subtle differences from CEL; however, if you are interested, before `cel-go` was created, I published a list filtering grammar which adapts to the `cel-spec` AST for the [grafeas.io](http://grafeas.io) project. It's not pretty code (my first Go) but you may find my [list filtering pull request](https://github.com/grafeas/grafeas/pull/105) informative.

**Comment by glerchundi** [comment]
> Fascinating use case. Thanks for sharing. I have a few more bits of information you may find useful with respect to list filters, but I'll save it for the end.

Cool.

> I just now realized that you aren't using the standard environment. My apologies, I misread the code in the first pass. Indeed, the custom `in` overload should do as you expect since it should be equivalent to the `vector` example I gave. From my initial debug pass, I can see why the code is allowing the check to pass and need to dig a bit further before I'll be able to come up with a solution.

Perfect, thanks. No hurries at all but in order to make it on our plan or not what timescale you have in mind?

> I'm familiar with list filters and there are some subtle differences from CEL; however, if you are interested, before `cel-go` was created, I published a list filtering grammar which adapts to the `cel-spec` AST for the [grafeas.io](http://grafeas.io) project. It's not pretty code (my first Go) but you may find my [list filtering pull request](https://github.com/grafeas/grafeas/pull/105) informative.

Really interesting! Thanks for sharing. Regarding to the point of "subtle differences" and knowing that you're familiar with the list filter expression/format, can you tell me which are those? I don't know if it's something that I should be worried about...

I'm not a grammar expert at all (although i've written some) but I wanted to avoid the design and the writing of a custom grammar for a filter due to my experience and the quantity of details that must be taken care of. So that being said, and after looking around for a while I found this fantastic repository that makes the parsing and type-checking jobs perfectly, which is what I was looking for.

Thanks again for your time.

**Comment by TristonianJones** [comment]
> Perfect, thanks. No hurries at all but in order to make it on our plan or not what timescale you have in mind?

I don't have an ETA at present, but it's on the backlog. I have one other PR in progress, but after that this would be my next priority. We try to prioritize bugs over features.

> Regarding to the point of "subtle differences" and knowing that you're familiar with the list filter expression/format, can you tell me which are those? I don't know if it's something that I should be worried about...

List filters support three syntactic elements that CEL does not: sequence, global, and the colon operator for attribute presence testing. Additionally, list filters treat barewords as either strings or identifiers. List filters are meant for human-based searches and fuzzy logic. 

Take for example the filter:  `New York`. This filter should score documents with both `New` and `York` higher than documents with just one or the other. At the AST level as `sequence(global('New'), global('York'))`, though you might instead want to introduce a function that just handles this fuzzy matching case within CEL: `query('New York') && ...`

**Comment by glerchundi** [comment]
Thank you very much @TristonianJones for the tips and diffs between
googlish filters and CEL itself. We’ll wait for the fix then.

Bye 👋!

**Comment by TristonianJones** [comment]
I've looked over the issue, and part of the problem is that `dyn` is used to signify two things:

1. Unknown type to be determined at runtime
1. Mixed type, possibly known statically

The introduction of a union type to handle this second case would fix the issue, but introduce
a lot of complexity (i.e. will take a while to implement). 

The alternative, which only partly solves your problem, would be to add a check mode that ensures
list and map literals are constructed with homogeneous element types. This solves the following
issue:

```
// results in a check-error
first_name in [1, 2u, 'my-name'] 
```

However, it doesn't solve this one

```
// if 'names' is a JSON list value it will be treated as list(dyn)
first_name in input.names
```

The flag-based approach would ensure that you could construct an environment which only uses homogeneous types if so desired, but does not guarantee that `dyn` won't appear.  Does this sound amenable to you? If so, I'm going to close this as an issue and open a feature request with the desired behavior, since the code is don't basically what it is supposed to be doing which is trying to match the closes possible function and leaving the runtime to enforce strictness when there is ambiguity at check-time.

**Comment by glerchundi** [comment]
This would work for us @TristonianJones as we're protecting from the second case by doing an extra-check round. So yes, definitely a flag that controls if the behaviours is a) take the closest or b) be strict would make our lives a little bit easier ;)
