### ISSUE TITLE
Support for zero-arity extern

### ISSUE THREAD

**Issue by kyessenov** [cel-expr/cel-go#141]
In my experiments, I found that adding a zero-arity extern causes a panic in the interpreter at this line:
https://github.com/google/cel-go/blob/master/interpreter/dispatcher.go#L96

The spec is not definitive about support for zero-arity externs. Is this something that CEL supports and the implementation has a defect, or CEL expects at least one argument for every function?

**Comment by TristonianJones** [comment]
There haven't been any zero-arity functions as built-ins within CEL, mostly because CEL is side effect free, so functions should say something about a value in the activation. To preserve this behavior and probably give you what you want we could introduce lazy values in the activation. Could you tell me more about your use case?

**Comment by kyessenov** [comment]
It's mostly a syntactic issue. There is a function called `emptyStringMap()` that I tried to add as an extern. You are right, that the zero-arity function ought to be a constant or a lazily-activated value. The reason for the function existence are not fundamental. But in case some other user tries to add a custom zero-arity extern, it might be worth documenting this somewhere.

**Comment by TristonianJones** [comment]
The spec doesn't prohibit zero-arity functions, so what you observed is an error in the implementation. That said, this is an area that probably deserves discussion in the spec. I'll talk to @JimLarson about it tomorrow. Thanks for the feedback!

**Comment by JimLarson** [comment]
Though the spec doesn't mention zero-arity functions explicitly, zero-argument calls are clearly valid grammar productions.  We've decided to add an explicit note that they are legal, but to suggest lazy values as a preferred method, as they make the value-nature more explicit.  Someone might be tempted to add something like rand() to generate random integers - a subtle form of side-effect.  A CEL implementation is free to consolidate common subexpressions and only make one call to rand() even in an expression that contains many of them.  However, if we forbid zero-arity functions, someone could just add dummy arguments to get around the restriction, so we're going to avoid forbidding that which we cannot disallow, and we'll just add a note to beware.

**Comment by TristonianJones** [comment]
Jim, can you file an issue to track this on `google/cel-spec`, and then close out this issue with a reference to the cel-spec one?

**Comment by TristonianJones** [comment]
The dispatch code was updated in pull #145 to support zero-arity functions properly.
