### ISSUE TITLE
Data Race error when running tests in parallel

### ISSUE THREAD

**Issue by inigohu** [cel-expr/cel-go#175]
**Describe the bug**
We are using **cel-go** in our project and when we try to run our tests in parallel, we get a `DATA RACE` error. 

I have reproduced the same behavior with your tests, running parser tests in parallel, and I get this error: `WARNING: DATA RACE`     `race detected during execution of test`

**To Reproduce**
Check which components this affects:

- [X]  parser
- [ ]  checker
- [ ]  interpreter

Sample expression and input that reproduces the issue:
```
go test -v parser/parser.go parser/macro.go parser/errors.go parser/helper.go parser/unescape.go parser/parser_test.go -race
```

Test setup:
```go
// test case in go
func TestParse(t *testing.T) {
  for i, tst := range testCases {
    name := fmt.Sprintf("%d %s", i, tst.I)
      t.Run(name, func(tt *testing.T) {
        tt.Parallel()
        ...
```

```
WARNING: DATA RACE
Read at 0x00c000110f00 by goroutine 28:
...
--- FAIL: TestParse (0.03s)
    --- FAIL: TestParse/0_"A" (0.04s)
        testing.go:809: race detected during execution of test
    --- FAIL: TestParse/31_a_>=_b (0.02s)
        testing.go:809: race detected during execution of test
...
```
**Expected behavior**
Should pass all tests

**Additional context**
run tests with `-race`flag to check Data Race

**Comment by TristonianJones** [comment]
I've looked briefly at the error and it looks as though the race comes from the Antlr4 Go runtime library. I'll see if updating the build.bazel WORKSPACE reference to the library addresses the issue.

**Comment by TristonianJones** [comment]
Updating the workspace had no effect. I'll check through the library to see if I can find the source of the issue.

**Comment by TristonianJones** [comment]
It appears this is an issue with the Antlr Go codegen template. I can address the issue manually for now and will add a hefty set of comments about what the change is within the generated source. I'll also see if I can get the Antlr codegen template changed via PR, but I'm not sure what the overhead of the change is or if an alternative would be preferred. This latter step may take a bit more time.

In terms of downstream gotchas, the protobuf libraries also mutate global state, so depending on your use case you may notice data races during type-check and interpretation. The expectation is that you're typically initializing the runtime type-system once per-process. 

Could you tell me a bit more about your use case so I can better understand the desired execution model @inigohu?

**Comment by inigohu** [comment]
> Could you tell me a bit more about your use case so I can better understand the desired execution model @inigohu?

I have a gRPC API server that implements an expression language parser object. That parser is using the **cel-go** library to make type-check filters of the gRPC requests. To test the server's endpoints, I instantiate N _mock_ servers, that means, N parsers executing in parallel. And that is where I get the **data race** error, when it tries to parser concurrently.

**Comment by inigohu** [comment]
I've found another similar error creating providers concurrently. Maybe this is not strictly an error because is not necessary to create multiple providers concurrently.

In this case the error comes from [indexTypes function](https://github.com/google/cel-go/blob/master/common/types/pb/file.go#L103)

```bash
--- FAIL: Test_1 (0.00s)
    testing.go:809: race detected during execution of test
==================
WARNING: DATA RACE
Write at 0x00c000132330 by goroutine 6:
  runtime.mapassign_faststr()
      /usr/local/Cellar/go/1.12/libexec/src/runtime/map_faststr.go:202 +0x0
  github.com/google/cel-go/common/types/pb.(*FileDescription).indexTypes()
  ...
  
```

The *providers_test.go* tests, don't reproduce the error because all the tests must run in parallel. I don't understand why, but if just one of the tests runs in serie, the other tests pass.
I've prepare this small test to reproduce the error. 

```go
package types

import (
	"testing"

	exprpb "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
)

func Test_1(t *testing.T) {
	t.Parallel()
	_ = NewProvider(&exprpb.ParsedExpr{})
}
func Test_2(t *testing.T) {
	t.Parallel()
	_ = NewProvider(&exprpb.ParsedExpr{})
}
```

<u>Note</u>: run tests with `-race`flag

The problem comes from map variables, in this case from `revFileDescriptorMap`, but the `TypeDescription.fields` and `TypeDescription.fieldIndices` have the same problem. There are two ways to solve this:

1. Lock/Unlock when using maps
*file.go*
```go
func (fd *FileDescription) indexTypes(pkg string, msgTypes []*descpb.DescriptorProto) {
	...
	var lock = sync.RWMutex{}
	lock.RLock()
	defer lock.RUnlock()
	fd.pbdb.revFileDescriptorMap[msgName] = fd
}
```
2. Use asyc.Map instead of normal map
*pb.go*
```go
type Db struct {
	revFileDescriptorMap sync.Map
}
DefaultDb = &Db{
	revFileDescriptorMap: sync.Map{},
}
```
*file.go*

```go
func (fd *FileDescription) indexTypes(pkg string, msgTypes []*descpb.DescriptorProto) {
	...
	fd.pbdb.revFileDescriptorMap.Store(msgName,fd)
}
```

<u>Note</u>: If you think that this should be in a different issue I can move it

**Comment by TristonianJones** [comment]
Thank you for the detailed report. I'll move this to a separate bug. To avoid races at check-time you'll need to use the `IsolateTypes()` option with the `TypeDesc()` option that was added just yesterday.

The type isolation for runtime types is an area for improvement. The typical use case is one `ref.Provider` per process which is why I was curious how you were using the libraries. The operations within the `pb.Db` are idempotent in the sense that any call with the same arguments will result in the same response. So the race points out a wart in this case, but it shouldn't impact library behavior. The ANTLR parser on the other hand had mutable global state that was wasn't clearly idempotent. 

I was planning on working on runtime type isolation today, so the added context here is great.

**Comment by TristonianJones** [comment]
I've made some good progress here. Should have a PR out tomorrow
