### ISSUE TITLE
Reference to undefined variable should be error instead of unknown

### ISSUE THREAD

**Issue by JimLarson** [cel-expr/cel-go#190]
**Describe the bug**
The interpreter currently returns an "unknown" value for undefined variables.  It ought to return an error.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [X]  interpreter

Sample expression and input that reproduces the issue:
```cel
// sample expression string
x
```

Test setup:
```go
// test case in go
Evaluate the expression `x` without binding `x`.
```

**Expected behavior**
It should return an error for an undefined variable.

**Additional context**
To evaluate for `x` being unknown (vs undefined), it can be bound to an unknown value.

**Comment by TristonianJones** [comment]
Closing #154 as a duplicate

**Comment by TristonianJones** [comment]
Just as a quick update to this bug. I'm working through a possible design, but it's reasonably complex and so I'm going to punt this task to CEL v0.4.0 milestone until I can work through the details.

**Comment by TristonianJones** [comment]
Moved out the 0.3.0 release since I think there will be some breaking interface changes needed to support unknowns that should probably go out sooner rather than later.
