### ISSUE TITLE
Use struct tags to parse function arguments

### ISSUE THREAD

**Issue by tobiaszheller** [cel-expr/cel-go#204]
**Change**

Use struct tags to parse arguments in function definition.

Struct tag should define position of variable in arguments passed to function.

**Example**
```
func funcA(argsVal ...ref.Val) ref.Val {
	var args struct {
		A bool    `position:"0"`
		B float64 `position:"1"`
		C int     `position:"2"`
	}
	err := parseArgs(&args, argsVal...)
}
```
What do you think about that? I am willing to implement that.

**Comment by TristonianJones** [comment]
Hi Tobiaz,

Could you give me a bit more context on the problem this is trying to solve? For example, does this improve guarantees of correctness? Or unify the declaration + definition steps? 

My preference is to avoid two ways of doing the same thing, but I certainly understand there are areas of improvement in the following areas:
1. Working with protos.
2. Separation of declaration from definition, e.g. function signature separate from function impl.
3. Weak guarantees of type-safety in the runtime function definitions.

Thanks,

-Tristan

**Comment by tobiaszheller** [comment]
@TristonianJones 
I think that it will remove a lot of boilerplate code when adding overload functions.
Let's take a look of function with multiple arguments [cel_test.go](https://github.com/google/cel-go/blob/6a046a90da28fd89ea6f11b5834b84d5143ca6db/cel/cel_test.go#L341-L361).
You need to check len of arguments first, then cast every argument to check if it has proper type.
The idea about that feature is to close that boilerplate stuff behind function which will do the magic. It return error if something goes wrong or update variable.

This should be optional but can be helpful if you define a lot of functions overloads.

**Comment by TristonianJones** [comment]
I like the idea of making the overload declaration simpler in the common case. The tradeoff here is between ease of use (tags) and performance (hand-roll). Also, the `planner.go` relies pretty heavily on the specific structure of the existing overloads to optimize the execution plan. 

I think in the ideal case, you would use a feature like this to communicate everything the type-checker might want that it currently gets out of `cel.Declarations` and everything that the runtime might want to enforce the declaration contract in `cel.Functions`. 

I guess I imagine something along the following lines:

```go
func andFunc() cel.Binding {
   // a.and(b) returns true if b is `a` is `true` and `b` is a truthy double. 
   var argsTypes struct {
        a types.Bool      `in: "0", target: "true"`
        b types.Double  `in: "1"`
        c types.Bool      `out: "true"`
    }
    // Create a new CEL binding for 'and' where a Binding contains both a declaration and definition.
    // - automatically generate an overload_id based on the argTypes
    // - wrap the invocation of the impl in a type-checking function based on argTypes
    return cel.Binding({
        name: "and",
        args: argTypes,
        impl: func(a ref.Val, b ref.Val) ref.Val {
           return a == types.True && b != types.Double(0.0)
        }
    )
}
```

**Comment by tobiaszheller** [comment]
> Create a new CEL binding for 'and' where a Binding contains both a declaration and definition.

I really like how it is working right now, that declaration is separated from implementation. If I understand you correctly, introducing `cel.Binding` will couple it together?

 I don't understand also how that simplify implementation? You are still operating on cel Types. My idea was to simplify process of converting arguments in implementation and it is lost in your proposal. Or am I missing something?

**Comment by TristonianJones** [comment]
>My idea was to simplify process of converting arguments in implementation

Since the `interpreter.Activation` handles the conversion from Go to CEL types on access, type-conversion should be handled already. I believe the `planner.go` also checks that the number of arguments provided to a function is also the same as the number declared, but if not then I would consider this a bug.

Given these two features, the one bit of boilerplate remaining would be runtime type checking of the input arguments. This is somewhat intentional, but I could see how it would be annoying (and not the common case to fall-through). I think the planner can be updated to do runtime type-checking of the args based on the function declaration, but this wouldn't require any more information than is already present in the current top-level interfaces.

**Comment by tobiaszheller** [comment]
I have done some verification and it works as you describe, check for length or arguments is not necessary. Also type check in runtime can be simplified due to type check during parsing.

I would like to simplify then test case in cel_test.go or create examples how to use/define custom function because that test case is misleading for me. What do you suggest? simplify test case or add examples?

**Comment by TristonianJones** [comment]
I'm always happy to have more examples if you'd like to contribute them. The ones that are in there now are probably complete, but not concise. The more the merrier. :)
