### ISSUE TITLE
Support for creating an Env instance using a protobuf schema.

### ISSUE THREAD

**Issue by KristaHyer1** [cel-expr/cel-go#206]
**Change**
When creating an Env instance, the user currently has to define the constants that will be checked.
* Example - https://github.com/google/cel-go#environment-setup
* Code - https://github.com/google/cel-go/blob/master/cel/env.go#L106-L111

This request is for an enhancement that would allow a protobuf schema to be passed in, instead of a list of constants.

This would be less prone to errors such as typos. Also, it would allow the following case to work (which is the motivation behind this request):
* we have a service that can accept requests of unknown forms
* these requests DO all have fields which contain their service and method, allowing their form to be looked up (in the form of a compiled protobuf schema)
* so we'd like to create an Env that takes a protobuf schema, so that we can compile the code without knowing all the constants that will be checked

We'd be happy to create this PR for you to check.

**Example**
```
import (
	pb "github.com/google/cel-go/test/proto2pb/test_all_types.pb.go"
)

e := &env{
	schema:      pb,
}
```

**Comment by TristonianJones** [comment]
Thanks for the feature request! The `cel.Env` is composed of a few elements, but the variable identifiers are a certainly a big component. If you are interested in making a functional `cel.EnvOption` which takes a proto message and produces a declaration list from the field names as output that sounds very useful. 

Please let me know if the following pseudo-code in line with your thinking:

```go
import (
  pb "github.com/google/cel-go/test/proto2pb/test_all_types.pb.go"
)
// ... other code ...
  e, err := cel.NewEnv(
     // Use proto message fields as variable declarations
     cel.VariablesFromMessageFields(&pb.TestAllTypes{}),
     // Add custom function declarations
     cel.Declarations(
        decls.NewFunction(...),
     ))
```

To walk the fields of the message, I would recommend using the `common/types/pb` utilities. Something along the following lines.

```go
import(
  "github.com/google/cel-go/checker/decls"
  "github.com/google/cel-go/common/types/pb"

  exprpb "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
)

func VariablesFromMessageFields(msg proto.Message) []*exprpb.Decl {
  // Create a new pb db and register the type before describing it.
  pbdb := pb.NewDb()
  pbdb.RegisterMessage(msg)
  td, err := pbdb.DescribeType(msg)
  
  // Build the list of decls.
  var vars []*exprpb.Decl
  // The TypeDescriptor.Fields() function would need to be implemented.
  for _, f := range td.Fields() {
     name := f.OrigName()      // protobuf style name using underscores.
     type := f.CheckedType()  // checked-type used for declarations.
     vars = append(vars, decls.NewIdent(name, type, nil)
  }
  return vars
}
```

Happy coding!

**Comment by TristonianJones** [comment]
@KristaHyer1 let me know if you need any help getting started. Happy discuss on the cel-go-discuss board if you would like as well.

**Comment by KristaHyer1** [comment]
Thanks for your quick response!

The pseudo-code you put above does match my thinking, and I have enough info to get started.

I'm just starting this now, and I'll probably find questions as I go along. Is the cel-go-discuss board the right place to ask these? If so, can you point me towards it, since I haven't been able to find it.

**Comment by TristonianJones** [comment]
Hi Krista, don't hesitate to ask questions to confirm your understanding of how things work on https://groups.google.com/forum/#!forum/cel-go-discuss

Once you have a review out, we'll move the discussion to the PR.

Cheers!

**Comment by KristaHyer1** [comment]
I'm not able to finish this right now - @david-lshift here is the link so we don't lose it.
And here is the PR I've started with the changes in it - https://github.com/google/cel-go/pull/219.

**Comment by TristonianJones** [comment]
I'm going to close this issue for now. If you'd like to reopen it, please feel free.
