### ISSUE TITLE
Panic during runtime when object in vars is nil

### ISSUE THREAD

**Issue by tobiaszheller** [cel-expr/cel-go#209]
**Describe the bug**
`prg.Eval()` panics if referencing proto object (in expression) which is declared as nil pointer (of some type) in vars map.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

Sample expression and input that reproduces the issue:
```cel
test.name
```

Test setup:
Proto loaded from https://github.com/grpc/grpc-go/tree/master/examples/helloworld/helloworld
```go
func Test_CustomTypes(t *testing.T) {
    env, err := cel.NewEnv(
        cel.Types(&helloworld.HelloRequest{}),
        cel.Declarations(
            decls.NewIdent("test",
                decls.NewObjectType("helloworld.HelloRequest"), nil)))
    if err != nil {
        t.Fatalf("environment creation error: %s\n", err)
    }
    p, iss := env.Parse(`test.name`)
    if iss != nil && iss.Err() != nil {
        t.Fatal("Check failed: ", iss)
    }
    c, iss := env.Check(p)
    if iss != nil && iss.Err() != nil {
        t.Fatal("Check failed: ", iss)
    }
    prg, _ := env.Program(c)

    var req *helloworld.HelloRequest
    // req = &helloworld.HelloRequest{}
    vars3 := map[string]interface{}{"test": req}

    out, _, _ := prg.Eval(vars3)
}
```

**Expected behavior**
Runtime error.

**Comment by TristonianJones** [comment]
In general, CEL tries not to `panic`. My guess here is that the defined-but-nil case should be treated as idiomatically equivalent to the concrete `null` by the default type adapter. Thanks for the report!
