### ISSUE TITLE
Eval panic recovery

### ISSUE THREAD

**Issue by tobiaszheller** [cel-expr/cel-go#210]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [ ] The change is large enough it can't be addressed with a simple Pull Request
- [ ] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**
Top level panic recovery for `program.Eval` method. 

Based on recent bugs #208 #209, `Eval` method is not so safe and could cause panic. I would expect from expressions interpreter to have top level recovery function and handle panics.

**Comment by TristonianJones** [comment]
That's a very reasonable request. I'll add it to the todo list. :+1:
