### ISSUE TITLE
cel.Types should add imported nested messages types from proto message

### ISSUE THREAD

**Issue by tobiaszheller** [cel-expr/cel-go#211]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [ ] The change is large enough it can't be addressed with a simple Pull Request
- [ ] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**
When you import top level proto message with nested one you can reference nested fields within expression. However if nested message is imported from other package it is no longer possible. 

`cel.Types` should add also imported nested messages to environment. 

**Example**
```go
func Test_CustomTypes(t *testing.T) {
	e, _ := NewEnv(
		Types(&proto3pb.TestAllTypes{}),
		Declarations(
			decls.NewIdent("pb3",
				decls.NewObjectType("google.expr.proto3.test.TestAllTypes"), nil)))
	p, iss := e.Parse(`pb3.single_timestamp.seconds`)
	if iss != nil && iss.Err() != nil {
		t.Fatal(iss.Err())
	}
	_, iss = e.Check(p)
	if iss != nil && iss.Err() != nil {
		t.Fatal(iss.Err())
	}
}
```
```
ERROR: <input>:1:21: type 'well_known:TIMESTAMP ' does not support field selection
         | pb3.single_timestamp.seconds
         | ....................^
```

**Comment by TristonianJones** [comment]
Actually this is specific behavior for well-known types. The `google.protobuf.Duration` and `google.protobuf.Timestamp` types are considered well-known and opaque. Opaque types do not expose their properties directly to CEL, but for durations and timestamps there are many helper methods available to get this state.

**Comment by tobiaszheller** [comment]
what about user defined types which are imported in proto?

**Comment by TristonianJones** [comment]
Those should support field accesses with the exception of the well-defined types. Note, protobuf wrapper types are currently not implemented, but will be soon
