### ISSUE TITLE
Improper conversion of byte literals to byte sequences

### ISSUE THREAD

**Issue by phith0n** [cel-expr/cel-go#227]
**Describe the bug**

When the expression returns a bytes array which contains no UTF-8 character, the result is unexpected.

**To Reproduce**

Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

Sample expression and input that reproduces the issue:

```cel
b'\x8B'
```

Test setup:

```go
package main

import (
	"github.com/google/cel-go/cel"
	"fmt"
)

func main() {
	env, _ := cel.NewEnv()
	parsed, _ := env.Parse(`b'\x8B'`)
	checked, _ := env.Check(parsed)
	prg, _ := env.Program(checked)
	out, _, _ := prg.Eval(map[string]interface{}{})
	fmt.Println(out)
}
```

**Expected behavior**

Output a byte array, which length is 1, the only character is [139].

**Actual behavior**

Output a byte array, which length is 2, value is [194, 139]

**Comment by TristonianJones** [comment]
Thanks for the report. This is indeed an inconsistency with the spec.

**Comment by TristonianJones** [comment]
@JimLarson would you be able to give this a look while I'm OOO next week? It's an issue with the `unescape.go` converting to `rune` type straight-away and not considering whether the byte sequence coming in is for a byte literal. There's actually a TODO that questions whether the right encoding is being performed.

**Comment by JimLarson** [comment]
Should work now.
