### ISSUE TITLE
Checker `list.filter` bug w/ protobuf struct list

### ISSUE THREAD

**Issue by jarreds** [cel-expr/cel-go#232]
**Describe the bug**
Seems to be a checker bug with a `filter` expression operating on a list in `pb.Struct`. The error message also seems strange because the expected type is exactly the same as the found type?

```
ERROR: <input>:1:17: expected type 'list(type_param:"_var0" )' but found 'list(type_param:"_var0" )'
 | test.list.filter(x, x > 1.5)
 | ................^
```

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [x]  checker
- [ ]  interpreter

Sample expression and input that reproduces the issue:
```cel
test.list.filter(x, x > 1.5)
```

Test setup:
```go
package main

import (
  "bytes"
  "encoding/json"
  "fmt"
  "testing"

  "github.com/golang/protobuf/jsonpb"
  pstruct "github.com/golang/protobuf/ptypes/struct"
  "github.com/google/cel-go/cel"
  "github.com/google/cel-go/checker/decls"
)

func TestRepro(t *testing.T) {
  j, err := json.Marshal(map[string]interface{}{
    "list": []interface{}{1, 2, 3},
  })
  if err != nil {
    panic(err)
  }

  s := pstruct.Struct{}
  if err := jsonpb.Unmarshal(bytes.NewReader(j), &s); err != nil {
    panic(err)
  }

  env, err := cel.NewEnv(
    cel.Declarations(
      decls.NewIdent("test", decls.NewObjectType("google.protobuf.Struct"), nil)))
  if err != nil {
    panic(err)
  }

  p, iss := env.Parse("test.list.filter(x, x > 1.5)")
  if iss != nil && iss.Err() != nil {
    panic(err)
  }

  _, iss = env.Check(p)
  if iss != nil && iss.Err() != nil {
    fmt.Println(iss.Err())
  }
}
```

**Expected behavior**
I expect this expression to type-check or provide a non-contradictory error message. I assume the former because the expression runs and generates the expected results w/o the checker.

**Comment by TristonianJones** [comment]
Thanks for the report. There is some special casing around the protobuf JSON types which must be getting applied just slightly too late. In theory the `list` value should have been flagged as type `Dyn` and passed the check.

We'll take a look. Does this also happen when the type of `test.list` is a parameterized list and not a JSON-like value?

**Comment by jarreds** [comment]
Thanks!

**Comment by TristonianJones** [comment]
No problem. Thanks for the report. It helped us track down two different bugs that have been there since the inception of the project.
