### ISSUE TITLE
Backslash handling

### ISSUE THREAD

**Issue by lopezator** [cel-expr/cel-go#243]
**Describe the bug**

Escaped backslashes get stripped on resulting ast.

`actualWithKind` gets printed in the `parser_test.go` as:

```
 "hello\\world"^#1:*expr.Constant_StringValue#
```

However, as we are parsing the resulting ast to generate SQL sentences from it (we use cel-go as a app/db filtering component), and we found that:

`expression.Expr.ExprKind.ConstExpr.ConstantKind.StringValue`

Contains:

`"hello\world"` (unscaped).

**To Reproduce**

Check which components this affects:

- [x]  parser
- [ ]  checker
- [ ]  interpreter

Sample expression and input that reproduces the issue:

```cel
"hello\\world"
```
Test setup:
```go
	{
		I: `"hello\\world"`,
		E: "",
	}
```

**Expected behavior**

`expression.Expr.ExprKind.ConstExpr.ConstantKind.StringValue` to be escaped:

`"hello\\world"`

**Additional context**

Not sure if this is intended or not, if it is, do you have any idea on how can we accomplish this? 

We need escaped values to pass them to the SQL engine and be able to return results.

As passing:

```go
	{
		I: `"hello\world"`,
		E: "",
	}
```

Fails with:

```go
        parser_test.go:997: Unexpected errors: ERROR: <input>:1:1: Syntax error: token recognition error at: '"hello\w'
             | "hello\world"
             | ^
            ERROR: <input>:1:13: Syntax error: token recognition error at: '"'
             | "hello\world"
             | ............^
```

I assume this is the correct way to pass a backslash containing filter to the parser.

**Comment by TristonianJones** [comment]
You might need to try to `strconv.quote` the strings before embedding them in SQL. Let me know if that works for you. 

The AST representation should contain the escaped string, but if you want to consume the string in another context the Go quoting utilities should do the trick

**Comment by lopezator** [comment]
I made an small test for expr args like:

```
strings.Trim(strconv.Quote(arg.(string)), "\"")
```

And seems to work!

Thanks @TristonianJones feel free to suggest a better way if you know it, but anyway, you I close this as the solution is in our end.

**Comment by TristonianJones** [comment]
Great, I'm glad that the recommendation worked! Moving strings across languages can be a bit tricky.

**Comment by lopezator** [comment]
Yep.

The final "problem" was on how databases handle backslashes on LIKE statements.

At the end, we translate ASTs to db, being:

startsWith -> LIKE 'text%'
endsWith -> LIKE '%text'
contains -> LIKE '%text%'

As backslashes are being escaped in LIKE stmts we ended up simply doubling backslashes after AST walk and just before SQL generation on thoses cases.

Thanks for the hard work here, CEL's great! :+1:
