### ISSUE TITLE
How to inject custom behaviour into parsing logic (return custom types after parsing not evaluation)?

### ISSUE THREAD

**Issue by pmalekn** [cel-expr/cel-go#279]
I'm working on an internal Go package that would translate user (other services') expressions into Elasticsearch queries.

My goal is to declare parsing logic which would let's say allow something like:

```
label.id == "my-id1" && label.value == 100
```

or

```
( label.id == "id1" && label.value == 100 ) || ( label.id == "id2" && label.value == 900 )
```

So the parsing logic has to be aware that it looks for (in the second example):
* a label with id `id1` *and* `value` of `100`
or
* a label with id `id2` *and* `value` of `900`

What I'm looking for is to generate a query that would do the filtering etc. on the DB side (Elasticsearch) instead of getting all the relevant results (for instance from a particular time range) and then evaluating the filter on those results.
I believe that aligns with usage of cel in other projects like those mentioned on [1]

> Google uses CEL as the expression component of IAM and Firebase security policies, as well as within Istio Mixer configs.
> 
> Cloud IAM Conditions
> Firebase Rules
> Istio Mixer

Can I achieve this with cel? If so then can I do that?

[1] https://opensource.google/projects/cel

**Comment by TristonianJones** [comment]
Here's a pointer to the current conversation thread on the cel-go-discuss@googlegroups.com:
https://groups.google.com/d/msg/cel-go-discuss/7ed2b_nqNkw/aqsU1TuMAwAJ

I'm going to close this issue here and hopefully we'll figure out how to meet your needs in the group thread.

Cheers,

-Tristan
