### ISSUE TITLE
a bug when unparse bytes data with double quote

### ISSUE THREAD

**Issue by virusdefender** [cel-expr/cel-go#281]
**Describe the bug**
a bytes data like `b'aaa"bbb'`, parse it and then unparse it, the quote will be wrong

**To Reproduce**
add `b'aaa"bbb'` to test case `TestUnparse_Identical`, and it will output 

```
=== RUN   TestUnparse_Identical/lit_bytes_with_quote
    --- FAIL: TestUnparse_Identical/lit_bytes_with_quote (0.00s)
        unparser_test.go:103: Got 'b"aaa"bbb"', wanted 'b'aaa"bbb''
        unparser_test.go:109: Second parse differs from the first. Got 'id:1 const_expr:<bytes_value:"aaa\"bbb" > ', wanted 'id:1 
```

- [ ]  parser
- [ ]  checker
- [ ]  interpreter
- [x]  unparser

**Expected behavior**

output `b'aaa"bbb'` or `b"aaa\"bbb"`

**source code**

```go
case *exprpb.Constant_BytesValue:
		// bytes constants are surrounded with b"<bytes>"
		b := c.GetBytesValue()
		un.str.WriteString(`b"`)
		un.str.Write(b)
		un.str.WriteString(`"`)
```

**Comment by TristonianJones** [comment]
Thanks for the report. I'm guessing a similar issue probably appears on various forms of quoted strings as well.
