### ISSUE TITLE
is it the correct way to format cel expr

### ISSUE THREAD

**Issue by virusdefender** [cel-expr/cel-go#282]
**Describe the bug**
I want to format the cel expr submitted by other users, the only way i think is to parse and then unparse, however, i have some questions.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [ ]  interpreter
- [x]  unparser

```go
func TestFmtCELExpr(t *testing.T) {
	src := "func(a,b) - func1(c     +d) ==func3(a?b:   c)"
	fmt.Println(src)
	p, iss := Parse(common.NewTextSource(src))
	if len(iss.GetErrors()) > 0 {
		t.Fatal(iss.ToDisplayString())
	}
	out, err := Unparse(p.GetExpr(), p.GetSourceInfo())
	if err != nil {
		t.Error(err)
	}
	fmt.Println(out)
	out1, err := Unparse(p.GetExpr(), nil)
	if err != nil {
		t.Error(err)
	}
	fmt.Println(out1)
}
```

```
func(a,b) - func1(c     +d) ==func3(a?b:   c)  # origin
func(a,b) - func1(c     + d) == func3(a? b : c) # with source info
func(a,b) - func1(c + d) == func3(a? b : c) # without source info
```

so we have two results, none of them is equal to src and none of them are perfect

however it source info is nil, the result is slightly different with the prefect output

**Comment by TristonianJones** [comment]
I've actually been considering removing the use of `source_info` from `parser.Unparse` and adjusting the output format to look like what you'd expect from something like`go fmt`. I'll consider this a request to do just that. 

Thanks for the report!
