### ISSUE TITLE
Support formatting options when unparsing ASTs to strings

### ISSUE THREAD

**Issue by TristonianJones** [cel-expr/cel-go#293]
**Feature request checklist**

- [X] There are no issues that match the desired change
- [X] The change is large enough it can't be addressed with a simple Pull Request
- [ ] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**
When unparsing ASTs, currently the tool will emit a single-line expression which is well-formatted, but maybe not the most kind on human eyes. Add options to support formatting rules, such as add newlines at `&&` and `||` when expressions are greater than 80 chars.

**Comment by l46kok** [comment]
We could create a new function signature that takes in a variadic of formatting options in the `unparser`:

```go
func Unparse(expr *exprpb.Expr, info *exprpb.SourceInfo, opts ...FormattingOptions)
```

```go
type formattingOptions struct {
	wrapBehavior WrapBehavior // Defines when new lines should be introduced.
	wrapColumn int // Defaults to 80
}

type WrapBehavior int

const (
	NO_WRAP WrapBehavior = iota
	WRAP_ON_LOGICAL_OPERATORS
)
```

Alternatively, WrapBehavior enum can be made to support bitwise operation if we anticipate supporting multiple wrapping rules.

Let me know if this was what you were looking for and if so I'll send a PR.

**Comment by TristonianJones** [comment]
@l46kok `FormattingOption` seems like an apt choice. I think it's most likely that you'll have a series of boolean flags which indicate what the wrapping behavior is since the language itself is quite small and the options limited; alternatively, you could like the operator names that you wish to support wrapping on, e.g. `operators.LogicalAnd`, `operators.LogicalOr`, `operators.Conditional`. Something to consider.
