### ISSUE TITLE
Help wanted: cannot find package cel-spec/.../test_all_types

### ISSUE THREAD

**Issue by dysuby** [cel-expr/cel-go#296]
hi all, i want to use cel in my app (using GO modules), but don't know how to import it. I try to use `go get github.com/google/cel-go/...` but it raise errors like below: 

```
package github.com/google/cel-spec/proto/test/v1/proto2/test_all_types: cannot find package "github.com/google/cel-spec/proto/test/v1/proto2/test_all_types" in any of:
        /usr/local/Cellar/go/1.13.4/libexec/src/github.com/google/cel-spec/proto/test/v1/proto2/test_all_types (from $GOROOT)
        /Users/sukyun/go/src/github.com/google/cel-spec/proto/test/v1/proto2/test_all_types (from $GOPATH)
package github.com/google/cel-spec/proto/test/v1/proto3/test_all_types: cannot find package "github.com/google/cel-spec/proto/test/v1/proto3/test_all_types" in any of:
        /usr/local/Cellar/go/1.13.4/libexec/src/github.com/google/cel-spec/proto/test/v1/proto3/test_all_types (from $GOROOT)
        /Users/sukyun/go/src/github.com/google/cel-spec/proto/test/v1/proto3/test_all_types (from $GOPATH)
```
how can i fix it ?

## Another Question

How can I use `cel-go` to deploy a rpc service and parse expressions on it？I cannot find enough docs about it 😂.

**Thx a lot**

**Comment by tobiaszheller** [comment]
It looks like you are trying to compile it instead of add dependencies as go modules. Can you make sure that you already initialized project with `go mod init` and you are in your project path? I have tried it right now on fresh project I can add it without any issues on `go1.13`.

**Comment by dysuby** [comment]
thank for reply! I found out that it was really my fault. I can import it successfully now.

As for second question,  I want to setup a service that can parse and eval expression from users. Should i use `cel-go/server` directly? 

thx

**Comment by tobiaszheller** [comment]
@vegchic you should follow [examples](https://github.com/google/cel-go/blob/1cb01ca62c5d6c2553ade6f27d12d773aaf8cdc4/cel/cel_test.go#L40-L159)

**Comment by dysuby** [comment]
thx a lot, i think this issue can be closed
