### ISSUE TITLE
FR: Built-in substring functions

### ISSUE THREAD

**Issue by wlynch** [cel-expr/cel-go#306]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [x] The change is large enough it can't be addressed with a simple Pull Request
- [x] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**
It would be great to see built-in substrings in CEL to complement the existing concatenation and matching.

This is something we're adding ourselves as a custom definition in [our own project](https://github.com/tektoncd/triggers/pull/329), but it'd be great to see something like this upstream!

**Example**
Given a string `s = "0123456789"`:

Expression | Evaluation
--------------- | --------------
s[0] | "0"
s[:5] | "01234"
s[5:] | "56789"
s [1:3] | "12"

**Alternatives considered**
n/a

**Comment by TristonianJones** [comment]
Hi Billy,

I appreciate the feature request. Thanks for using CEL!

With respect to custom syntax for sub-ranges, I'm a fan of it in more powerful languages, but I'm reluctant to add support for it in CEL. The inclusion of such functionality at the syntax level implies that certain, potentially expensive computations, can't be disabled. It's actually for this reason that we're planning string and list concatenation out of the default `+` operator and into their own `concat` (or similar) functions. Ideally, the operator implies the same or similar cpu and memory cost no matter the operand types. 

I would like to make it easier to enable optional modules of functionality for things like string manipulation, time computations, and list/map manipulation. They're not really part of the core language, but the should be simple to enable.

One model I've been considering is to create module like so:

```go
type Module interface {
   CompileOptions() []EnvOption
   ProgramOptions() []ProgramOption
}
```

I would also add a top-level `cel.Compile` function that accepts `Module` values as inputs and perform the proper bindings. For anyone who wants to break apart the parse / check from eval, you could still use the `Module` members directly.

Thoughts?

**Comment by TristonianJones** [comment]
@wlynch Curious to hear your thoughts on the suggested approach when you get a chance.

**Comment by wlynch** [comment]
A module based approach sounds great! I think that would help us bundle our own custom functions for reuse across our own project.

Would this basically be a wrapper around the existing Declarations/ProgramOptions so that they only need to be declared once? e.g. something like:

```go 
env := cel.NewEnv(cel.StringModule(), cel.TimeModule(), ...)
...
p, err := env.Program(checked)
p.Eval(data)
```

**Comment by TristonianJones** [comment]
Something to that effect, yes.

```go
// The module objects provide declarations and a set of ProgramOptions for their
// concrete implementations that will then be used implicitly within the env.Program()
// construction.
env := cel.NewEnv(cel.StringModule(), cel.TimeModule(), ...)

// Introduce a new Compile method which does the Parse / Check / Program call all in one shot
// Parse / Check / Program are useful for separating the validation and storage of an expression
// from the need to bind it to something evaluable at runtime. In many cases though I expect that
// Compile from a string source and keep resident in memory will be the common case.
p, err := env.Compile(`<expr>`, <ProgramOption>...)

// Eval as usual.
p.Eval(data)
```

**Comment by wlynch** [comment]
LGTM! I think that would fit our use case nicely. :)

**Comment by TristonianJones** [comment]
@wlynch I'm going to take a crack at a string library, though there are a few refactors I'll be making first. When I started looking at the implementation, I realized I could be making the general process of adding new functions much easier and safer.
