### ISSUE TITLE
Parsing Fuzzer

### ISSUE THREAD

**Issue by lopezator** [cel-expr/cel-go#317]
**Describe the bug**

I discovered through fuzzing:

https://github.com/dvyukov/go-fuzz  
https://medium.com/@dgryski/go-fuzz-github-com-arolek-ase-3c74d5a3150c  

That some string inputs passed to the parser function end up in a panic:

```go
func TestFuzzCrashers(t *testing.T) {
	var crashers = []string{
		"--",
		"?",
	}
	env, err := NewEnv()
	if err != nil {
		t.Fatal(err)
	}
	for _, crasher := range crashers {
		_, _ = env.Parse(crasher)
	}
}
```

For example, "--", and "?" (and might be more).

The error message is:

```bash
panic: unknown parsetree type: '<nil>': <nil> [<<nil>>]
```

**To Reproduce**
Check which components this affects:

- [x]  parser
- [ ]  checker
- [ ]  interpreter

Tried only with the parser, but we could fuzz also on other places.

**Expected behavior**

To err and not to panic when passing an incorrect string.

I could start a PR if you consider this to be useful.

**Comment by TristonianJones** [comment]
Hi @lopezator, thanks for the report!

A PR for the fuzzer would be greatly appreciated! If you wouldn't mind using https://github.com/google/gofuzz that would be easiest to integrate. 

As for the panic, it originates here: https://github.com/google/cel-go/blob/master/parser/parser.go#L131. A better behavior would be to report the error and return an error node within the parse tree. I can make this quick code change if you'd like to work on the Fuzzer PR in parallel.

What do you think?

**Comment by TristonianJones** [comment]
Once PR #318 is submitted, I'll switch this from a bug to a feature request. If you'd like to contribute a fuzzer, I'd be super happy to have one @lopezator

**Comment by lopezator** [comment]
Wow that's nice, I'll fuzz again once the changes in #318 are addressed to see if more crashes occur.

**Comment by TristonianJones** [comment]
Okay @lopezator the code is all ready for you

**Comment by TristonianJones** [comment]
With the bug now fixed, I've recast this PR as Parser Fuzzing support. Thanks again for filing @lopezator and I look forward to having fuzz tests in the CEL-Go repo.

**Comment by TristonianJones** [comment]
The cel-go parser an interpreter are currently part of the oss-fuzz project. Marking fixed.
