### ISSUE TITLE
Ambiguous Error Message for Missing Attribute.

### ISSUE THREAD

**Issue by mtheodorides** [cel-expr/cel-go#330]
The current error message for missing attributes looks like this: "no such attribute: &{2 [0xc00039f030] 0xc000196cb0 0xc000196cb0 0xc000dac540}"

It would be nice if the message made it easier for humans to identify the attribute that is missing by including a variable name in the message.

**Comment by TristonianJones** [comment]
Thanks for the issue report! I think this should be as simple as providing `String() string` methods on the `Attribute` implementations if you want to take a shot at making the change you'd like to see.
