### ISSUE TITLE
Env.Extend() result shares state

### ISSUE THREAD

**Issue by mctofu** [cel-expr/cel-go#333]
**Describe the bug**
This is a minor issue that prevents using a shared parent Env to build multiple child Envs.

Env.Extend() returns a new Env that shares the underlying slices of the original Env. If I extend the same Env more than once then previous extended Envs can be modified by the current one. This is because they append into the same slice.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [ ]  interpreter

Test setup:
```go
func TestEnvExtends(t *testing.T) {
	baseEnv, err := cel.NewEnv(cel.Declarations(
		decls.NewIdent("age", decls.Int, nil),
		decls.NewIdent("gender", decls.String, nil),
		decls.NewIdent("country", decls.String, nil)))
	if err != nil {
		t.Fatal(err)
	}

	env1, err := baseEnv.Extend(cel.Declarations(
		decls.NewIdent("name", decls.String, nil)))
	if err != nil {
		t.Fatal(err)
	}

	env2, err := baseEnv.Extend(cel.Declarations(
		decls.NewIdent("group", decls.String, nil)))
	if err != nil {
		t.Fatal(err)
	}

	if _, issues := env2.Compile("size(group) > 10"); issues.Err() != nil {
		t.Fatal(issues.Err())
	}

	// I expect this to work but env1 now has "group" instead of "name"
	if _, issues := env1.Compile("size(name) > 10"); issues.Err() != nil {
		t.Fatal(issues.Err())
	}
}
```
```
--- FAIL: TestEnvExtends (0.01s)
    cel_test.go:37: ERROR: <input>:1:6: undeclared reference to 'name' (in container '')
         | size(name) > 10
         | .....^
```

**Expected behavior**
In the test case I expect env1 to have the declarations of baseEnv + name and env2 to have the declarations of baseEnv + group.

I'd also expect similar behavior for other configurable slice fields.

**Additional context**
I'm reporting this as an Env.Extend() issue but it could also be solved if the EnvOptions made new copies of slices instead of appending.

**Comment by TristonianJones** [comment]
Thanks for the detailed report. I'll put together a fix.

**Comment by mctofu** [comment]
Thanks for the quick fix!
