### ISSUE TITLE
cel.ClearBuiltins was removed but doc comments still reference it

### ISSUE THREAD

**Issue by sfllaw** [cel-expr/cel-go#344]
**Describe the bug**

The doc comments for [`cel.ClearMacros`](https://pkg.go.dev/github.com/google/cel-go/cel?tab=doc#ClearMacros), [`cel.Declarations`](https://pkg.go.dev/github.com/google/cel-go/cel?tab=doc#Declarations), and [`cel.Macros`](https://pkg.go.dev/github.com/google/cel-go/cel?tab=doc#Macros) mention `cel.ClearBuiltins` which was replaced by `cel.NewCustomEnv` in #311 

**Expected behavior**

These doc comments shouldn’t have references to the removed function. They can simply be deleted.

Perhaps it would be helpful to mention `NewCustomEnv`, but I would suggest that this be an `ExampleCustomEnv`.

**Comment by TristonianJones** [comment]
@sfllaw Thanks for the report, I'll tackle this a bit later today.
