### ISSUE TITLE
Flatten or reduce a list of lists

### ISSUE THREAD

**Issue by btomasini** [cel-expr/cel-go#352]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [x] The change is large enough it can't be addressed with a simple Pull Request
- [ ] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**
I don't know if this is a feature request or a request for assistance. I have a cel expression which maps a list and in the predicate does a lookup against a map<string, list<string>>.  The result is a list of lists of stings, eg [['a'],[],['b', 'c']].  I would like to combine these into a single list of ['a','b','c'].  Here are some options I have thought of:

1. A flatmap macro.
2. A flatten function
3. A reducer in which I append the lists together

So far I am closest to implementing option 2 but am having some troubles with the InstanceOverloads not matching the input type.

Are there any built-in features of cel-go which would support this?

I am closest to implementing option 2 on my own but am having some troubles with the instance overloads not matching. If there is no built-in feature of cel-go for this, I will post a code sample here of my current work.

**Comment by TristonianJones** [comment]
Hi @btomasini. A function makes the most sense (Option 2). Do you happen to have an example, test case, or gist that you could share?

**Comment by btomasini** [comment]
@TristonianJones 

My original attempt failed as I treated it as an instance override rather than a global.  I plan to try again soon and will let you know what I come up with it.

**Comment by TristonianJones** [comment]
@btomasini If you'd like some general support for CEL, you're also welcome to reach out to cel-go-discuss@googlegroups.com. It's usually a better forum for free-form discussion.

**Comment by TristonianJones** [comment]
Hi @btomasini if you need any further help, I'd be happy to help in the discussion forums. For now, I'm closing the issue.
