### ISSUE TITLE
Comparing timestamps?

### ISSUE THREAD

**Issue by mholt** [cel-expr/cel-go#357]
Hi, sorry for the lame question -- how can I compare timestamps using CEL + this library?

I tried `timestamp(0) == timestamp(0)` but I get false every time.

Is there a reference I could read about how to do this?

**Comment by TristonianJones** [comment]
That should work. Let me add a quick conformance test and get back to you.

**Comment by mholt** [comment]
It's _very_ possible there is a bug on my end too -- I will dig down more, now that I know that should work.

**Comment by TristonianJones** [comment]
Ah, there's no overload for timestamp from epoch: 
`type conversion error from 'int' to 'google.protobuf.Timestamp', wanted true`

We could add one if you like. I see no reason not to support this.

**Comment by TristonianJones** [comment]
@mholt This is a bug on our side. Sorry about this. It's clearly in the `checker`, but not in the `interpreter`.

**Comment by mholt** [comment]
No worries, thanks for checking!

My objective is to compare timestamps. I would prefer to use `==   <    >` operators since they are so convenient. If it's not too much trouble, I think it could be really useful.

**Comment by TristonianJones** [comment]
Oh, yes, the comparisons are certainly supported. The problem is that the function declaration was added to the Go type-checker, but not the interpreter. We missed it in our conformance audit since the spec indicates that only `timestamp(string)` is supported. I'll add an issue to update the spec, but will fix the Go implementation shortly.

**Comment by TristonianJones** [comment]
@mholt I'll put together a point release once this is checked in.

**Comment by mholt** [comment]
Thanks! That's fast!

**Comment by TristonianJones** [comment]
@mholt You should be all set to bump up to v0.5.1 :) Thanks for the reaching out!

**Comment by mholt** [comment]
Works like a charm. Thank you very much!
