### ISSUE TITLE
strings: add string casing functions

### ISSUE THREAD

**Issue by bitsofinfo** [cel-expr/cel-go#370]
Would be great to have some string casing functions in strings.co extension https://github.com/google/cel-go/tree/master/ext

such as `toUpper`, `toLower` etc @TristonianJones

**Comment by TristonianJones** [comment]
@bitsofinfo I'd be happy to have `lowerAscii` and `upperAscii`. Would that work? 

I had tried to introduce `lower` and `upper` with the first set of extensions, but found what appeared to be inconsistencies between Go case-mapping and the Unicode case-mapping spec.

**Comment by bitsofinfo** [comment]
yep that will do! thx
