### ISSUE TITLE
simplified version of exists for lists

### ISSUE THREAD

**Issue by lopezator** [cel-expr/cel-go#388]
Hello @TristonianJones this is more a question/advice request rather than an issue, so feel free to close this is this doesn't apply.

Having a field like this in our specification:

```
message User {
    repeated string roles = 1;
}
```

We just want to know if a specified value exists on the mentioned string list. If I am not mistaken, the way to go (if we don't care about that value being more than once) would be:

```
roles.exists(x, x == 'roles/admin')
```

But this is verbose/hard to remember for a such simple scenario like this and generates an AST with a `ComprehensionExpr`, which is quite complex to parse. Would you recommend any simpler way to accomplish this? We were thinking in something like:

```
roles.exists('roles/admin')
```

What would be the best way to go?  Overloading the exists function with just a string value? (if this is possible). Ideas?

Thank you!

**Comment by lopezator** [comment]
This can be done in JavaScript using `indexOf`. In ECMAScript2016 this is called `includes`. On the other hand, I think this is called `contains` in Java, so...  maybe the way to go is just overloading the `contains` method for a `List` type? 

CC/ @glerchundi

**Comment by TristonianJones** [comment]
Hi @lopezator! 

The `in` operator can be used to test for a value in a list: `'roles/admin' in roles`

If you'd prefer to not use `in`, then providing a `contains` function patterned after the `Lister.Contains` function would probably be your best bet. 

-Tristan

**Comment by lopezator** [comment]
Ouch, completely missed the `in` operator for lists, my fault.

I think this will serve us well, I'll close this for now.

Thank you for your fast response!
