### ISSUE TITLE
Unable to fit custom map type

### ISSUE THREAD

**Issue by aionbit** [cel-expr/cel-go#400]
https://github.com/google/cel-go/blob/385dcdcbc4865cb64aa953c12d7549615cb5fd03/common/types/map.go#L240

https://github.com/google/cel-go/blob/385dcdcbc4865cb64aa953c12d7549615cb5fd03/common/types/list.go#L190

expect:

	otherMap, ok := other.(traits.Mapper)
	if !ok {
		return ValOrErr(other, "no such overload")
	}

**Comment by TristonianJones** [comment]
Fixed in #399 since I was in this code anyway. Thanks for the ticket!

**Comment by aionbit** [comment]
Thanks very much. @TristonianJones
