### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tonirmv** [cel-expr/cel-go#405]
**Describe the bug**

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [ ]  interpreter

Sample expression and input that reproduces the issue:
```cel
// sample expression string
```

Test setup:
```go
// test case in go
```

**Expected behavior**

**Additional context**

**Comment by TristonianJones** [comment]
This isn't quite enough to go off of. Could you add some detail?

**Comment by TristonianJones** [comment]
If this is a real issue, please re-open the ticket with the information requested and we'll be happy to take a look.
