### ISSUE TITLE
Why remove the "NewValueList" function from the master branch?

### ISSUE THREAD

**Issue by dean2021** [cel-expr/cel-go#407]
Why remove the "NewValueList" function from the master branch?

**Comment by TristonianJones** [comment]
The `types.NewValueList` was replaced with `types.NewRefValList` in #399. The reason for the name change was to avoid confusion with the `structpb.Value` type. I'll make sure to document the removal in the next release notes.

In general, prefer to rely on the `TypeAdapter#NativeToValue` interface method which will invoke the appropriate constructor for the object type:

https://github.com/google/cel-go/blob/4c3317a66a3a4ce51b74b76360f59282da52e03d/common/types/ref/provider.go#L58
