### ISSUE TITLE
Question: Go structure value reflection?

### ISSUE THREAD

**Issue by Julio-Guerra** [cel-expr/cel-go#408]
Hello,

I couldn't find any way of binding bare Go values, especially Go structures, in CEL declarations. My understanding is that this is limited to protobufs only so far. Is there any way to have some "wrapper" value where I could use Go reflection?

A simple example of a use-case I have: accessing `*http.Request` values from CEL expressions. Ideally, I don't want to copy/convert it into another protobuf value, but rather use it in-place.

Thanks!

**Comment by TristonianJones** [comment]
Thanks for the request @Julio-Guerra. This sounds like a good feature ask, and I know it's come up before in other contexts. A `ref.TypeProvider` could be implemented to support Go structs, but one has not been implemented to date. 

I'd be happy to change this into a feature request rather than a question if that works for you. I can also give some pointers on how to implement this yourself if you'd prefer.

Let me know which you prefer. Happy CELing!

-Tristan

**Comment by Julio-Guerra** [comment]
I'd be really happy to. We have come up with [our own 0-copy data querying language](https://github.com/sqreen/go-agent/blob/master/internal/binding-accessor/binding-accessor_test.go) which is a subset of what CEL can do, while we really could make benefit of other features CEL provides.

I'll have a look at `ref.TypeProvider` as soon as I can.

**Comment by abursavich** [comment]
Hey @TristonianJones, I'm interested in CEL and would like to learn more about the internals of the go module. I'm gonna start looking into implementing this. Any guidance would be appreciated, if you have time.

**Comment by kortschak** [comment]
This is something that I would like to see. Currently I have code that essentially serialises and deserialises HTTP requests and responses to allow mutation of the structs by user CEL code, e.g. [here](https://github.com/kortschak/mito/blob/5e293d905848c8529dceac552f1e18a689a28804/lib/http.go#L596-L604), but this obviously has potentially significant performance impacts, and also increases the potential for correctness issues in the implmentation.

**Comment by danielpacak** [comment]
We are looking into integrating cel-go with [Tracee](https://github.com/aquasecurity/tracee) to evaluate expressions like the following:

```
input.EventName == 'ptrace' && arg(input, 'request') == 'PTRACE_TRACEME'
```

I'm not sure if it's valid CEL syntax, but I wanted to confirm that we can declare `input` variable as pure Go struct:

```go
type Event struct {
	EventName           string     `json:"eventName"`
	Args                []Argument `json:"args"` //Arguments are ordered according their appearance in the original event
	ArgsNum             int        `json:"argsNum"`
	ReturnValue         int        `json:"returnValue"`
	StackAddresses      []uint64   `json:"stackAddresses"`
}
```

Did I understand correctly that it's currently not supported without implementing custom `ref.TypeProvider`? /cc @itaysk

**Comment by TristonianJones** [comment]
@danielpacak @kortschak @Julio-Guerra @abursavich If you'd like to take a look at #612 and let me know what more you'd like to see, I finally had a spare minute to provide an extension to support native Go structs in CEL. PTAL and if there are additional features to address in the current PR or subsequent ones, this is a good time to let me know.
