### ISSUE TITLE
Interpret unknowns within PartialActivation after resolving known attributes

### ISSUE THREAD

**Issue by tonyhb** [cel-expr/cel-go#409]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [x] The change is large enough it can't be addressed with a simple Pull Request
- [x] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**

Change `TryResolve` to attempt resolution before testing unknowns.  TryResolve will return the given value if it exists or `Unknown` _only_ if the data is not present in an `Activation`.

**Example**

Forgive my ignorance, but as far as I know unknown patterns override any variables added to an `Activation`.  

With user-generated data (particularly with an expression itself), we only know which variables are missing if we inspect the AST and data.  This is possible, but given we already have the ability to add partials it adds an extra step which is not required.

 For example:

```go
package main

import (
        "fmt"

        "github.com/google/cel-go/cel"
        "github.com/google/cel-go/checker/decls"
        "github.com/google/cel-go/interpreter"
)

func main() {
        data := map[string]interface{}{
                "user": map[string]interface{}{
                        "email": "test@example.com",
                },
                "event": map[string]interface{}{
                        "name": "signup.new",
                },
        }

        partial, _ := interpreter.NewPartialActivation(
                data,
                cel.AttributePattern("user").Wildcard(),
                cel.AttributePattern("event").Wildcard(),
        )

        e, _ := cel.NewEnv(
                cel.Declarations(
                        decls.NewVar("user", decls.NewMapType(decls.String, decls.Dyn)),
                        decls.NewVar("event", decls.NewMapType(decls.String, decls.Dyn)),
                ),
        )

        // contrived
        ast, _ := e.Compile("user.email == 'test@example.com' || user.role == 'admin'")
        prg, _ := e.Program(ast,
                cel.EvalOptions(cel.OptTrackState, cel.OptPartialEval),
        )
        out, det, err := prg.Eval(partial)

        residualAst, _ := e.ResidualAst(ast, det)
        residual, _ := cel.AstToString(residualAst)

        // prints "true" with no AttributePattern in the above partial, or the
        // entire expression with.
        fmt.Println(residual)
        fmt.Println(out, det, err)
}
```

In the above example, we specify that we _may not_ know user or event data.  Though, within data itself `email` is present.  My expectation was that variables will attempt resolution when marked as unknowns in a Partial, and will only resolve to Unknown if the variable isn't present.

Else, we have to parse the incoming data _and_ the expression for all `*expr.Expr_SelectExpr` types to see what variables are being evaulated.  Then, we have to specify each missing item within an attribute pattern itself. 

Essentially, instead of specifying the two AttributePatterns above`, we need to walk the AST, inspect all SelectExpr items, check whether the data exists, and then specify an AttributePattern if the data is missing manually.

This seems redundant if we already allow Partials and have TryResolve :)

**Comment by TristonianJones** [comment]
Hi @tonyhb. For your use case, I had envisioned something a bit different which is to optimistically evaluate before pessimistically providing the partial state and computing a residual. In many cases, users will know the absent fields up front; however, if they are _sometimes_ provided, then I'd recommend computing the residual pessimistically. 

```go
        prg, _ := e.Program(ast,
            cel.EvalOptions(cel.OptTrackState, cel.OptPartialEval),
        )
        out, det, err := prg.Eval(data)
        if err == nil {
            fmt.Println(out, det, err)
            return
        }
        _, det, err := prg.Eval(partial)
        if err != nil {
            residualAst, _ := e.ResidualAst(ast, det)
            residual, _ := cel.AstToString(residualAst)
            fmt.Println(residual)
        }
```

I see your point about the `TryResolve` when you don't know the attribute ahead of time, but I need to think about it. One option to make this simpler would be to expose the attribute set present in the expression via a helper method. 

The main issue with what you're suggesting is that you could access a partially populated map or object. It would have a key/field and a value, but the value would be incomplete. For example, `user == {'email': 'test@example.com', 'role': 'admin'}` would immediately return unknown in the current setup, but with your suggestion would return `false`. I offer this as an explanation as to why things are the way they are, but I'll need to think about this more before relaxing the constraint on field/key accesses where the result is a simple type.

**Comment by tonyhb** [comment]
@TristonianJones thanks for the response and the tip for optimistically then pessimistically evaluating.

I'll give it a go, though this use case is odd: we want to inspect everything exhaustively to see if the expression is testing against any timestamps, and if so, what the minimum next timestamp is for re-evaluation.   


To be honest, it's not too much of an issue to inspect the AST and pull out the attribute set that is being inspected.  I was just hoping not to, considering the AST is parsed again in order to evaluate the expression :)

Just in case it's useful to anyone else, here's the code for inspecting attributes within a map type for an expression:

```go
        // where e is an env already instantiated
        ast, _ := e.Compile(expression)

        // eg "user": { "name": struct{}{}, "email: struct{}{} }
        attrMap := map[string]map[string]struct{}{}

        stack := []*expr.Expr{ast.Expr()}
        for len(stack) > 0 {
                ast := stack[0]
                stack = stack[1:]
                switch ast.ExprKind.(type) {
                case *expr.Expr_CallExpr:
                        // Everything is a function call:
                        // - > evaluates to _>_ with two arguments, etc.
                        // This means pop all args onto the stack so that we can find
                        // all select expressions.
                        stack = append(stack, ast.GetCallExpr().GetArgs()...)
                case *expr.Expr_IdentExpr:
                        name := ast.GetIdentExpr().Name
                        attrMap[name] = map[string]struct{}{}
                case *expr.Expr_SelectExpr:
                        name := ast.GetSelectExpr().Operand.GetIdentExpr().GetName()
                        field := ast.GetSelectExpr().Field
                        if _, ok := attrMap[name]; !ok {
                                attrMap[name] = map[string]struct{}{}
                        }
                        attrMap[name][field] = struct{}{}
                }
        }

        result := map[string][]string{}
        for k, attrs := range attrMap {
                result[k] = make([]string, len(attrs))
                i := 0
                for attr := range attrs {
                        result[k][i] = attr
                        i++
                }
        }
```

Edit:  the above fits my use case with two user-supplied maps, but does not inspect the full range of `decls.NewVar` within an env.  This only inspects `decls.NewMapType` map keys within an expression.

**Comment by TristonianJones** [comment]
Hi @tonyhb you could also use a `cel.CustomDecorator` and collect the set of `interpreter.InterpretableAttribute` values where the `Attr()` field is an instance of an `interpreter.NamespacedAttribute` since this will allow you to inspect the names of the qualified field accesses that appear within the expression. This sounds more complex than it is ...

```go
attrNames := map[string]struct{}{}
attrCollector := func(i interpreter.Interpretable) (interpreter.Interpretable, error) {
    attr, ok := i.(interpreter.InterpretableAttribute)
    if !ok {
        return i, nil
    }
    nsAttr, ok := attr.Attr().(interpreter.NamespacedAttribute)
    if !ok {
        return i, nil
    }
    for _, nm := range nsAttr.CandidateVariableNames()
    attrNames[nm] = struct{}{}
}
prg, err := e.Program(ast, cel.CustomDecorator(attrCollector))
// attrNames should be populated with keys like:
// user.name, user.email, request.time
```

This way you'll always get the same view of the relevant attributes as CEL does. It's hopefully less to maintain. Here's another example of using the program decorators to modify behavior as well: https://github.com/google/cel-go/blob/v0.7.0/cel/cel_test.go#L991. You may want to use a decorator that calculates the next evaluation time given the time at which the program is being planned, which should also be possible to do.

**Comment by TristonianJones** [comment]
I'm going to close this for now, but please feel free to re-open if you'd still like to see improvements here.
