### ISSUE TITLE
codelab execution instructions

### ISSUE THREAD

**Issue by jkanywhere** [cel-expr/cel-go#417]
The section "Execute the code" on https://codelabs.developers.google.com/codelabs/cel-go#3 states `go run github.com/google/cel-go` however this leads to an error
```
$ go run github.com/google/cel-go
go: finding module for package github.com/google/cel-go
cannot find module providing package github.com/google/cel-go: invalid github.com/ import path "github.com/google"
```

According to https://stackoverflow.com/questions/55631569/go-mod-cannot-find-module-providing-package it is because there is no main package at the top level of cel-go.

I think the execution command should run the codelab directory: `go run github.com/google/cel-go/codelab`.
That will make it match with section 3. Set Up: https://codelabs.developers.google.com/codelabs/cel-go#2

**Comment by TristonianJones** [comment]
Should be updated shortly. Thanks for the report.
