### ISSUE TITLE
Ambiguous import of github.com/antlr/antlr4/runtime/Go/antlr

### ISSUE THREAD

**Issue by vadimsht** [cel-expr/cel-go#441]
**Describe the bug**
go.mod imports `github.com/antlr/antlr4`, but it's  not the "real" module (there's no go.mod in github.com/antlr/antlr4). The "real" module is `github.com/antlr/antlr4/runtime/Go/antlr` (it has go.mod). If something in a module imports cel-go and another module that references `github.com/antlr/antlr4/runtime/Go/antlr`, Go gets confused. It is also gets confused when running `go get -t -u ./...` even when cel-go is the only dependency.

**To Reproduce**

```
$ mkdir testmod
$ cd testmod
$ go mod init testmod
$ cat >main.go <<EOL
package main
import _ "github.com/google/cel-go/cel"
EOL
$ go mod tidy
$ go get -t -u ./...
testmod imports
	github.com/google/cel-go/cel imports
	github.com/google/cel-go/parser imports
	github.com/antlr/antlr4/runtime/Go/antlr: ambiguous import: found package github.com/antlr/antlr4/runtime/Go/antlr in multiple modules:
	github.com/antlr/antlr4 v0.0.0-20200503195918-621b933c7a7f (.../.modcache/github.com/antlr/antlr4@v0.0.0-20200503195918-621b933c7a7f/runtime/Go/antlr)
	github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20210707120613-a80295a60b3e (.../.modcache/github.com/antlr/antlr4/runtime/!go/antlr@v0.0.0-20210707120613-a80295a60b3e)
```

I don't know why exactly this happens, but please consider changing go.mod to refer to `github.com/antlr/antlr4/runtime/Go/antlr`.

**Comment by TristonianJones** [comment]
Thanks @vadimsht I'll update the `go.mod`!
