### ISSUE TITLE
[Question] Dose cel-go allows to build an AST?

### ISSUE THREAD

**Issue by yeqown** [cel-expr/cel-go#444]
In my situation, I want to build an AST then translate it into the expression, so I wonder `cel-go` has the ability to build AST or not?

make expression can be configured in management Dashboard, it is not inputed but choose components to describe it. In my thought, AST is the best carrier to translate between `Expression` and `View model`

**Comment by TristonianJones** [comment]
You can technically build an AST via the protocol buffers used by CEL:
https://github.com/googleapis/googleapis/tree/master/google/api/expr/v1alpha1
https://github.com/googleapis/go-genproto/tree/master/googleapis/api/expr/v1alpha1

My recommendation would be to build a `ParsedExpr`, convert it to an `Ast` via `cel.ParsedExprToAst` and then type-check the `Ast` before attempting to evaluate it.

```go
var expr ParsedExpr // pass your input here
ast := cel.ParsedExprToAst(expr)
env, err := cel.NewEnv() // add variable declarations, etc.
if (err) {
   return fmt.Errorf("Error configuring environment: %s", err);
}
checkedAst, iss := env.Check(ast)
if (iss.Err() != nil) {
   return fmt.Errorf("Ast failed type checking: %s", iss.Err())
}
prg, err := env.Program(checkedAst)
if (err) {
   fmt.Errorf("Failed to setup program from Ast: %s", err)
}
return prg.Eval(<args>)
```
