### ISSUE TITLE
How to create a case-insensitive map?

### ISSUE THREAD

**Issue by n1ngod** [cel-expr/cel-go#445]
I create a protobuf structs like
```
syntax = "proto3";
package requests;
option go_package = "./requests";

message RequestModel {
  string url = 1;
  string method = 2;
  map<string, string> headers = 3;
  bytes body = 4;
}
```
when i eval expression `request.headers['cookie'] == "some text"` ，the capitalization must be correct. The http header is case-insensitive. Is there a way to make `request.headers['cookie']` and  `request.headers['Cookie']` get the same value?

Current，i must modified these codes to achieve the effect
https://github.com/google/cel-go/blob/2457df3b0ad52151f83584be297a319b002284ce/common/types/map.go#L660-L665
```
        ntvKey, err := key.ConvertToNative(m.value.KeyType.ReflectType())
	if err != nil {
		return &Err{err}, false
	}
+      k, ok := ntvKey.(string)
+	if ok {
+		ntvKey = strings.ToLower(k)
+	}
	// Use protoreflection to get the key value.
	val := m.value.Get(protoreflect.ValueOf(ntvKey).MapKey())
	if !val.IsValid() {
		return nil, false
	}
```
but it is a bad implementation, is there any other way?

**Comment by TristonianJones** [comment]
Good question. You've actually stumbled onto a best practice, which is to always lower-case HTTP headers before providing them as input to CEL. I know it's a pain, but it's good advice and ensures that headers are always being written in a very specific style. 

Some alternatives to lower-casing before evaluation include:
- Enable the `ext/strings.go` library to support the `"String".lowerAscii()` function and ask users to add the call to header accesses.
- Override the `AttributeFactory` to inspect the field selection path and change lookup behavior based on whether the field is attempting to access a `map<string, string>`: https://github.com/google/cel-go/blob/2457df3b0ad52151f83584be297a319b002284ce/interpreter/attributes_test.go#L477

The last option will let you do what you want, but it's tricky to setup.
