### ISSUE TITLE
How to use protobuf enums as strings?

### ISSUE THREAD

**Issue by geokb** [cel-expr/cel-go#450]
Currently when declaring variables from proto3 types that contain enum fields, enums are treated as integers in the CEL expressions. It's usually way more friendly to have enum comparisons as strings not ints. Due to this problem, I have to declare my variable as `decls.Any` and marshal-then-unmarshal the struct to `map[string]interface{}` using `google.golang.org/protobuf/encoding/protojson` in order to correctly use enums as strings in my CEL expressions.

I think there should be an optional feature to parse enums as strings while at the same time not breaking the current default behaviour.

**Comment by TristonianJones** [comment]
Hi @geokb could you give me an example of an expression that you're trying to write?  

Enums may be referenced by their fully qualified identifier name, e.g. `msg.field == my.pkg..CustomEnum.STATUS`. See: https://github.com/google/cel-go/blob/master/interpreter/interpreter_test.go#L425

**Comment by geokb** [comment]
@TristonianJones thanks for the quick response. My use case is that I need to  used the string representations of enums instead of ints. Here is a simple example.

```
enum Type {
  TYPE_A = 0;
  TYPE_B = 1;
  TYPE_C = 2;
}

message Context {
  Type type = 1;
}
```

When using the `Context` type as a declared protobuf var, I want to have expressions written as `ctx.type == "TYPE_A"` instead of `ctx.type == 0`. The problem is that the entire API (very similar to Envoy APIs where configs are parsed from YAML to compiled proto3 structs) is already using the same resources where enums are dealt with as strings not integers. 


I think we could have a feature that can be optionally enabled whenever you declare a new var or env where you parse enums as string instead of int while at the same time not breaking the current default behavior. This is what the package `protojson` does, it by default deals with enums as strings but you can set the marshaller to treat them as ints.

I saw the example in the tests. While it is great if I am the one who uses it, it is unfortunately very confusing since the entire API already deals with the countless enums as strings and the docs are generated as such.

**Comment by TristonianJones** [comment]
@geokb I see, that's unfortunate. I would normally just say use `ctx.type == Type.TYPE_A`, but if `ctx.type` is type `string`, then that's a bit harder to do. 

One thing you could do is iterate over the enum values and provide namespaced identifiers like `Type.TYPE_A` which have the string value `"TYPE_A"` instead of exposing the enum to the program:

```
cel.Declarations(
  decls.NewConst("Type.TYPE_A", decls.String, "TYPE_A"),
  ...
)
```

**Comment by geokb** [comment]
Thanks again @TristonianJones for the quick response and I apologize for the late reply. I will now test the `NewConst` idea but I think this is not really a very good solution anyway. Now I probably have to use reflection to detect all enums and then convert each possible FQDN value, or whatever it is called, of each possible enum in the entire API just to declare them inside the env.

If you're okay with the option of having enums as strings, please let me know, even if you have no intention to implement it, I might help here because I am really interested in this. Even though honestly when it comes to reflection I am a complete rookie.

**Comment by TristonianJones** [comment]
@geokb We'd like to make enums strongly typed and conversions from string or number to enum type explicit, so implicit equality checking with strings would run counter to the longer-term direction.  

If you're looking for some help on reflecting over the set of qualified enum strings, I'd look at `common/types/pb/file.go` for a way to take a `protoreflect.FileDescriptor` and obtain the fully qualified set of enum type names as strings. If you want to experiment with auto-declaring enum conversion signatures and conversion functions `pkg.EnumType("string")` that would definitely be aligned with our longer term direction. The function should return the int value for the enum given the string name.

**Comment by TristonianJones** [comment]
I'm going to close this issue for now since it was mostly a request for information, but if you have a PR you'd like to submit in the future, please let me know.
