### ISSUE TITLE
Ability to parse numbers as decimal

### ISSUE THREAD

**Issue by tp** [cel-expr/cel-go#456]
**Change**

We want to us CEL in the context of some currency calculations. This is would be important to be able to use our own "number" type with the appropriate rounding (to never have more than 2 digits after the decimal point) etc.

Is there any facility how we can switch the parsing of e.g. `1.2` to use this own type instead of double?

Generally I haven't been able to find a clear example of how to add our own "primitives" (if that is supported with some combination of `cel.Types`, `cel.CustomTypeAdapter`, and `cel.CustomTypeProvider`).

**Example**

Goal: "123.45 * 1.19" should evaluate to `146.91 (type "currency" or "decimal")` instead of `146.9055 (types.Double)`

**Alternatives considered**

An alternative considered would be to create types through a function, e.g. `decimal("123.45")` which should work just fine but is a bit more cumbersome to input for the end-user.

If you have any input on how to achieve this or pointers how to make this easier to input, that'd be much appreciated :)

**Comment by TristonianJones** [comment]
Hi @tp! Good question.

While it is possible to introduce new types to CEL, the parser will only understand literals for Core CEL types. You could instead write `decimal(1.2 * 1.19)` to convert the type to  `146.9055 (types.Double)` to `146.91`. For this you would only need to provide a conversion function which may be as simple as rounding the double to the nearest two decimal places. 

I'm not sure whether you actually want more types or a way to more cleanly represent the result of a currency calculation as a `double`. Could you give me a bit more context about your use case? 

Cheers,

-Tristan

**Comment by tp** [comment]
> I'm not sure whether you actually want more types or a way to more cleanly represent the result of a currency calculation as a double. 

For our use-case I would prefer to have a new type, just to be sure it only gets composed in expected/valid ways instead of being treated as `double` and then leaving it to the end-user to round.

I added a new type on my own incl. a parser (e.g. `decimal("123.45")`) and overloads for `+` etc.

For end-user convenience I thought it'd be nice if they could just enter `123.45` and have it treated as/converted to `decimal` instead of `double`, but I guess we can also either live with the parse function or else explore how to restructure the input that at least most "constant variable declarations" don't need the extra ceremony (for example feeding these into the environment from the "Go program" instead of having them be the result of simple CEL expressions).

For now I am good then with the `decimal` function. That seems very clean and is also easily translatable to other numeric types we need detailed control over (e.g. `currency`).
