### ISSUE TITLE
Error computing residuals when using macros

### ISSUE THREAD

**Issue by tonyhb** [cel-expr/cel-go#474]
**Describe the bug**

When using partial activations with unknown variables, we may want to compute the residual expression.  This is supported with the following snippet:

```
	// We'll ignore the result for testing residuals.
	_, details, err := program.Eval(activation)
	if err != nil {
		return "", err
	}

	residualAst, err := env.ResidualAst(ast, details)
	if err != nil {
		return "", fmt.Errorf("error creating ast for residual: %w", err)
	}
	residual, err := cel.AstToString(residualAst)
	if err != nil {
		return "", fmt.Errorf("error converting residual ast to string: %w", err)
	}
```

However, if your expression has a macro computing residuals fails.  Given we have an activation with `data` as `[1, 2, 3]`, and `future` is unknown (representing some future state):

```
data.exists(i, i > future)
```

Computing the residual will fail with `unimplemented`.  (edit: in 0.7.0 it's unimplemented.  on 0.9.0 it's "unsupported expression")

**To Reproduce**
Check which components this affects:

- [x]  parser
- [ ]  checker
- [ ]  interpreter

Sample expression and input that reproduces the issue:

```cel
data.known.exists(i, i == data.future)
```

Test setup:
```go
func Residual() (string, error) {
	activation, _ := interpreter.NewPartialActivation(map[string]interface{}{
		"data": map[string]interface{}{
			"known": []string{"a", "b", "c"},
		},
	}, interpreter.NewAttributePattern("data"))

	env, _ := cel.NewEnv(
		cel.Declarations(
			decls.NewVar("data", decls.NewMapType(decls.String, decls.Dyn)),
		),
	)
	ast, issues := env.Compile("data.known.exists(i, i == data.future)")
	if issues != nil {
		return "", issues.Err()
	}

	program, err := env.Program(
		ast,
		cel.EvalOptions(cel.OptExhaustiveEval, cel.OptTrackState, cel.OptPartialEval),
	)

	_, details, err := program.Eval(activation)
	if err != nil {
		return "", err
	}
	residualAst, err := env.ResidualAst(ast, details)
	if err != nil {
		return "", fmt.Errorf("error creating ast for residual: %w", err)
	}
	residual, err := cel.AstToString(residualAst)
	if err != nil {
		return "", fmt.Errorf("error converting residual ast to string: %w", err)
	}
	return residual, err
}

```

**Expected behavior**

You may expect the AST to contain the original macro with the variable swapped out, eg. for the string version of the residual AST to read `["a", "b", "c"].exists(i, i == future)`.

**Actual behaviour**

We receive an error:

```
unimplemented : id:16  comprehension_expr:{iter_var:"i"  iter_range:{id:2  select_expr:{operand:{id:1  ident_expr:{name:"data"}}  field:"known"}}  accu_var:"__result__"  accu_init:{id:9  const_expr:{bool_value:false}}  loop_condition:{id:12  call_expr:{function:"@not_strictly_false"  args:{id:11  call_expr:{function:"!_"  args:{id:10  ident_expr:{name:"__result__"}}}}}}  loop_step:{id:14  call_expr:{function:"_||_"  args:{id:13  ident_expr:{name:"__result__"}}  args:{id:6  call_expr:{function:"_==_"  args:{id:5  ident_expr:{name:"i"}}  args:{id:8  select_expr:{operand:{id:7  ident_expr:{name:"data"}}  field:"future"}}}}}}  result:{id:15  ident_expr:{name:"__result__"}}}
```

(edit: in 0.7.0 it's unimplemented.  on 0.9.0 it's "unsupported expression", with the same comprehension_expr AST)

**Comment by tonyhb** [comment]
So, what I'm about to post is based off of theory and assumptions without reading how CEL works with the AST.  My apologies if this is wrong;  I'll do some digging after posting these thoughts.

I anticipate that this is difficult to do because we expand the macros into the full AST.  Expanding macros could be "lossy" - it's hard to go back from expanded comprehensions to macros.  If this is the case, I may explore what it would take to store two separate ASTs:  the parsed AST and the expanded AST.  It would make ASTs bidirectional for unparse.

In this case, we could replace the knowns in the parsed AST with concrete consts and leave the unknowns.

Anyway, thoughts over:  I'll do some cursory digging to see if this is possible.

@TristonianJones - is this something that the CEL team would like to see?

**Comment by TristonianJones** [comment]
@tonyhb I believe I added support for this, but as a new option when you parse / check the expression. `cel.EnableMacroCallTracking()`. If you provide this functional option as part of your environment, the decode should work as you expect, at least for unparsing. I haven't tried residuals extensively.

**Comment by tonyhb** [comment]
Awesome!  I saw that poking around master as I was reading through parsing.  I'll take a look at residuals later and get back to you (have a few other items on the list right now).

**Comment by TristonianJones** [comment]
I'm guessing that your needs were met. Please feel free to reopen if you need additional help.
