### ISSUE TITLE
Question: How to implement a variadic function

### ISSUE THREAD

**Issue by xqzhou** [cel-expr/cel-go#476]
I could't find a way to implement a variadic function which can take a variable number of argument of different types, for example, an Excel-like concatenate function:
```
concatenate("Hello", "World", 100, "Times", ...)
```

Any clue is appreciated.

**Comment by TristonianJones** [comment]
Hi @xqzhou, variadic functions are not supported in CEL, but you can provide a `list(dyn)` argument to the `concatenate` function and it will work as you expect: 

```
concatenate(["Hello", "World", 100, "Times"])
```
