### ISSUE TITLE
Codelab solution for step 10 proto conversion panics

### ISSUE THREAD

**Issue by aabmass** [cel-expr/cel-go#478]
**Describe the bug**
Running [Codelab step 10](https://codelabs.developers.google.com/codelabs/cel-go/index.html#9) `exercise6()` panics on v0.9.0 (and main):
```
=== Exercise 6: Building Protos ===


  Request{
   auth: Auth{
    principal: jwt.iss + '/' + jwt.sub,
    audiences: [jwt.aud],
    presenter: 'azp' in jwt ? jwt.azp : "",
    claims: jwt
   },
   time: now
  }

------ input ------
jwt = {
  "aud": "my-project",
  "extra_claims": {
    "group": "admin"
  },
  "iss": "auth.acme.com:12350",
  "sub": "serviceAccount:delegate@acme.co"
}
now = seconds:1644247358
------ result ------
value: &{0xc00046f8a0 0xc000410780 0xc000094840 0xc000243c50} (*types.protoObj)

panic: interface conversion: interface {} is *dynamicpb.Message, not *attribute_context.AttributeContext_Request

goroutine 1 [running]:
main.exercise6()
        ~/tmp/cel-go/codelab/solution/codelab.go:312 +0x946
main.main()
        ~/tmp/cel-go/codelab/solution/codelab.go:51 +0x34
exit status 2
```

The last tag that it correctly runs with was v0.6.0.

**To Reproduce**
Check which components this affects:

- [x]  interpreter (maybe?)
- [x] codelab

Sample expression and input that reproduces the issue:
https://github.com/google/cel-go/blob/fa20ec8537cd02b9a25f56d4e0f3693792dfe07d/codelab/solution/codelab.go#L312

Test setup:
`go run github.com/google/cel-go/codelab/solution`

**Expected behavior**
The codelab should execute without panicking. I was expecting `cel.Program.Eval()` to return the actual protobuf message type instead of a `*dynamicpb.Message`.

**Additional context**
I encountered this after noticing that CEL expressions were always returning `*dynamicpb.Message` instead of the protobuf message the expression outputs.

**Comment by TristonianJones** [comment]
Thanks for the report @aabmass I'll give it a look.

**Comment by TristonianJones** [comment]
Hi @aabmass, I've found the issue and the fix.

Around v0.6.0, the CEL library migrated to Golang protobuf API v2. The updated proto API significantly altered its reflection behavior to return dynamic protos nearly always. To ensure the proper protobuf type used in the output, you'll need to use the `ConvertToNative` method like so:

```go
req, err := out.ConvertToNative(reflect.TypeOf(&rpcpb.AttributeContext_Request{}))
```

I'll update the codelab source and instructions to make sure it works properly. Thanks for raising the issue!

-Tristan

**Comment by aabmass** [comment]
Happy to help, and thanks for the quick response!

**Comment by TristonianJones** [comment]
The code has been updated, and the codelab static content is out for review. Thanks for helping others who might have encountered this issue as well!
