### ISSUE TITLE
Poor performance of concatList Value() method

### ISSUE THREAD

**Issue by hzhaop** [cel-expr/cel-go#488]
hi, all,

expression: `data.map(item, item.id)`
input: 
`{"data": [{"id": "1"}, {"id": "2"}, ... , {"id": "1000"}]}`

I call the Value() method of the program.Eval() output, find it very slow to return the value.

I find out that it's because `data.map(item, item.id)` produce a concatList, which is very slow in Value() method. (about O(N^2) complexity)

Is there any workaround method that I could enhance this expression performance?

**Comment by TristonianJones** [comment]
#491 should improve evaluation speed by 40x and ensure that the call to `Value()` is a constant time operation. The combination of the two effects should yield an even more significant performance boost for this use case.
