### ISSUE TITLE
contextEval only checks interrupted for evalFold

### ISSUE THREAD

**Issue by cici37** [cel-expr/cel-go#509]
contextEval only checks interrupted for [evalFold](https://github.com/google/cel-go/blob/505a087e6301f4fb073417e6707c96709eb721a4/interpreter/interpretable.go#L764) which will cause context cancellation fail for any other cases.

**Comment by cici37** [comment]
cc @TristonianJones @jpbetz 
I am not sure if this behavior is intended. It seems only checking interrupted in evalFold would miss tons of cases. Any suggestions on where to check operation interrupted instead of adding it everywhere?

**Comment by TristonianJones** [comment]
@cici37 The `evalFold` is the only instruction that can loop or be nested, so it's the only place where non-linear compute can be introduced into an expression. And even then, the interrupt check is only being considered once every 100 iterations. 

Is there a specific instruction that you'd like to check for interrupts that you think would be problematic?

**Comment by TristonianJones** [comment]
@cici37 @jpbetz The only other one I can think of which might be problematic would be heavy use of non-constant regex matchers. I don't mind checking for an interrupt after a regex. Thoughts?

**Comment by cici37** [comment]
It seems like my understanding of cel context cancellation didn't align with the design earlier. After check https://github.com/google/cel-go/pull/492 and offline sync with @TristonianJones , it makes sense to only check for comprehension loops. Thank you
/close
