### ISSUE TITLE
Missing comma in Hello World codelab page

### ISSUE THREAD

**Issue by kortschak** [cel-expr/cel-go#514]
In https://codelabs.developers.google.com/codelabs/cel-go/#3 the "Parse and check the expression" code chunk has either a missing comma or extra newline depending on your style preference. The codelab code in this repo for the solutions is correct.

On the web codelab page there is this:
```
    // Check the result type is a string.
    if !proto.Equal(checked.ResultType(), decls.String) {
        glog.Exitf(
            "Got %v, wanted %v result type",
            checked.ResultType(), decls.String
        )
    }
```
Note the absent trailing comma after `decls.String`.

Hijacking my own issue: In https://codelabs.developers.google.com/codelabs/cel-go/#11 "Exhaustive Eval", `` falseVars := map[string]interface{}{`"x": int64(6), "y": uint64(2)`} `` should be `` falseVars := map[string]interface{}{"x": int64(6), "y": uint64(2)} ``

**Comment by TristonianJones** [comment]
This should be fixed internally and will be published hopefully within the next day or so.
