### ISSUE TITLE
Compilation latency dominated by addOverload operations when using extension libraries

### ISSUE THREAD

**Issue by jpbetz** [cel-expr/cel-go#519]
Originally found by @DangerOnTheRanger and @liggitt

In Kubernetes we use the same set of libraries for all CEL expressions, but have to pay the cost of registering them into an environment each time a CEL expression is compiled. This appears to dominate the compilation cost.

https://github.com/google/cel-go/blob/ffa9b84b3e4a8c37db126eb23296f16f2cbc4980/cel/env.go#L163

![image](https://user-images.githubusercontent.com/523590/159579035-8025031c-2b8e-4ad5-bf29-bf57600495dd.png)

**Comment by jpbetz** [comment]
cc @TristonianJones @DangerOnTheRanger @liggitt

**Comment by TristonianJones** [comment]
@jpbetz This doesn't surprise me. Why can't you use a statically configured environment?

**Comment by jpbetz** [comment]
> Why can't you use a statically configured environment?

Maybe we can? We vary the variable decls used across the compiled CEL expressions, which is what I think got us hung up here.

I'll have a look at https://github.com/google/cel-go/pull/347 PR that you shared offline with me and see if that can be use to eliminate the bulk of the cost.

**Comment by TristonianJones** [comment]
@jpbetz Take a look at the draft state for #347. I've added some options to early validate declarations and to ensure that validated declarations are copied from one `Env` to the next when the `Env.Extend()` call is used. 

This means that if you do an `init()` of the base environment for K8s you should see a 7-10x performance boost and a dramatic reduction in memory allocations:

```go
func init() {
        // maybe panic if this errors
        baseEnv, _ = cel.NewEnv(
		cel.HomogeneousAggregateLiterals(),
                 library.ExtensionLibs...,
                 cel.EarlyValidateDeclarations(true),
	)
}
```

Then use the `baseEnv.Extend` with the per-compile options you need in your use case.

Before PR:
```
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
BenchmarkNewEnv-8   	     430	   2674244 ns/op	  574888 B/op	   20228 allocs/op
```

After PR:
```
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
BenchmarkNewEnv-8             	     994	   1064345 ns/op	  369540 B/op	   12238 allocs/op
BenchmarkEnvExtend-8          	    7965	    154726 ns/op	   42053 B/op	     661 allocs/op
BenchmarkEnvExtendNoDecls-8   	    9135	    114062 ns/op	   34511 B/op	     401 allocs/op
```

What do you think? If you think this will work, I'll finish up the tests tomorrow and we'll do another release. I'm actually tempted to make a base copy of the stdEnv internal to CEL to speed up the simple extension cases as well.

**Comment by jpbetz** [comment]
Fixed by https://github.com/google/cel-go/pull/347

See https://github.com/kubernetes/kubernetes/pull/108954 for benchmarks.
