### ISSUE TITLE
Missing reference documentation (Godoc)

### ISSUE THREAD

**Issue by broady** [cel-expr/cel-go#54]
Here's a list of important functions and types that don't have documentation, and probably should:

* [`common.Types.NativeToValue`](https://godoc.org/github.com/google/cel-go/common/types#NativeToValue)
* [`packages`](https://godoc.org/github.com/google/cel-go/common/packages) (the whole package, really. what is it for? an example would be good.)
* [`checker.NewStandardEnv`](https://godoc.org/github.com/google/cel-go/checker#NewStandardEnv)
* [`checker.StandardDeclarations`](https://godoc.org/github.com/google/cel-go/checker#StandardDeclarations)
* [`types.NativeToValue`](https://godoc.org/github.com/google/cel-go/common/types#NativeToValue)

**Comment by broady** [comment]
Oh, and in the types package, what is `DynType`? A lot of the others are fairly obvious, but this is all I can find on it:

```
var (
	// DynType singleton.
	DynType = NewTypeValue("dyn")
)

// IsDyn indicates whether the input ref.Value or ref.Type is equal to DynType.
func IsDyn(elem interface{}) bool {
```

**Comment by TristonianJones** [comment]
Thanks for the pointers. We're working on cleaning up the docs and proto usage over the next quarter.

The concept of `dyn` comes from the CEL specification. It's basically a keyword to indicate that a value has dynamic type and is useful during the type-unification logic in the `checker`
