### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by l46kok** [cel-expr/cel-go#553]
- https://codelabs.developers.google.com/codelabs/cel-go/index.html#3

Output should be `interpreter.emptyActivation` instead of `interpreter.mapActivation`:
```
=== Exercise 1: Hello World ===

------ input ------
(interpreter.emptyActivation)

------ result ------
value: Hello, World! (types.String)
```

- https://codelabs.developers.google.com/codelabs/cel-go/index.html#8

call to `cel.Declarations` missing a trailing comma:

```
    env, _ := cel.NewEnv(
      cel.Declarations(
        decls.NewVar("now", decls.Timestamp),
      )**,**
    )
```

- https://codelabs.developers.google.com/codelabs/cel-go/index.html#9

The documentation states midway that we should get an error for undeclared reference to `jwt`:

```
ERROR: <input>:4:16: undeclared reference to 'jwt' (in container 'google.rpc.context.AttributeContext')
 |     principal: jwt.iss + '/' + jwt.sub,
 | ...............^
```

The code sample above this error message already contains the needed declaration, so this error is never encountered. 
(The instruction asks you to specify the container first, run the code and declare the variables afterwards to address the error so perhaps just the sample code needs be moved below, or split into two steps for better clarity)
 
- https://codelabs.developers.google.com/codelabs/cel-go/index.html#10

`Building Protos` section at the bottom is a duplicate from the previous exercise and should be removed here. Looks like the `additional considerations` disclaimer should also be moved to the previous exercise.

**Comment by TristonianJones** [comment]
Fixed upstream
