### ISSUE TITLE
Question: How to use Function() in custom Lib?

### ISSUE THREAD

**Issue by trganda** [cel-expr/cel-go#572]
I'm using the latest version cel-go, and write some code like below, define a `customLib` to add external fuction in cel. It's ok if i use the func [func Functions(funcs ...*functions.Overload) ProgramOption](https://pkg.go.dev/github.com/google/cel-go/cel#Functions)  to add some `ProgramOption` type value to the `c.programOptions`.

However, the editor has prompted that the `cel.Functions()` has been deprecated, use Function() insted. I'm try to use [func Function(name string, opts ...FunctionOpt) EnvOption](https://pkg.go.dev/github.com/google/cel-go/cel#Function) to instead，but it return type `EnvOption`  was no compatible with `ProgramOption` and I have no found other way to convert `EnvOption` to `ProgramOption`.

So, I want to kown it's there any way can reslove this problem.

```go
import (
  "github.com/google/cel-go/cel"
  "github.com/google/cel-go/checker/decls"
  "github.com/google/cel-go/common/types"
  "github.com/google/cel-go/common/types/ref"
)

type CustomLib struct {
  envOptions     []cel.EnvOption
  programOptions []cel.ProgramOption
}

func NewEnvOption() CustomLib {
  c := CustomLib{}
  
  c.envOptions = []cel.EnvOption{
    cel.Container("yamlctx"),
    cel.Declarations(
        // a few custom function
    ),
  }
  
  c.programOptions = []cel.ProgramOption{
    cel.Functions(
        // custom function defination
    ),
  }
```

**Comment by trganda** [comment]
Ignore this stupid question, I have found the solution, put the `cel.Function` in `cel.EnvOption{}` as show in this [example](https://pkg.go.dev/github.com/google/cel-go/cel#example-package-GlobalOverload)

**Comment by TristonianJones** [comment]
@trganda no worries on asking the question. I'm glad you found the answer you were looking for in the examples. :) Hopefully, it makes the creation of libraries a bit easier with less of a need for split configuration between the env and program options.
