### ISSUE TITLE
Support json.Number

### ISSUE THREAD

**Issue by mark-a-johnson** [cel-expr/cel-go#576]
An internal library we are using just decided to decode json with the Number() option that converts numbers to json.Number instead of a float64.  Something like this:

```
	dec := json.NewDecoder(bytes.NewBuffer(data))
	dec.UseNumber()
```
When we use one of these for input to a cel expression we get the error:

unsupported conversion to ref.Val: (json.Number)

Thanks

**Comment by TristonianJones** [comment]
My recommendation would be to provide a custom type adapter, using `cel.CustomTypeAdapter(...)`. 

The implementation could be as simple as this:

```go
type adapter struct {}

func (a *adapter) NativeToValue(value interface{}) ref.Val {
    switch v := value.(type) {
       case json.Number:
         return types.DefaultTypeAdapter.NativeToValue(float64(v))
       default:
         return types.DefaultTypeAdapter.NativeToValue(v)
    }
}
```
