### ISSUE TITLE
The error type is not understood

### ISSUE THREAD

**Issue by PollosD** [cel-expr/cel-go#606]
I tried to use filter to determine whether the string "develop" exists in the ref field, but the error failed to evaluate: got 'types.String', expected iterable type, I don't understand what this means, my expression is as follows: body.ref .exists(r, r.name == 'refs/heads/develop'), where body.ref is the information returned by the webhook

**Comment by TristonianJones** [comment]
@PollosD from the error, it seems as though `body.ref` is of type `string` at runtime rather than a list or map (iterable type). Perhaps there's an issue with how the the `body.ref` is constructed or declared? It's hard to say without knowing more about the context.
