### ISSUE TITLE
Using ext.NativeTypes prevents deserialisation of result when an array of byte string

### ISSUE THREAD

**Issue by kortschak** [cel-expr/cel-go#614]
**Describe the bug**

When the `ext.NativeTypes` extension is used, arrays of byte strings fail to be convertable.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter (?)

Sample expression and input that reproduces the issue:
```cel
[b'byte string']
```

Test setup:
```go
package main

import (
	"fmt"
	"reflect"

	"github.com/google/cel-go/cel"
	"github.com/google/cel-go/ext"
	"github.com/google/cel-go/interpreter"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/structpb"
)

func main() {
	const src = `[b'byte string']`

	fmt.Println(run(src))
	fmt.Println(run(src, ext.NativeTypes()))
	fmt.Println(run(src, ext.NativeTypes(reflect.TypeOf(&Native{}))))
}

type Native struct {
	ID int8
}

func run(src string, opts ...cel.EnvOption) (string, error) {
	env, err := cel.NewEnv(opts...)
	if err != nil {
		return "", fmt.Errorf("failed to create env: %v", err)
	}

	ast, iss := env.Compile(src)
	if iss.Err() != nil {
		return "", fmt.Errorf("failed compilation: %v", iss.Err())
	}

	prg, err := env.Program(ast)
	if err != nil {
		return "", fmt.Errorf("failed program instantiation: %v", err)
	}

	out, _, err := prg.Eval(interpreter.EmptyActivation())
	if err != nil {
		return "", fmt.Errorf("failed eval: %v", err)
	}

	v, err := out.ConvertToNative(reflect.TypeOf(&structpb.Value{}))
	if err != nil {
		return "", fmt.Errorf("failed proto conversion: %v", err)
	}
	b, err := protojson.MarshalOptions{Indent: "\t"}.Marshal(v.(proto.Message))
	if err != nil {
		return "", fmt.Errorf("failed native conversion: %v", err)
	}
	return string(b), nil
}
```

https://go.dev/play/p/ZnwBQwexvVR

**Expected behavior**

I expect three instances of the following to be printed.
```
[
	"Ynl0ZSBzdHJpbmc="
] <nil>
```
 Instead, I see
```
[
	"Ynl0ZSBzdHJpbmc="
] <nil>
 failed proto conversion: unsupported conversion to ref.Val: (uint8)98
 failed proto conversion: unsupported conversion to ref.Val: (uint8)98
```

If the expression is `['byte string']` the program behaves as expected, emitting three copies of
```
[
	"byte string"
] <nil>
```

**Additional context**

This may be due to changes that I need to make in the serialisation as I come out of the cel execution. If so, this is a question rather than a bug; what do I need to do with the code above to make the change work?

**Comment by TristonianJones** [comment]
@kortschak Thanks for the repro. I hadn't anticipated someone trying to convert between a JSON value and a native type. If that's what you're looking for then I believe I would need to update the `native.go` `ConvertToNative` method to support those conversions.

**Comment by kortschak** [comment]
Thanks @TristonianJones. That would be great.

For background the project that makes use of this is https://github.com/elastic/mito where I want to be able to use native structs in place of map for some of the subterfuge in https://github.com/elastic/mito/blob/dev/lib/http.go. This is all being used in https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-cel.html where the CEL result is serialised to publish to Elasticsearch.

The initial find was in https://github.com/elastic/mito/blob/2f0f2875e464616f5406d3ccdd7510e4ddc2ef21/testdata/regexp.txt#L14 when I added native types into the environment; `find` returns a byte string when the input is byte string.

**Comment by TristonianJones** [comment]
@kortschak It's probably better to use the Golang serialization for JSON values assuming you're using go `struct` types as the top-level values in expressions. 

I've added support for serialization to protobuf JSON values, but you may find the formatting will not be idiomatic to the sort of data you'd expect when converting between JSON and struct values.

**Comment by kortschak** [comment]
@TristonianJones The top level values in inputs are `map[string]any` and this is what we take from the final output to send to ES. The Go structs that I want to use for the subterfuge in the HTTP extension are currently implemented as `map[string]any`. These are used to hold http request and response values between parts of an evaluation. If I can avoid the protobuf-mediated serialisation and go directly through a `map[string]any`, that should work for us.

**Comment by kortschak** [comment]
This shows the structure of the flows that involve the HTTP extension.

```mermaid
sequenceDiagram
    participant input
    participant cel prepare request
    participant cel do request
    participant cel prepare response
    participant output
    input-->>output: process flow
    input-->>cel prepare request: `map[string]any`
    cel prepare request->>cel do request: Go struct to reflect `http.Request` (currently using `map[string]any`)
    cel do request->>cel prepare response: Go struct to reflect `http.Response` (currently using `map[string]any`)
    cel prepare response-->>output: `map[string]any`
```
