### ISSUE TITLE
No way to check for existence of dictionary key that isn't expressible as `[a-zA-Z][a-zA-Z0-9_]*`

### ISSUE THREAD

**Issue by achew22** [cel-expr/cel-go#618]
**Describe the bug**

There doesn't appear to be a syntax for checking the existence of a key in a dictionary if the key contains characters that are disallowed in field names. For example `"foo/bar"`.

I have reviewed the documentation from the [language spec](https://github.com/google/cel-spec/blob/master/doc/langdef.md#field-selection) and it seems you're supposed to be able to invoke via:

```
has(foo.x)
```

to check the existence of `x` on the `foo` object. I infer from that example that a user would use the standard access pattern and that the interpreter would handle the conversion for you. That is to say that if `foo.x` is a `map[string]string` you would like to check for key existence, you might try:

```
has(foo.x["bar"])
``` 

**To Reproduce**
Check which components this affects:

I think it's the interpreter, but I'm not entirely sure. Sorry!

- [ ]  parser
- [ ]  checker
- [X]  interpreter

Sample expression and input that reproduces the issue:
```cel
// sample expression string
```

Test setup:

Add a test case to `interpreter/interpreter_test.go`:

```go
    { // N.B. this one passes already, so the setup is sane-ish
      name:      "has_able_to_detect_maps_with_complex_keys_success",
      container: "google.expr.proto3.test",
      types:     []proto.Message{&proto3pb.TestAllTypes{}},
      expr: `has(TestAllTypes{
        map_string_string: {
          'hello': 'world',
        },
      }.map_string_string.hello)`,
      out: types.True,
    },
    {
/* This testcase fails with: 
    interpreter_test.go:1579: has_able_to_detect_maps_with_complex_keys_attempt_1: ERROR: <input>:1:4: invalid argument to has() macro
         | has(TestAllTypes{
         | ...^
*/
      name:      "has_able_to_detect_maps_with_complex_keys_attempt_1",
      container: "google.expr.proto3.test",
      types:     []proto.Message{&proto3pb.TestAllTypes{}},
      expr: `has(TestAllTypes{
        map_string_string: {
          'hello/world': 'moo',
        },
      }.map_string_string["hello/world"])`,
    },
    {
/* This testcase fails with: 
    interpreter_test.go:1585: has_able_to_detect_maps_with_complex_keys_attempt_2: ERROR: <input>:1:4: invalid argument to has() macro
         | has(TestAllTypes{
         | ...^
*/
      name:      "has_able_to_detect_maps_with_complex_keys_attempt_2",
      container: "google.expr.proto3.test",
      types:     []proto.Message{&proto3pb.TestAllTypes{}},
      expr: `has(TestAllTypes{
        map_string_string: {
          'hello/world': 'moo',
        },
      }.map_string_string.hello/world)`,
    },
```

**Expected behavior**

A function for checking the existence of a map key.

**Additional context**

I think this is possibly solvable by creating my own macro that takes an dict (`map[string]any`) and a `key` (in this case `string`) and returns an `any` iff the key exists, otherwise returns a default value. Is there a better way to approach this without extending the language with my own macro?

**Comment by jnthntatum** [comment]
I think this is working as intended -- has should only work for struct field-like keys.

Could you use the `in` operator or do you need this to work for both maps and structs?
`'hello/moo' in { 'hello/moo': 'world',}` -> true

We've talked internally about adding an escape syntax for similar cases (e.g.  ``has(var.map_string_string.`hello/moo`)``, but I don't think we've settled on anything.

We're also working on adding an optional type with a new accessor syntax (see https://github.com/google/cel-spec/wiki/proposal-246#cel---optional-values). Implementation is in progress, but should be available soon -- might be helpful if you need to chain the presence checks `var.?map_string_string[?'hello/moo'] -> 'world' : optional(string)`
