### ISSUE TITLE
Best way to lazily evaluate json

### ISSUE THREAD

**Issue by newhook** [cel-expr/cel-go#633]
I'm looking for the best way to avoid unmarshaling my json to a `map[string]interface{}`, which can be quite expensive for a large JSON structure. 

I've looked at the examples given here https://groups.google.com/g/cel-go-discuss/c/FJCp4A3Fd2M, but am having trouble determining the best course of action here.

I also tried something like this:
```
func lazyMap(attributes []byte) map[string]any {
  // look through attributes to see what is present, etc.
  m := map[string]any{}
  m["abc"] = func ref.Val ( ...)
  m["def"] = func ref.Val ( ...)   
  return m
}
...
   env, err := cel.NewEnv(
		cel.Declarations(
			decls.NewIdent("attributes",
				decls.NewMapType(
					decls.String,
					decls.Dyn,
				), nil)),
	)
out, _, err := prg.Eval(map[string]interface{}{
				"attributes": lazyMap(attributes),
			})
```

But this doesn't work.

Is there an example I could look at to see how that might be done?

**Comment by TristonianJones** [comment]
There isn't direct support for lazily evaluated fields of an input object, just lazily evaluated top-level variables:

```go
func lazyMap(attributes []byte) func() any {
  return map[string]any{
    "abc": ...,
    "def": ...,
  }
}

prg.Eval(map[string]any{"attribute": lazyMap(attributes)})
```

If you want lazily evaluated fields, you could introduce a new `ref.Val` implementation that that allows you to intercept the lookup on the field and deserialize (or create a view reference, etc.)  the field value on calls to `Get`. I think you would want to implement the `traits.Indexer` if you want something like this. You can still declare the type as a `map(string, dyn)`, but the object you access at runtime can be a custom value type.
