### ISSUE TITLE
Consider migrating to "github.com/antlr/antlr4/runtime/Go/antlr/v4"?

### ISSUE THREAD

**Issue by Rick-xuy** [cel-expr/cel-go#644]
It seems that `v1` module of `github.com/antlr/antlr4/runtime/Go/antlr` has been deprecated. <br>
<https://github.com/antlr/antlr4/blob/master/runtime/Go/antlr/go.mod>
```
// Deprecated: Please switch to the new v4 module path: github.com/antlr/antlr4/runtime/Go/antlr/v4 - see https://github.com/antlr/antlr4/blob/master/doc/go-target.md
module github.com/antlr/antlr4/runtime/Go/antlr
```
The new module is `github.com/antlr/antlr4/runtime/Go/antlr/v4` and it fits more properly with the idiomatic ways of Go than `v1` module. <br>
Is there any plan to migrate to `github.com/antlr/antlr4/runtime/Go/antlr/v4`?

**Comment by TristonianJones** [comment]
This is a good point. We were waiting on some internal migrations to happen before made the update, but now I expect it can happen any time.

**Comment by Rick-xuy** [comment]
Ok, I see. Thanks for your reply! Hope the migration process goes smoothly.
