### ISSUE TITLE
define Overload with cel.UintType, got "found no matching overload for 'getUintValue' applied to '(string, int)'"

### ISSUE THREAD

**Issue by MichaelDiao** [cel-expr/cel-go#648]
**Describe the bug**
When learning cel-go and writing a demo, I created a NewEnv, like:
```
type Big struct {
	Str string
	Num int32

	Obj Obj
}
type Obj struct {
	Str  string
	Num  int16
	Size uint16
}
big := &Big{
	Str: "heloo",
	Num: int32(5),
	Obj: Obj{
		Num:  int16(5),
		Str:  "obj heloo",
		Size: 66,
	},
}

env, err := cel.NewEnv(
        cel.Function("getUintValue",
	   cel.Overload("getUintValue_string_uint",
		[]*cel.Type{cel.StringType, cel.UintType},
		cel.UintType,
		cel.BinaryBinding(func(name, index ref.Val) ref.Val {
			n := name.Value().(string)
			fmt.Println("type:", index.Type())
			idx, ok := index.Value().(uint64)
			fmt.Printf("idx: %v, ok: %v", idx, ok)
			return types.DefaultTypeAdapter.NativeToValue(nil)
		},
		),
	),
))
ast, e2 := env.Compile("getUintValue('big.Obj.Size', 0)")
fmt.Println(e2)
```

Then run it,  "env.Compile" would failed with "found no matching overload for 'getUintValue' applied to '(string, int)'".  It be actually set to "cel.UintType" in cel.Overload function, Why do I still got no matching error?  

In other words, how do I write rule to expression uint type? Please help me figure it out.

**Comment by TristonianJones** [comment]
@MichaelDiao It looks like you're providing an `int` literal in the function call `0`. To ensure type agreement, use a uint literal `0u`. Hopefully, that helps.

-Tristan
