### ISSUE TITLE
has() and hyphenated keys

### ISSUE THREAD

**Issue by patt1s0n** [cel-expr/cel-go#654]
**Describe the bug**
I have keys in data which are hyphenated. I can access these keys by doing `data['a-key']` however when I try to check if they exist with `has()` I get an error. 

```
failed to parse: ERROR: <input>:1:4: invalid argument to has() macro
         | has(data['a-key'])
         | ...^
```

**To Reproduce**
```
func TestCel(t *testing.T) {
	env, err := cel.NewEnv(cel.Variable("data", cel.MapType(cel.StringType, cel.DynType)))
	if err != nil {
		t.Fatalf("failed to create env: %v", err)
	}

	_, iss := env.Parse(`has(data['a-key'])`)
	if iss != nil && iss.Err() != nil {
		t.Fatalf("failed to parse: %v", iss.Err())
	}
}
```

Check which components this affects:

- [X]  parser
- [ ]  checker
- [ ]  interpreter

Sample expression and input that reproduces the issue:
```cel
has(data['a-key'])
```

Test setup:
```go
func TestCel(t *testing.T) {
	env, err := cel.NewEnv(cel.Variable("data", cel.MapType(cel.StringType, cel.DynType)))
	if err != nil {
		t.Fatalf("failed to create env: %v", err)
	}

	_, iss := env.Parse(`has(data['a-key'])`)
	if iss != nil && iss.Err() != nil {
		t.Fatalf("failed to parse: %v", iss.Err())
	}
}
```

**Expected behavior**
I expect to be able to check if hyphenated keys exist or not.

**Comment by TristonianJones** [comment]
Sorry for the confusion, but only identifier characters are supported with `has` per the cel-spec; however, the `in` operator works well for presence testing of complex keys in maps: `'a-key' in data`.

**Comment by patt1s0n** [comment]
Ahh thank you.
