### ISSUE TITLE
string.format() cannot be used as intended with HomogeneousAggregateLiterals

### ISSUE THREAD

**Issue by jpbetz** [cel-expr/cel-go#655]
We encountered this with Kubernetes, where we have `HomogeneousAggregateLiterals` enabled.

`string.format()` takes a list of values to interpolate in a formatted string, e.g. `"%s - %d".format(['a', 1])`.

When `HomogeneousAggregateLiterals` is enabled, CEL enforces that the items of a literal list be the same type.

The result is that expressions like `"%s - %d".format(['a', 1])` are not allowed when `HomogeneousAggregateLiterals` is enabled.

**Comment by jpbetz** [comment]
Workarounds like `"%s - %d".format([string('a'), string(1)])` or `"%s - %d".format([dyn('a'), dyn(1)])`, exist, but are messy and I don't recommend them.

**Comment by TristonianJones** [comment]
Thank you, Joe.

**Comment by jpbetz** [comment]
Some short term questions:

- Should we temporarily take `string.format()` out of the strings extension library until we have a plan? Would doing this help keep our design options open? (or has that ship sailed)
- Any next steps we should explore?

**Comment by TristonianJones** [comment]
I don't think taking `string.format()` out really changes anything. In terms of design, even if you were to use a variadic argument macro (not recommended), it would generate a mixed type list under the covers and suffer the same issue. 

As a next step, I would like to shift the `HomogeneousAggregateLiteral` option and the `string.format()` argument checking into something more general purpose that can be run post type-check and still provide the same feedback and levels of correctness so we can address issues #359, #420, and #496 more effectively. By making it possible to introduce these individual checks, it should also allow for some customization of when mixed type list / map literals are permitted.
