### ISSUE TITLE
REPL: Output format change for list(string)

### ISSUE THREAD

**Issue by l46kok** [cel-expr/cel-go#656]
**Describe the bug**
In REPL, it's currently not possible to distinguish whether an outputted list of strings are multiple elements in a list or the string itself contains a space:

```
cel-repl> ["Hello World"]
[Hello World] : list(string)
cel-repl> ["Hello","World"]
[Hello World] : list(string)
```

**Expected behavior**

We could simply wrap the elements of string type with quotes and optionally use comma as a separator:

```
cel-repl> ["Hello World"]
["Hello World"] : list(string)
cel-repl> ["Hello","World"]
["Hello", "World"] : list(string)
```

**Comment by TristonianJones** [comment]
@l46kok if you want to update the `Stringer` implementation for list and map types, this would probably be worthwhile and address the issue you're seeing in the repl.
