### ISSUE TITLE
Rename com_github_antlr_antlr4_runtime_go_antlr to com_github_antlr_antlr4_runtime_go_antlr_v4

### ISSUE THREAD

**Issue by satreix** [cel-expr/cel-go#680]
**Describe the bug**

Recent version of gazelle map "github.com/antlr/antlr4/runtime/Go/antlr/v4" to "com_github_antlr_antlr4_runtime_go_antlr_v4" and not "com_github_antlr_antlr4_runtime_go_antlr".

This causes the following error for projects that import cel-go with bazel and gazelle:

> ERROR: external/com_github_google_cel_go/parser/BUILD.bazel:7:11: no such package '@com_github_antlr_antlr4_runtime_go_antlr//': The repository '@com_github_antlr_antlr4_runtime_go_antlr' could not be resolved: Repository '@com_github_antlr_antlr4_runtime_go_antlr' is not defined and referenced by '@com_github_google_cel_go//parser:go_default_library

**To Reproduce**

Use a recent version of go/bazel/gazelle and depend on cel-go v0.14. This is done in https://github.com/satreix/everest/pull/466 (you do need to drop the patch introduced in the PR for the issue to trigger).
 
**Expected behavior**

Gazelle should not be tripped by the naming of com_github_antlr_antlr4_runtime_go_antlr in this repo.

**Additional context**
IIUC this was introduced with https://github.com/google/cel-go/issues/644

**Comment by TristonianJones** [comment]
Thank you, @satreix. I'll make to bump the `WORKSPACE` naming and associated bzl files and create a point release mid-week
