### ISSUE TITLE
FR: Use rules_antlr

### ISSUE THREAD

**Issue by satreix** [cel-expr/cel-go#681]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [ ] The change is large enough it can't be addressed with a simple Pull Request
    - no, this can fit in a single PR
- [ ] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).
    - this is not a bug

**Change**

Could we use https://github.com/marcohu/rules_antlr to encapsulate antlr (parser/gen/generate.sh) in Bazel.

This relates to https://github.com/google/cel-go/pull/533 by not storing the antlr code in-tree, while still making is simpler and more automated than (read a comment) to generate the code.

This could also use some variation of [write_source_files](https://github.com/aspect-build/bazel-lib/blob/main/docs/write_source_files.md) to generate the in-tree go code and provide a freshness check in CI.

**Comment by Clement-Jean** [comment]
I was checking the rules_antlr repo and it looks like it's not maintained anymore. Furthermore, it doesn't support newer version of ANTLR.

Anyway, I'm interested in hearing about what you decide here. I need that rule for my CEL implementation (C#) too.

**Comment by TristonianJones** [comment]
I don't think we can support this build dependency since it would complicate support for newer ANTLR versions. That said, there seem to be issues with supporting newer ANTLR versions in general as a recent attempt to update #724 seems to have surfaced some data race issues in the Golang rewrite.
