### ISSUE TITLE
Protobuf type with `nil` value in list or map

### ISSUE THREAD

**Issue by tonyli233** [cel-expr/cel-go#687]
**Describe the bug**
When using a protobuf message type as the element type of a list or the value type of a map, `nil` values seems to become something that is not `nil`
**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [√]  interpreter

Test setup:
```go
tests := []struct {
		name     string
		expr     string
		x        any
		xType    *cel.Type
		expected any
	}{
		{
			name:     "null bar",
			expr:     "x == null",
			x:        nil,
			xType:    cel.ObjectType("foo.Bar"),
			expected: true,
		},
		{
			name:     "null in map",
			expr:     "x[1] == null",
			x:        map[int]*foo.Bar{1: nil},
			xType:    cel.MapType(cel.IntType, cel.ObjectType("foo.Bar")),
			expected: true,
		}, {
			name:     "null in list",
			expr:     "x[0] == null",
			x:        []*foo.Bar{nil},
			xType:    cel.ListType(cel.ObjectType("foo.Bar")),
			expected: true,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			env, err := cel.NewEnv(
				cel.Types(&foo.Bar{}),
				cel.Variable("x", test.xType),
			)
			require.NoError(t, err)
			ast, issues := env.Compile(test.expr)
			require.NoError(t, issues.Err())

			prog, err := env.Program(ast)
			require.NoError(t, err)
			val, _, err := prog.Eval(map[string]any{"x": test.x})
			require.NoError(t, err)
			require.Equal(t, test.expected, val.Value())
		})
	}
```

Test output:
```
=== RUN   TestNull
=== RUN   TestNull/null_bar
=== RUN   TestNull/null_in_map
    validate_test.go:111: 
        	Error Trace:	validate_test.go:111
        	Error:      	Not equal: 
        	            	expected: true
        	            	actual  : false
        	Test:       	TestNull/null_in_map
=== RUN   TestNull/null_in_list
    validate_test.go:111: 
        	Error Trace:	validate_test.go:111
        	Error:      	Not equal: 
        	            	expected: true
        	            	actual  : false
        	Test:       	TestNull/null_in_list

```

**Expected behavior**
Protobuf type in map or list with `nil` value should reserve the `nil` value.

**Comment by TristonianJones** [comment]
@tonyli233 I'm a little torn on this one because in a list of nil valued protos, the elements will look the same as the default instance of the message type which is what the list/map access returns.

I'm tempted to say this is working as intended, but I'll have to think about it more.

-Tristan

**Comment by tonyli233** [comment]
@TristonianJones Thanks for your quick response. I think it might be more useful if proto types can also be nullable in lists and maps. Anyways we have some workarounds to avoid using expressions like these in our use case. 😀

**Comment by TristonianJones** [comment]
@tonyli233 Depending on the proto implementation, it's possible for a `nil` value to be equivalent to a default protobuf message instance, so I'm not sure this should change. If you want an optionally populated protobuf value, then `list(optional(T))` or `map(string, optional(T))` are probably better choices since the behavior is clearer.

**Comment by tonyli233** [comment]
Thank you Tristan! I'll look into that.
