### ISSUE TITLE
Unexpected behavior: string.join relies on ConvertToNative returning a []string

### ISSUE THREAD

**Issue by jpbetz** [cel-expr/cel-go#688]
**Describe the bug**

In k8s we encountered https://github.com/kubernetes/kubernetes/issues/117590.

We had [expected](https://github.com/kubernetes/kubernetes/blob/1d116c437c2ad531a36bd9aabef165f5efa0f0e9/staging/src/k8s.io/apiserver/pkg/cel/common/values.go#L425-L431) that if `ConvertToNative` is asked for a `reflect.Type` of `Slice` that `[]interface{}` would be an appropriate return type, although the godoc doesn't spell this out:

https://github.com/google/cel-go/blob/377a0bba20d07926e0583b4e604509ca7f3583b7/common/types/ref/reference.go#L38-L40

**To Reproduce**

https://github.com/kubernetes/kubernetes/issues/117590 provides a reproduction.

**Expected behavior**

- `ConvertToNative()` expects `[]interface{}` not `[]string`, or that `ConvertToNative()` defines more clearly the expected behavior in the godoc.
- `string.join()` does not rely on `ConvertToNative()` and instead operates on `ref.Val`.

**Additional context**

I'll put a workaround in k8s.  I'm open to discussion on what the right way to fix this is.  It would be great if we can establish clear rules on:

- What exactly `ConvertToNative` is expected to return in all cases
- If functions should be call `ConvertToNative()`

**Comment by jpbetz** [comment]
@TristonianJones curious on your thoughts about correct behavior here.

**Comment by TristonianJones** [comment]
@jpbetz I think the docs need to be updated. The `ConvertToNative` method is easily one of the most complicated methods to implement consistently across types. 

I think you raise an interesting point. Given the complexity, should extension implementers be able to call the function? It appears that `strings.join` is the only function that does this within the CEL codebase. If we were to shift, it would likely require a `traits.Iterable` whose elements were all of type `types.String`. Changing the code might break some users though. I'll have to come up with a new versioned implementation that makes the shift to iterating over a list of string values in terms of `ref.Val` and update the comment.

In your usage, are you expecting the arguments to be `types.String` or convertible to `types.String`?

**Comment by jpbetz** [comment]
> I think the docs need to be updated. The `ConvertToNative` method is easily one of the most complicated methods to implement consistently across types.

I completely agree. This was my big take away from finding this bug.  If we know more about the expected behavior we try to fix our implementation to match.  I suspect we have an implementation that is significantly out of spec.

> I think you raise an interesting point. Given the complexity, should extension implementers be able to call the function? It appears that `strings.join` is the only function that does this within the CEL codebase. If we were to shift, it would likely require a `traits.Iterable` whose elements were all of type `types.String`. Changing the code might break some users though. I'll have to come up with a new versioned implementation that makes the shift to iterating over a list of string values in terms of `ref.Val` and update the comment.

Right, I had noticed that `string.join` was the only function calling into `ConvertToNative`. 

FWIW, I'm far more confident that we have faithful implementation of the traits and ref.Val than I am about `ConvertToNative`.  So while I am interested in making `ConvertToNative` compliant, I also see value in a convention where all implementers work against ref.Val and the traits.  It seems cleaner to me this way.

> 
> In your usage, are you expecting the arguments to be `types.String` or convertible to `types.String`?

Yes, we expect our arguments to be of type string.  And we do have a [workaround](https://github.com/kubernetes/kubernetes/pull/117593/files#diff-b82fcb39e4dae72bd0cfdb4a7a021a286454cbe0e3880460074faf29476cf04dR432-R444) that will sustain us for the short term.

I would probably prioritize our needs as:

1. Declare the `ConvertToNative` interface more clearly so k8s can fix our implementation. (important soon-ish)
2. Agree on if `ConvertToNative` should be used in future library implementation or not. (important long term)
3. Decide what to do for `string.join` and implement (important long term)

Thanks!
