### ISSUE TITLE
OptCheckStringFormat causes Program to fail generation if format argument has field access

### ISSUE THREAD

**Issue by rodaine** [cel-expr/cel-go#690]
**Describe the bug**

With `ext.Strings`, setting the `OptCheckStringFormat` option when generating the `Program` fails if the argument to the format string refers to a field on a message.

**To Reproduce**

- [x]  parser
- [x]  checker
- [ ]  interpreter

Test setup:
```go
func Test(t *testing.T) {
	// message Msg {
	//   double fld = 1;
	// }
	msg := &Msg{Fld: 1.23}

	expr := "'%s'.format([msg.fld])"

	env, err := cel.NewEnv(
		ext.Strings(),
		cel.Types(msg),
		cel.Variable("msg",
			cel.ObjectType(string(msg.ProtoReflect().Descriptor().FullName()))),
	)
	require.NoError(t, err)

	ast, issues := env.Compile(expr)
	require.NoError(t, issues.Err())

	prog, err := env.Program(ast, cel.EvalOptions(
		cel.OptOptimize,
		cel.OptCheckStringFormat,
	))
	require.NoError(t, err)

	val, _, err := prog.Eval(map[string]any{"msg": msg})
	require.NoError(t, err)
	t.Logf("%#v", val)
}
```

**Actual behavior**

```
=== RUN   Test
    validator_test.go:59: 
        	Error:      	Received unexpected error:
        	            	error during formatting: string clause can only be used on strings, bools, bytes, ints, doubles, maps, lists, types, durations, and timestamps
--- FAIL: Test (0.00s)
```

**Expected behavior**

`"1.23"`

**Additional context**

Test passes with either modification:

- Remove `cel.OptCheckStringFormat`
- Replace `msg` type with `cel.DynType`

**Comment by TristonianJones** [comment]
@rodaine I'm not actually able to repro the error. I am curious though whether disabling `cel.OptOptimize` has any effect as I notice that the tests don't check this case.

**Comment by rodaine** [comment]
Removing just `cel.OptOptimize` from the above still fails with the same error. I think the above case is passing for you because the variable type is being [set to `Dyn`](https://github.com/google/cel-go/blob/9ee247994eb75df094b51a50049936db8e832e81/ext/strings_test.go#LL1226C1-L1226C1). If you make it the explicit type of the message, you should see the same error.

**Comment by TristonianJones** [comment]
@rodaine Thank you, that was the piece I missed. My PR now reflects the fix and test case.
