### ISSUE TITLE
Data race when calling Env.Compile and Env.Extend concurrently.

### ISSUE THREAD

**Issue by rodaine** [cel-expr/cel-go#698]
**Describe the bug**

The checker is not initialized when calling `NewEnv`, being setup only once `Check` is first called.  However, if a newly instantiated `Env` is extended concurrently to making this check, a (benign) data race occurs accessing `Env.chk`.

**To Reproduce**

This race is pretty flaky. I've only triggered this in CI through a couple of unrelated (and significantly more complex) tests, however I cannot reproduce it locally. Theoretically, the following test case should produce the race:

```go
func TestDataRace(t *testing.T) {
	env, err := cel.NewEnv()
	require.NoError(t, err)

	wg := &sync.WaitGroup{}
	wg.Add(2)
	go func() {
		defer wg.Done()
		_, _ = env.Compile("true")
	}()

	go func() {
		defer wg.Done()
		_, _ = env.Extend(cel.Variable("bar", cel.BoolType))
	}()

	wg.Wait()
}
```

**Expected behavior**
No race.

**Actual behavior**
From CI:

```
WARNING: DATA RACE
Write at 0x00c000122188 by goroutine 25:
  github.com/google/cel-go/cel.(*Env).initChecker.func1()
      /home/runner/go/pkg/mod/github.com/google/cel-go@v0.15.0/cel/env.go:556 +0x650
  sync.(*Once).doSlow()
      /opt/hostedtoolcache/go/1.19.9/x64/src/sync/once.go:74 +0x101
  sync.(*Once).Do()
      /opt/hostedtoolcache/go/1.19.9/x64/src/sync/once.go:65 +0x46
  github.com/google/cel-go/cel.(*Env).initChecker()
      /home/runner/go/pkg/mod/github.com/google/cel-go@v0.15.0/cel/env.go:522 +0x58
  github.com/google/cel-go/cel.(*Env).Check()
      /home/runner/go/pkg/mod/github.com/google/cel-go@v0.15.0/cel/env.go:181 +0xc4
  github.com/google/cel-go/cel.(*Env).CompileSource()
      /home/runner/go/pkg/mod/github.com/google/cel-go@v0.15.0/cel/env.go:227 +0x6a
  github.com/google/cel-go/cel.(*Env).Compile()
      /home/runner/go/pkg/mod/github.com/google/cel-go@v0.15.0/cel/env.go:211 +0x57
  <snip>

Previous read at 0x00c000122188 by goroutine 23:
  github.com/google/cel-go/cel.(*Env).Extend()
      /home/runner/go/pkg/mod/github.com/google/cel-go@v0.15.0/cel/env.go:257 +0x1b6
  <snip>
```

**Additional context**
FWICT, the race happens when `Extend` checks if the type checker is not nil [here](https://github.com/google/cel-go/blob/0e0af4afbd072b0fe9d1b7c8d17ab259f9b119a4/cel/env.go#L257). Hypothetically, `initChecker` can still be in-flight performing the write [here](https://github.com/google/cel-go/blob/0e0af4afbd072b0fe9d1b7c8d17ab259f9b119a4/cel/env.go#L556). This is likely true for `chkErr` as well. Current work around is to call `Check` before using the `Env` concurrently.

**Comment by rodaine** [comment]
Also, just want to add that using CEL and this library has been a blast. Thanks for the hard work! 😁

**Comment by TristonianJones** [comment]
I could see how this might happen, but definitely hadn't anticipated that someone would attempt to both compile and extend concurrently. I'll give it a look. Thanks for the quality bug reports!

**Comment by TristonianJones** [comment]
You can also use the option `cel.EagerlyValidateDeclaration()` which should also solve the race condition. I'm adding a mutex around the internal checker state, but thought I would highlight your options.
