### ISSUE TITLE
ERROR: found no matching overload for '_*_' applied to '(double, int)'

### ISSUE THREAD

**Issue by carmel** [cel-expr/cel-go#706]
```sh
ERROR: <input>:1:40: found no matching overload for '_*_' applied to '(double, int)'
 | e=='1'?(a+b*c):(e=='2'?(0.3*a+b*c):(0.7*a+b*c))
 | .......................................^
```

Hey, the variables `a`,`b`,`c` are int types.  The int type multiplied by the double type shouldn't have such an error, should it?

**Comment by TristonianJones** [comment]
CEL doesn't do any type-coercion, so you would need to convert the int to a double manually:

```sh
e=='1'?(a+b*c):(e=='2'?(0.3*double(a+b*c)):(0.7*double(a+b*c)))
```

Type coercion can be a source of subtle bugs, so the ask is that users make these conversions explicit.
