### ISSUE TITLE
Benchmark of some representative CEL matchConditions

### ISSUE THREAD

**Issue by ritazh** [cel-expr/cel-go#729]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [x] The change is large enough it can't be addressed with a simple Pull Request
- [x] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**

Benchmark the cost (time/memory/allocs) of some representative CEL matchConditions
e.g. for k8s:
- scoping to a particular namespace
- scoping to a particular group/resource
- excluding a particular set of users
- excluding a particular set of groups

**Example**

**Alternatives considered**

cc @jpbetz @maxsmythe

**Comment by jpbetz** [comment]
@TristonianJones Are the cel-go benchmarks or performance datasets available (or that could be made available) to the community?

**Comment by TristonianJones** [comment]
The `interpreter/interpreter_test.go` benchmarks are runnable by anyone. We haven't published the numbers anywhere, though we could. 

@ritazh is this a request for benchmarks with CEL in K8s or benchmarks of CEL in general?

**Comment by ritazh** [comment]
> @ritazh is this a request for benchmarks with CEL in K8s or benchmarks of CEL in general?

This would be for benchmarks with CEL in k8s

**Comment by jpbetz** [comment]
> > Rita Zhang is this a request for benchmarks with CEL in K8s or benchmarks of CEL in general?
> 
> This would be for benchmarks with CEL in k8s

time/allocs can be done with standard go micro benchmarks in k8s, e.g.: https://github.com/kubernetes/kubernetes/blob/5f598179d8362ce9683ab1b87b7591007464cdbd/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go#L2610

**Comment by TristonianJones** [comment]
@ritazh @jpbetz Would it be worthwhile to create a set of benchmark expressions which could be included in both the k8s and CEL repos? This way you could get a sense of raw cost and cost within the context of k8s or some other integration.

**Comment by jpbetz** [comment]
> Would it be worthwhile to create a set of benchmark expressions which could be included in both the k8s and CEL repos? This way you could get a sense of raw cost and cost within the context of k8s or some other integration.

A benchmark suite of expressions would be amazing.  I'm imagining maybe 10-50 distinct expressions that cover the breadth of CEL features. Once we have the expressions, we could run a variety of comparisons.  I'd really like to see what the overhead is for k8s CEL expressions (given our ref.Val wrapper layers and cost tracking) vs. a baseline.

EDIT: If would be fine with me if protos or json are used the default input for variables in the benchmark suite. We could create equivalent types on the k8s side to substitute in when we benchmark our use of CEL.

**Comment by TristonianJones** [comment]
I'll look into creating a benchmark harness after I finish working on the PRs for #493 and #568.

**Comment by TristonianJones** [comment]
@ritazh @jpbetz I've put together #750 with some simple standalone expressions. None of the expressions are Kubernetes specific, but you could run the reference examples against the Kubernetes CEL environment, and also define your own benchmark cases which we could port into the canonical cases.
