### ISSUE TITLE
Issues with field selection from proto messages

### ISSUE THREAD

**Issue by adityasaky** [cel-expr/cel-go#758]
**Describe the bug**

Field selection fails with "undefined field" in a CEL `Env` created from proto messages. The issue _may_ be because of a camel-case / snake-case mismatch.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [x]  checker
- [x]  interpreter

Sample expression and input that reproduces the issue:
```cel
buildDefinition.buildType == 'https://slsa-framework.github.io/github-actions-buildtypes/workflow/v1'
```

Test setup:
```go
import provenancePredicatev1 "github.com/in-toto/attestation/go/predicates/provenance/v1"
...

env, _ := cel.NewEnv(
	cel.Types(&provenancePredicatev1.BuildDefinition{}), // there's no release with this type definition in in-toto/attestation, I've used go get @ commit
	cel.Types(&provenancePredicatev1.RunDetails{}),
	cel.Declarations(
		decls.NewVar("buildDefinition", decls.NewObjectType("in_toto_attestation.predicates.provenance.v1.BuildDefinition")),
		decls.NewVar("runDetails", decls.NewObjectType("in_toto_attestation.predicates.provenance.v1.RunDetails")),
	),
)

rule := "buildDefinition.buildType == 'https://slsa-framework.github.io/github-actions-buildtypes/workflow/v1'"

ast, issues := env.Compile(rule)
if issues.Err() != nil {
	return issues.Err()
}

prog, err := env.Program(ast)
if err != nil {
	return err
}
out, details, err := prog.Eval(predicate)
...
```

The `predicate` is read in from a JSON file and passed in as `map[string]any` (it's read into a protobuf defined struct called statement, passed to the verification routine as `statement.Predicate.AsMap()`).

```jsonc
{
	"_type": "https://in-toto.io/Statement/v1",
	"subject": [
		{
			"digest": {
				"sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
			},
			"name": "foo"
		}
	],
	"predicateType": "https://slsa.dev/provenance/v1",
	"predicate": {
		"buildDefinition": {
			"buildType": "https://slsa-framework.github.io/github-actions-buildtypes/workflow/v1"
		},
		"runDetails": {
			"builder": {
				"id": "https://github.com/slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@refs/tags/v0.0.1"
			}
		}
	}
}
```

**Expected behavior**

The expression passes for this input with `buildDefinition.buildType`.

**Additional context**

I did some digging to understand what's happening, I don't know how useful this is.

```
<input>:1:16: undefined field 'buildType'
 | buildDefinition.buildType == 'https://slsa-framework.github.io/github-actions-buildtypes/workflow/v1'
 | ...............^
```

After poking around cel-go for a bit, I found that the type's fields are stored with their snake cased names (as they are defined in the .proto file). In https://github.com/google/cel-go/blob/master/common/types/pb/type.go#L94, dumping out `td.fieldMap` shows me:

```
map[build_type:in_toto_attestation.predicates.provenance.v1.BuildDefinition.build_type `oneof=false` external_parameters:in_toto_attestation.predicates.provenance.v1.BuildDefinition.external_parameters `oneof=false` internal_parameters:in_toto_attestation.predicates.provenance.v1.BuildDefinition.internal_parameters `oneof=false` resolved_dependencies:in_toto_attestation.predicates.provenance.v1.BuildDefinition.resolved_dependencies `oneof=false`]
```

Here, `td.typeName` is `in_toto_attestation.predicates.provenance.v1.BuildDefinition` and `name` is `buildType`.

For posterity's sake, I updated the expression to use `build_type` instead of `buildType`. In this instance, I ran into a different issue:

```
unsupported field selection target: (map[string]interface {})map[buildType:https://slsa-framework.github.io/github-actions-buildtypes/workflow/v1]
```

In this case, I'm hitting https://github.com/google/cel-go/blob/master/common/types/pb/type.go#L251 during `prog.Eval` as it evaluates `buildDefinition.build_type` (the error is raised from `absoluteAttribute.Resolve`).

The repository where I'm prototyping all of this can be found here: https://github.com/adityasaky/in-toto-attestation-verifier/blob/501514172b01c32f010a0b8174d65efe3c707605/verifier/rules.go

**Comment by TristonianJones** [comment]
@adityasaky the expected behavior is that CEL will evaluate over the `snake_case` fields as they are defined in the protobuf.

In terms of the error, it looks like you're passing in a map value rather than a protobuf object type, so the attribute resolver is complaining about the difference between the expected type (protobuf) and the actual type (`map[string]any`).  If you're declaring a protobuf type, then the expectation is that proto reflection will be used to resolve the field. At least, this is my best guess as to what's happening based on what I've looked at so far.

-Tristan

**Comment by adityasaky** [comment]
@TristonianJones thanks for the quick response! I amended the code to pass in the Provenance as a proto message (https://github.com/in-toto/attestation/blob/main/go/predicates/provenance/v1/provenance.pb.go#L30) but I'm facing this issue in the interpreter (https://github.com/google/cel-go/blob/master/cel/program.go#L323):

```
invalid input, wanted Activation or map[string]any, got: (*v1.Provenance)build_definition:{build_type:"https://slsa-framework.github.io/github-actions-buildtypes/workflow/v1"}  run_details:{builder:{id:"https://github.com/slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@refs/tags/v0.0.1"}}
```

I looked through the examples and if I'm not mistaken, most of them do use `map[string]any` as the argument to `Eval()`, which is why I was passing in `.AsMap()` initially. Any ideas?

**Comment by TristonianJones** [comment]
@adityasaky The top-level variable names are keys in the `map[string]any` and the values are where you would introduce the protocol buffer instance:

```go
prg.Eval(map[string]any{'build_definition': &BuildDefinition{...}})
```

You may want to play around with the [cel-go codelab](https://codelabs.developers.google.com/codelabs/cel-go) to get a better sense of the general flow of inputs and outputs and working with protobuf data.

**Comment by adityasaky** [comment]
Got it, thanks! The model makes more sense to me now. :)
