### ISSUE TITLE
Pruner does not handle timestamp literals

### ISSUE THREAD

**Issue by charithe** [cel-expr/cel-go#785]
It looks like `types.Timestamp` is not handled here: https://github.com/google/cel-go/blob/e517cf50ea3388089d22394f1ff46f2d51d096ce/interpreter/prune.go#L97

Also, I am curious to know why a `Duration` literal is turned into a [string conversion](https://github.com/google/cel-go/blob/e517cf50ea3388089d22394f1ff46f2d51d096ce/interpreter/prune.go#L111-L125) instead of a straight literal like this:

```go
	case types.Duration:
		p.state.SetValue(id, val)
		return p.createLiteral(id, 
			&exprpb.Constant{ConstantKind: &exprpb.Constant_DurationValue{DurationValue: durationpb.New(v.Duration)}}), true
```

Lastly, are there any plans to extend pruning to simplify a constant expression like `timestamp("2023-07-25") > timestamp("2023-06-25")` to just `true`?

Thanks.

**Comment by TristonianJones** [comment]
@charithe the duration constant is deprecated and shouldn't be used. If you'd like support for timestamps it can be added. Is that what you're requesting?

**Comment by charithe** [comment]
> duration constant is deprecated

I see. Thanks for the clarification. 

> If you'd like support for timestamps it can be added. Is that what you're requesting?

Yes please. It'd be good if timestamps are supported because we use them quite extensively.

**Comment by charithe** [comment]
Actually this seems to have been a red herring. I mistakenly thought that timestamp literals were removed in the new version but turns out that they never existed! Thank you very much for the quick response and apologies for the confusion 🙏🏽

**Comment by TristonianJones** [comment]
@charithe I don't mind adding them. I'm overhauling the expression representation now, and have to update the pruner quite a bit, so I'll include the updates there.
