### ISSUE TITLE
Trouble building with protovalidate-go for `no field or method` errors

### ISSUE THREAD

**Issue by emahiro** [cel-expr/cel-go#811]
**Describe the bug**

I'm using cel-go via [protovalidate-go](https://github.com/bufbuild/protovalidate-go), but I found the build failed for `no field or method` errors in Ast expressions.

**To Reproduce**
Check which components this affects:

- [x]  parser
- [ ]  checker
- [ ]  interpreter

**Environment**

- protovalidate-go v0.2.1
- go v1.21.0
- github.com/google/cel-go v0.17.1

**Expected behavior**

No trouble in building the project using protovalidate-go.

**Additional context**

```sh
# github.com/google/cel-go/common/debug
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/common/debug/debug.go:173:13: entry.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/common/debug/debug.go:197:13: entry.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
# github.com/google/cel-go/parser
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/helper.go:125:4: unknown field OptionalIndices in struct literal of type expr.Expr_CreateList
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/helper.go:142:3: unknown field OptionalEntry in struct literal of type expr.Expr_CreateStruct_Entry
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/helper.go:162:3: unknown field OptionalEntry in struct literal of type expr.Expr_CreateStruct_Entry
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/helper.go:263:6: unknown field OptionalIndices in struct literal of type expr.Expr_CreateList
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/helper.go:263:32: listExpr.GetOptionalIndices undefined (type *expr.Expr_CreateList has no field or method GetOptionalIndices)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/unparser.go:310:24: l.GetOptionalIndices undefined (type *expr.Expr_CreateList has no field or method GetOptionalIndices)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/unparser.go:378:12: entry.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/unparser.go:402:12: entry.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
# github.com/google/cel-go/common/ast
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/common/ast/expr.go:509:34: l.ToExpr().GetListExpr().GetOptionalIndices undefined (type *expr.Expr_CreateList has no field or method GetOptionalIndices)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/common/ast/expr.go:527:13: e.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/common/ast/expr.go:588:13: f.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
```

**Comment by TristonianJones** [comment]
@emahiro I'd consider filing an issue with protovalidate-go since the method `GetOptionalIndices` should exist on the message of that type; however, if you could provide some more context about the provided input and expected output this would help considerably.

What version of the CEL protobuf are you using?

**Comment by emahiro** [comment]
@TristonianJones 
Sorry, I don't know how to find `version of the CEL protobuf`..., but I will describe my code to intent to use CEL via protovalidate-go@v0.2.1 in case of using with connect-go@v1.8.0.

In this code, I want to build my go code.

My proto file using `protovalidate` is below.

```proto
syntax="proto3";

package proto.greet.v1;

import "buf/validate/validate.proto";

message GreetRequest {
  string  user_name = 1 [(buf.validate.field).string.min_len = 3];
}

// 
```

And protovalidate version desribed in `buf.lock` is below.

```yaml
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: bufbuild
    repository: protovalidate
    commit: 1c33ebd9ecfa4653b8c1e662f84d1acf
    digest: shake256:4e3d93b2859a799ed4c08f530c62da1647cb85adacb3ff085dff6959a8d0a73989f3b8527145ee8b0783cd4e5264eaf0c0a76c206404f9520fce608b525559cb
```

When I tried to use protovalidate via [protovalidate-go](https://github.com/bufbuild/protovalidate-go) according to its README and [protovalidate](https://github.com/bufbuild/protovalidate) README, the errors described `Additional context` is occurred and failed to build my go code.

Sample is below.

```go
func (s *GreeterService) Greet(ctx context.Context, req *connect.Request[v1.GreetRequest]) (*connect.Response[v1.GreetResponse], error) {
	v, err := protovalidate.New()
	if err != nil {
		return nil, err
	}
	if err := v.Validate(req.Msg); err != nil {
		// error handling
	}
	//
}
```

**Comment by TristonianJones** [comment]
@emahiro I'm sorry, but I can't really speak to how buf.build is behaving here. Could you try reaching out to them instead? I suspect this is related to the dependencies pulled into your build where, for some reason that's not clear to me, you're getting a version of this protobuf which might be quite old: 

https://github.com/googleapis/googleapis/blob/master/google/api/expr/v1alpha1/syntax.proto

I hope that helps. If you create an issue in the protovalidate project would you mind cross-linking it here?

**Comment by emahiro** [comment]
@TristonianJones 

Thank you for replying.
I will create an issue in `protovalidate-go` project 👍

**Comment by emahiro** [comment]
@TristonianJones 
I fixed my troubles for protovalidate-go team supports, so I closed this issue.

Thank you your support!
