### ISSUE TITLE
CEL match enum field

### ISSUE THREAD

**Issue by federicocodo** [cel-expr/cel-go#828]
It's not a bug but an help me report because i cannot find any example of what i'm trying to do. I'm trying to use the CEL expression with `Dapr` in dotnet 6 for matching my cloud events, i found in the CEL [markdown](https://github.com/google/cel-spec/blob/master/doc/langdef.md) that i can match my cloud event using my enum values.
I have an object like:
```json
{
  "Id": "abc123",
  "Operation": 0
}
```

Where  `Operation` is my enum field wich contains a value that could be match with the value inside the enum class (like every language `message.Operation == EnumOperation.Day`).
At the moment i'm using the `int` conversion, so the CEL expression is structured like:
```proto
int(event.data.operation) == 0
``` 
There is a way for matching using the enum values?
For example like this:
```proto
event.data.operation == myPackage.namespace.enumClass.Day
```
Thank you in advance

**Comment by TristonianJones** [comment]
Hi @federicocodo, the last example should work just fine:  

`event.data.operation == myPackage.namespace.enumClass.Day`

There's a similar example in the `interpreter/interpreter_test.go`:

https://github.com/google/cel-go/blob/509c1d6161f0ae6bbb91cab1e65daeefb0109316/interpreter/interpreter_test.go#L1118-L1121
