### ISSUE TITLE
ANTLRv4 - bad import?

### ISSUE THREAD

**Issue by adev73** [cel-expr/cel-go#829]
**Describe the bug**
Attempting to do `go get -u ./...` on any project conting google/cel-go fails with this error:
```
go: github.com/antlr/antlr4/runtime/Go/antlr/v4@v4.0.0-20230828164656-e0df58f5185c: parsing go.mod:
        module declares its path as: github.com/antlr4-go/antlr/v4
                but was required as: github.com/antlr/antlr4/runtime/Go/antlr/v4
        restoring github.com/antlr/antlr4/runtime/Go/antlr/v4@v4.0.0-20230305170008-8188dc5388df
```

**To Reproduce**
Create a brand new Go project with the following main.go (ignore the fact it's nonsense...):
```
package main

import (
	"log"

	"github.com/google/cel-go/cel"
)

func main() {
	var v cel.Kind

	log.Printf("%v", v)
}
```
Run `go mod init some-name`, then `go mod tidy` (all good so far)
Run `go get -u ./...`

Result:
```
go: github.com/antlr/antlr4/runtime/Go/antlr/v4@v4.0.0-20230828164656-e0df58f5185c: parsing go.mod:
        module declares its path as: github.com/antlr4-go/antlr/v4
                but was required as: github.com/antlr/antlr4/runtime/Go/antlr/v4
        restoring github.com/antlr/antlr4/runtime/Go/antlr/v4@v4.0.0-20230305170008-8188dc5388df
go: github.com/antlr/antlr4/runtime/Go/antlr/v4@v4.0.0-20230828164656-e0df58f5185c: parsing go.mod:
        module declares its path as: github.com/antlr4-go/antlr/v4
                but was required as: github.com/antlr/antlr4/runtime/Go/antlr/v4
        restoring github.com/antlr/antlr4/runtime/Go/antlr/v4@v4.0.0-20230305170008-8188dc5388df
go: upgraded github.com/stoewer/go-strcase v1.2.0 => v1.3.0
go: upgraded golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e => v0.0.0-20230817173708-d852ddb80c63
go: upgraded golang.org/x/text v0.8.0 => v0.12.0
go: upgraded google.golang.org/genproto/googleapis/api v0.0.0-20230525234035-dd9d682886f9 => v0.0.0-20230822172742-b8732ec3820d
go: upgraded google.golang.org/genproto/googleapis/rpc v0.0.0-20230525234030-28d5490b6b19 => v0.0.0-20230822172742-b8732ec3820d
go: upgraded google.golang.org/protobuf v1.30.0 => v1.31.0
```

**Expected behavior**
A clean update of all packages

**Comment by l46kok** [comment]
Related: https://github.com/google/cel-go/pull/724. The latest update in ANTLR 4.13 changed the package names that needs to be reflected in cel-go. The aforementioned PR should address this but we haven't been able to merge it in due to a potential concurrency issue surfaced.

**Comment by TristonianJones** [comment]
@adev73 the concurrency issue has been raised with ANTLR devs, so hopefully we'll be able to pick up the changes sooner rather than later.

**Comment by pierrre** [comment]
I think they moved to this new repo https://github.com/antlr4-go/antlr
Could you update the import on your side ?

**Comment by TristonianJones** [comment]
@pierrre there's unfortunately a concurrency issue with the latest version of ANTLR Go (even in the new repo). We won't upgrade until it's resolved. ANTLR team is aware.

**Comment by glerchundi** [comment]
@TristonianJones do you have the issue reference to keep track of their progress? Thanks 🙏
