### ISSUE TITLE
go mod tidy fails with `ambiguous import: found package ` error

### ISSUE THREAD

**Issue by aldas** [cel-expr/cel-go#830]
When adding `github.com/google/cel-go v0.17.6`  to a project. After that `go mod tidy` will fail with following error:

```bash
go: gitlab.com/x/y/console/pkg/datastorage imports
        github.com/google/cel-go/cel imports
        google.golang.org/genproto/googleapis/api/expr/v1alpha1: ambiguous import: found package google.golang.org/genproto/googleapis/api/expr/v1alpha1 in multiple modules:
        google.golang.org/genproto v0.0.0-20230410155749-daa745c078e1 (/home/x/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230410155749-daa745c078e1/googleapis/api/expr/v1alpha1)
        google.golang.org/genproto/googleapis/api v0.0.0-20230525234035-dd9d682886f9 (/home/x/go/pkg/mod/google.golang.org/genproto/googleapis/api@v0.0.0-20230525234035-dd9d682886f9/expr/v1alpha
```

**Comment by TristonianJones** [comment]
@aldas in addition to the PR that @l46kok created, I believe that the go.mod version in `gitlab.com/x/y/console/pkg/datastorage` would need to be updated to a newer version if its already depending on genproto since there was module split in the genproto repo around 5/26 this year.

**Comment by aldas** [comment]
If it is possible could someone tag a release? and maybe through GitHub so https://github.com/google/cel-go/releases would be also updated and that  "Release" block on right side of the main page, would show latest release.  just for convenience

**Comment by aldas** [comment]
p.s. github actions can do release when tag is pushed. Example https://github.com/stretchr/testify/pull/1354/files

**Comment by TristonianJones** [comment]
Thanks @aldas Usually I put together releases manually, but I'll add support for release generation on tag since we do periodically backport fixes.
