### ISSUE TITLE
[Question] Expression functions isEmpty, isNotEmpty, notIn

### ISSUE THREAD

**Issue by nevesgustavo** [cel-expr/cel-go#834]
I'm building an application using **cel-go** and it's planned to use a lot of operators, I could find almost all of them but not the operators/functions below:
**is empty**
**is not empty**
**not in** 

I just would like to know if these operators exists to build expressions if not I think that I can use a custom function.

Thanks in advance team :)

**Comment by TristonianJones** [comment]
@nevesgustavo these functions don't exist, but I wouldn't mind an `isEmpty()` method being introduced for `bytes`, `string`, `list`, and `map` types as this would simplify a common check like so: `list.size() == 0` -> `list.isEmpty()`. 

I'm not sure how I feel about `isNotEmpty()` as a function, but I could be convinced.

The `not in` is the same as `!(value in list)`, but I'd rather not introduce `not` as a keyword.

**Comment by nevesgustavo** [comment]
Thanks for your answer @TristonianJones 🙂, I tried to use the size() it works fine when the property is not nil in the map otherwise It throws an error to compile.

**Comment by TristonianJones** [comment]
@nevesgustavo Maybe you could give me some examples of how you intend to use the operators? I'm not sure I follow how you're hitting an error on `size()` and where the `nil` is coming from.

**Comment by nevesgustavo** [comment]
Hello @TristonianJones, I hope you are having a great week. Yep in the example below when **order.status is nil** it'll throw this error **no such overload: size**, but if we change to "" it'll run and return false. Thanks for your help.

```go
package main

import (
	"fmt"
	"github.com/golang/glog"
	"github.com/google/cel-go/cel"
	"reflect"
	"strings"
)

func main() {
	data := map[string]interface{}{
		"order.id":       2222,
		"order.status":   nil,
		"payment.id":     11111,
		"payment.status": nil,
	}

	env, err := cel.NewEnv(
		cel.Variable("order.id", cel.IntType),
		cel.Variable("order.status", cel.StringType),
	)

	if err != nil {
		fmt.Printf("Error creating environment: %v\n", err)
		return
	}

	ast := compile(env,
		`order.id == 2222 && size(order.status) > 0`,
		cel.BoolType)

	program, _ := env.Program(ast)

	out, _, err := program.Eval(data)

	if err != nil {
		fmt.Println(fmt.Sprintf("error when running eval: %v", err))
		return
	}

	fmt.Println(fmt.Sprintf("Result: %v", out))
}

func compile(env *cel.Env, expr string, celType *cel.Type) *cel.Ast {
	ast, iss := env.Compile(expr)
	if iss.Err() != nil {
		glog.Exit(iss.Err())
	}
	if !reflect.DeepEqual(ast.OutputType(), celType) {
		glog.Exitf(
			"Got %v, wanted %v result type", ast.OutputType(), celType)
	}
	fmt.Printf("%s\n\n", strings.ReplaceAll(expr, "\t", " "))
	return ast
}
```

**Comment by TristonianJones** [comment]
I think if you want to communicate that the value is optional, you should use the `cel.OptionalTypes()` feature.

Your environment would change like so:

```go
	env, err := cel.NewEnv(
		cel.OptionalTypes(),
		cel.Variable("order.id", cel.IntType),
		cel.Variable("order.status", cel.OptionalType(cel.StringType)),
	)
```

The expression and input data would also shift a bit:

```go
	// Alternatively you can write: order.status.orValue("").size() > 0
	ast := compile(env,
		`order.id == 2222 && order.status.hasValue()`,
		cel.BoolType)	
```

```go	
	// Use types.OptionalNone to indicate the value is not present
	data := map[string]interface{}{
		"order.id":       2222,
		"order.status":   types.OptionalNone,
		"payment.id":     11111,
		"payment.status": types.OptionalNone,
	}
```
