### ISSUE TITLE
Deprecation notice recommends nonexistent replacement

### ISSUE THREAD

**Issue by akshayjshah** [cel-expr/cel-go#837]
**Describe the bug**

`cel.OptCheckStringFormat` is [deprecated](https://pkg.go.dev/github.com/google/cel-go@v0.18.0/cel#EvalOption), directing users to `ext.ValidateFormatString()`. However, `ext.ValidateFormatString` [doesn't seem to exist](https://github.com/search?q=repo:google/cel-go+ValidateFormatString&type=code). Should this deprecation notice be pointing to `ext.StringsValidateFormatCalls` instead?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Additional context**
None :)

**Comment by TristonianJones** [comment]
@akshayjshah thanks, good catch. I'll update the notice.
