### ISSUE TITLE
Breaking Change in Conversion of Custom Types to Standard Types Post Upgrade from v0.16.0 to v0.18.1

### ISSUE THREAD

**Issue by jackchuka** [cel-expr/cel-go#846]
Hello Maintainers,

I recently upgraded the cel-go library from version `0.16.0` to `0.18.1` and encountered a breaking change affecting the conversion of all custom types to standard types in my project.

I have gone through the [release notes](https://github.com/google/cel-go/releases) for version 0.18.1, but I couldn’t pinpoint the exact change that might have caused this behavior. I kindly request any guidance on resolving this issue or suggestions for potential workarounds.

Thank you for your time and consideration.

**Describe the bug**
Post-upgrade, all conversions from custom types to standard types started failing, which was working seamlessly in the previous version 0.16.0. This change in behavior has led to errors and disrupted the functionality of my project significantly.

**To Reproduce**
- [ ]  parser
- [ ]  checker
- [x]  interpreter

1. Define custom types and implement necessary conversion methods for standard type conversions.
2. Use the cel-go library version 0.16.0 and observe successful conversions of custom types to standard types.
3. Upgrade the cel-go library to version 0.18.1.
4. Observe the failure in conversions and the resultant errors.

Sample expression and input that reproduces the issue:

Example of my custom type
```go
var (
	TimeType = types.NewTypeValue("TimeHHMM",
		traits.ComparerType,
		traits.AdderType,
		traits.SubtractorType)
	durationValueType = reflect.TypeOf(&dpb.Duration{})
	reHHMM            = regexp.MustCompile(`^\d+:\d{2}$`)
)

type TimeHHMM struct {
	Hour   int
	Minute int
}


func (t TimeHHMM) String() string {
	return fmt.Sprintf("%02d:%02d", t.Hour, t.Minute)
}

func (t TimeHHMM) Int() int {
	return t.Hour*100 + t.Minute
}
```

Test setup:

#### Ex. 1 
```go
expr := `string(time(123))`
// ...
ast, iss := env.Compile(expr)
if iss.Err() != nil {
	t.Fatal(iss.Err())
}
prg, err := env.Program(ast)
if err != nil {
	t.Fatalf("program creation error: %s\n", err)
}
```

produces: `runtime error: no such overload: string(TimeHHMM)` error 
expects: `"01:23"`

#### Ex. 2
```go
expr := `int(time(123))`
// ...
ast, iss := env.Compile(expr)
if iss.Err() != nil {
	t.Fatal(iss.Err())
}
prg, err := env.Program(ast)
if err != nil {
	t.Fatalf("program creation error: %s\n", err)
}
```

produces: `runtime error: no such overload: int(TimeHHMM)` error 
expects: `123`

**Expected behavior**
The custom types should convert to standard types seamlessly, as they did in version 0.16.0.

**Additional context**

**Comment by Mistat** [comment]
In version 0.16.0, the String() and Int() receivers were being called, but starting from version 0.17.0 and onwards, Overload of standard functions are hard-coded as shown in the following source code.

https://github.com/google/cel-go/blob/master/common/stdlib/standard.go

For example, is it possible to add an Overload to TypeConvertString?

**Comment by TristonianJones** [comment]
@Mistat @jackchuka thanks for raising this. I'm afraid this is a case of Hyrum's law where there was something working well, but not intentionally. The change that was introduced to create the specific overloads in question was actually designed to make it easier to explicitly extend built-in operators like `string()` and `int()`:

```go
cel.Function(overloads.TypeConvertString,
   cel.Overload("time_to_string", []*cel.Type{TimeType}, cel.StringType,
     cel.UnaryBinding(func(val ref.Val) ref.Val {
        t := val.(TimeHHMM)
        return types.String(t.String())
    }))
```

As long as you're not adding an overlapping overload signature, the overloads will aggregate and support dynamic dispatch and direct invocation when strong typing info is available.

Hope that helps!

-Tristan

**Comment by Mistat** [comment]
@TristonianJones  Thank you for the explanation. I now understand it very well.
I was mistaken in thinking that the definition of a function would be overwritten; it actually gets merged!

https://github.com/google/cel-go/blob/fc501a3a9c46dca28c79477a0fd8ae48a2df8ec8/cel/decls.go#L185-L190

Many thanks,

Misato

**Comment by jackchuka** [comment]
Thank you so much for the quick reply @TristonianJones!
And thanks @Mistat for the quick confirmation.
I believe the issue is now resolved so closing this 👍

**Comment by TristonianJones** [comment]
@jackchuka @Mistat my apologies again for the inconvenience, but the previous way the declarations were working made it possible to overwrite existing declarations when people really intended to extend them. I'm glad the suggestion works for you and I'll try to be more careful about documenting how to breaking changes in the CEL release notes going forward. I don't expect any other changes like this one in the future though.
