### ISSUE TITLE
Registering custom type casts with CEL env

### ISSUE THREAD

**Issue by jon-whit** [cel-expr/cel-go#854]
I have a custom type that represents an IPAddress, and I'd like to be able to write IPAddress string literals in my CEL expression and cast them so that I can apply the overloaded functions to them inline. For example, consider the following CEL expression:

```
ipaddress("192.168.0.2").in_cidr("192.168.0.0/24")
```

This should return a boolean `true` value.

Do you have any examples of how to achieve this? If I pass in the IPAddress as a parameter I am able to bind, convert, and evaluate the expression above, but I'd like to be able to apply the type cast inline without the intermediate variable.

**Comment by jon-whit** [comment]
I found an example in Kubernetes for urls. Is this the recommended way of achieving this?

https://github.com/kubernetes/apiextensions-apiserver/blob/v0.25.15/pkg/apiserver/schema/cel/library/urls.go

**Comment by TristonianJones** [comment]
Hi Jonathan,

> Do you have any examples of how to achieve this? If I pass in the IPAddress as a parameter I am able to bind, convert, and evaluate the expression above, but I'd like to be able to apply the type cast inline without the intermediate variable.

Could you tell me what you mean regarding the `IPAddress` as a parameter that you're able to bind, convert, and evaluate? Do you mean something like this? `ip_var.in_cidr(...)`

If you're looking for converting strings inline, then creating an opaque `ipaddress` type, e.g. `cel.OpaqueType('ipaddress')` and binding functions to it like K8s does is a good example.

**Comment by jon-whit** [comment]
> If you're looking for converting strings inline, then creating an opaque ipaddress type, e.g. cel.OpaqueType('ipaddress') and binding functions to it like K8s does is a good example.

This is what I was trying to do. That k8s example worked perfect for my use case 👍
