### ISSUE TITLE
Return unknown parameters despite the expression being evaluable

### ISSUE THREAD

**Issue by jon-whit** [cel-expr/cel-go#856]
Could you share some reference code that shows to accumulate the list of unknown parameters even if the expression is evaluable? It's not clear at all from the documentation how I may achieve this. Here's what I am looking for:

* Define an expression involving two parameters `x` and `y`
  ` x < 10 || y < 15`
  
* Bind parameter `x: 5` before evaluation.

* Evaluate the expression (should return `true`), **but also return the list of other unknowns encountered** 

I'm using Env.PartialVars to construct a partial activation and then evaluating the expression, but in this case since `5 < 10` the first branch of the bool returns true and so the Program.Eval returns a non `Unknown` output. Here's some sample code:
```go
activation, err := celEnv.PartialVars(typedParams)
if err != nil {
	// handle error
}

out, details, err := celProgram.Eval(activation)
if err != nil {
	// handle error
}

var missingParameters []string
if celtypes.IsUnknown(out) {
       // I don't get here because the evaluation produces a concrete boolean value.

	unknownCELVal := out.(*celtypes.Unknown)

	for _, id := range unknownCELVal.IDs() {
		trails, ok := unknownCELVal.GetAttributeTrails(id)
		if ok {
			for _, attributeTrail := range trails {
				missingParameters = append(missingParameters, attributeTrail.String())
			}
		}
	}
}

return out, missingParameters
```
How do I get the unknown bindings from the PartialActiviation?

**Comment by TristonianJones** [comment]
@jon-whit when unknowns are encountered, they'll be present in the `details` if you enable `cel.EvalOptions(cel.OptStateTracking)` during the program generation. You'll have to search for them and they will not be complete if there are unknowns encountered within a loop. 

In general, we don't see this ask, so I'm curious what your use case is.

-Tristan
