### ISSUE TITLE
Is it possible to define a getter?

### ISSUE THREAD

**Issue by spacewander** [cel-expr/cel-go#876]
Currently, it is possible to customize methods in a custom object, for example:
https://github.com/kubernetes/apiextensions-apiserver/blob/v0.25.15/pkg/apiserver/schema/cel/library/urls.go

Is it possible to define a getter instead of calling the method?

For instance, by defining a getter, we can write `x.scheme` to invoke a `Scheme()` method defined in the object x. So far it looks like `x.scheme` will just return `x.Scheme` field directly.

**Comment by TristonianJones** [comment]
@spacewander you can write a getter, but it would still appear to be a function call rather than a field access, e.g.`x.scheme()` You can do the same for objects with fields as for opaque types (like k8s urls) which don't have any accessible fields.

Hope that helps.

-Tristan

**Comment by spacewander** [comment]
Thanks!
