### ISSUE TITLE
Has macro returns no such key error

### ISSUE THREAD

**Issue by parsnips** [cel-expr/cel-go#912]
**Describe the bug**
When executing the `has` macro on nested paths, will throw a no such key error instead of `false`.

Consider the following json in context as `doc`

```json
{
  "fizz": {
     "buzz": {
         "baz": "biz"
      }
   }
 }
```

if you execute the following has macros:

| macro | result |
|--------|-------|
| `has(doc.fizz.buzz.baz)` | `true` |
| `has(doc.fizz.baz)` | `false` |
| `has(doc.fizz.baz.buzz)` | input: evaluate [...]: `has(document.fizz.baz.buzz)`, no such key: baz |

**Expected behavior**

Expect `has` macro to return false instead of an error.

**Comment by TristonianJones** [comment]
The `has` macro only operates on the last field in the field selection. If you're looking for a more robust check, consider using optional types: `doc.?fizz.baz.buzz.hasValue()`
