### ISSUE TITLE
field selection with ? on null now produces an error

### ISSUE THREAD

**Issue by mtaufen** [cel-expr/cel-go#937]
**Describe the bug**
I think this change happened in https://github.com/google/cel-go/pull/922. 

For example, given yaml like:

```
foo:
  bar: null
```

and CEL like:

```
foo.?bar.?baz.orValue("not there")
```

behavior changes from returning "not there" to throwing a no such key error.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

**Expected behavior**
Expected "not there" to be returned. 

**Additional context**

I tried reverting the change from https://github.com/google/cel-go/pull/922 and it makes things work the way I expect.

**Comment by TristonianJones** [comment]
Thanks for the report. I'll give it a look.
