### ISSUE TITLE
Type checker and runtime types differ for native byte array in function overloads

### ISSUE THREAD

**Issue by patrickpichler** [cel-expr/cel-go#953]
**Describe the bug**
When using `ext.NativeTypes` with a byte array field, there CEL runtime  determines different types for at compile time
and at runtime.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [x]  checker
- [x]  interpreter

Sample expression and input that reproduces the issue:

```go
import (
	"encoding/hex"
        "fmt"
	"github.com/google/cel-go/cel"
	"github.com/google/cel-go/common/types"
	"github.com/google/cel-go/common/types/ref"
	"github.com/google/cel-go/common/types/ext"
)

type File struct {
	Hash [32]byte
}

func main() {
	reg := types.NewEmptyRegistry()
	env, err := cel.NewEnv(
		cel.CustomTypeAdapter(reg),
		cel.CustomTypeProvider(reg),
		ext.NativeTypes(
			reflect.TypeOf(&File{}),
		),
		cel.Variable("file", cel.ObjectType("main.File")),
		cel.Function("hex",
			cel.Overload("hex_bytes", []*cel.Type{types.BytesType}, types.StringType,
				cel.UnaryBinding(func(value ref.Val) ref.Val {
					bytes := value.(types.Bytes)
					return types.String(hex.EncodeToString(bytes))
				}))),
	)
	if err != nil {
		panic(err)
	}
	ast, iss := env.Compile(`hex(file.Hash)`)
	if iss.Err() != nil {
		panic(iss.Err())
	}
	prog, err := env.Program(ast)
	if err != nil {
		panic(err)
	}
	out, _, err = prog.Eval(map[string]any{
		"file": File{
			Hash: [32]byte{},
		},
	})
	if err != nil {
		panic(err)
	}
        fmt.Println(out)
}
```

**Actual behavior**
Program fails with
```
panic: no such overload: hex(list)
```

**Expected behavior**
Program should not panic and return the hex encoded bytes of the `file.Hash` field. 

**Additional context**
I've been trying to debug the issue and if i switch the overload function to accept a `types.ListType`, it fails at 
compile time. It only works if both overloads are defined. 

I think the issue is caused by the way the `nativeTypeProvider` implements `NativeToValue`. It only only ever returns a
`types.Bytes` for `[]bytes`, not for byte arrays ([here](https://github.com/google/cel-go/blob/master/ext/native.go#L328)), whereas the `convertToCELTypes` function specifies the `types.Bytes` type for byte arrays ([here](https://github.com/google/cel-go/blob/f7b83ae0424c68b21d1209d8dcf97f668dbf214a/ext/native.go#L387)).

**Comment by TristonianJones** [comment]
Closed by #958
