### ISSUE TITLE
Question: How should callers check for unpopulated root variables

### ISSUE THREAD

**Issue by jacobmikesell** [cel-expr/cel-go#970]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [ ] The change is large enough it can't be addressed with a simple Pull Request

**Change**
Summary of the proposed change and some details about what problem
it helps solve.

I'm curious if there is a better way to test precense/defaultness of a protobuf message when its not a "field" but at the root of the cel AST

**Example**
```protobuf

message TestMessage {
  string name = 1;
  int64 age = 2;
  bool adult = 3;
  google.type.Decimal height = 4;
  repeated string string_list = 5;
  map<string, int32> string_int_map = 6;
  google.type.Date birthday = 7;
 }
```

```go
msg := &testproto.TestProto{}	
env, _ := cel.NewEnv(cel.ProtoContext(msg))

//Doesnt work`msg`
env.Compile("birthday == null")

//Doesnt work with `msg`
env.Compile("has(birthday)")

//works with `msg` but is a hassle to explain/requires people to know the namespace of message, error prone
env.Compile("birthday == google.type.Date{}")

```

**Comment by TristonianJones** [comment]
Hi @jacobmikesell, you'll want to use optional values; however, this likely requires an update to the `ProtoContext` method to support generation of optional bindings for all fields such that set field are `optional.of(value)` and unset fields are `optional.none()`

**Comment by jacobmikesell** [comment]
@TristonianJones would this require `optional` to be used in the proto definition file? or do you mean that we could say (for only root message fields of type message) that they are optional in the cel context?

**Comment by TristonianJones** [comment]
@jacobmikesell I was referring to the cel-go notion of `cel.OptionalTypes()` to be enabled. When enabled, you could generation CEL-optional bindings for fields whose type are `optional_type(<field_type>)` and when unpopulated, the value would be `optional.none()`
