### ISSUE TITLE
AOT instead of JIT

### ISSUE THREAD

**Issue by quantumsheep** [cel-expr/cel-go#979]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [ ] The change is large enough it can't be addressed with a simple Pull Request
- [ ] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**

Hey ! 

I want to cache the compiled CEL expression in database to bypass the compilation phase each time I need to execute the expression. For that I need the binary representation or whatever of the expression.

* Is there a way to do it?
* Is this a good idea?

**Comment by TristonianJones** [comment]
Hi @quantumsheep, you would just use the output of the `Compile` step and store it as a protobuf if you need a binary rep. Then you'd convert it to a runtime `ast.AST` when you read it from the db and do all of the normal program plan steps. 

Hopefully, that makes sense, but if not I'd recommend looking at the `cel.AstToCheckedExpr` method as a way of getting the binary rep you're looking for.
