### ISSUE TITLE
Link to conformance dashboard in `README.md` leads to 404

### ISSUE THREAD

**Issue by bitwizeshift** [cel-expr/cel-go#984]
> [!IMPORTANT]
> This is not a bug with the language itself, just the documentation

**Describe the bug**

It looks like at some point the `README.md` fell out-of-sync with reality, and the link to the "Conformance dashboard" on line 34 now leads to a 404 webpage.

**To Reproduce**

Check which components this affects:

- [ ]  parser
- [ ]  checker
- [ ]  interpreter

(Not applicable)

**Steps for Reproduction**

Click the README link from [these lines](https://github.com/google/cel-go/blame/37d5b961f5da8ca2a21ccb565af63faaf84ed2fa/README.md#L33-L34). Specifically the text that says (verbatim copied from the current state):

> A dashboard that shows results of cel-go conformance tests can be found [here](https://k8s-testgrid.appspot.com/google-cel#cel-go).

The `here` link yields:

![404](https://github.com/user-attachments/assets/1749a6a6-ff76-4c5c-9819-2e3aff389631)

**Expected behavior**

The publicly linked dashboard resolves to a viewable dashboard

**Comment by TristonianJones** [comment]
I'll update the docs. I believe we've turned down the public dashboard.
