### ISSUE TITLE
[Policy compiler] Match blocks with missing outputs are silently ignored

### ISSUE THREAD

**Issue by seirl** [cel-expr/cel-go#999]
**Describe the bug**
Match blocks with missing outputs are silently ignored.

**To Reproduce**

- [x]  policy compiler

Sample expression and input that reproduces the issue:
```cel
rule:
  match:
  - condition: "!a.hasValue()"
  - condition: "!a.field.hasValue()"
  - output: "a.field.value()"
```

This gets compiled to the following expression:

```
a.field.value()
```

**Expected behavior**

Two possible behaviors would work here:

1. this should return an error because some match blocks don't have a rule or an output.
1. the expression should instead be compiled to a rule with an optional output:

```
!a.hasValue() ? optional.none() : !a.field.hasValue() ? optional.none() : a.field.value()
```

**Comment by TristonianJones** [comment]
For conditions, they should have either a rule or an output, so this should be an error.
